import { mkdir, writeFile } from 'node:fs/promises';
import { build } from 'esbuild';

await mkdir(new URL('../src/vendor/', import.meta.url), { recursive: true });

const result = await build({
  stdin: {
    contents: `
      import { createClient } from '@supabase/supabase-js';
      globalThis.supabase = Object.freeze({ createClient });
    `,
    resolveDir: process.cwd(),
    sourcefile: 'astraeon-supabase-entry.js',
    loader: 'js'
  },
  outfile: 'src/vendor/supabase-v2.js',
  write: false,
  bundle: true,
  minify: true,
  format: 'iife',
  platform: 'browser',
  target: ['es2020'],
  legalComments: 'eof',
  sourcemap: false,
  banner: {
    js: '/*! Astraeon vendored @supabase/supabase-js 2.91.0 — generated by npm run build:vendor */'
  }
});

const bundle = result.outputFiles[0].text.replace(/[\t ]+$/gm, '');
await writeFile('src/vendor/supabase-v2.js', bundle, 'utf8');

console.log('ASTRAEON VENDOR BUILD OK — Supabase JS 2.91.0');
