import assert from 'node:assert/strict';
import fs from 'node:fs';

const game = fs.readFileSync(new URL('../src/game-v2.js', import.meta.url), 'utf8');
const world = fs.readFileSync(new URL('../src/world-v2.js', import.meta.url), 'utf8');
const terrainTexture = game.match(/drawTerrainTexture\(ctx, tile, biome, x, y, size\) \{[\s\S]*?\n    drawShoreline/);
const shorelineRenderer = game.match(/drawShoreline\(ctx, tile, x, y, size\) \{[\s\S]*?\n    terrainChunk/);
const waterRenderer = game.match(/drawWater\(ctx, tile, x, y, size, now\) \{[\s\S]*?\n    drawRoad/);

assert.match(game, /const TERRAIN_CHUNK_TILES = 12/, 'O terreno detalhado deve ser cacheado em blocos pequenos.');
assert.match(game, /const TERRAIN_CHUNK_OVERLAP = 1/, 'Blocos do terreno devem possuir uma margem de sobreposição.');
assert.match(game, /terrainVisualCache = \{ world: null, chunks: new Map\(\) \}/, 'O cache visual deve ser isolado por mundo.');
assert.match(game, /drawTerrainTexture\(ctx, tile, biome, x, y, size\)/, 'O terreno deve possuir textura e relevo determinísticos.');
assert.ok(terrainTexture, 'A rotina de textura do terreno deve existir.');
assert.match(game, /return biome\.ground\[tile\.variant\]/, 'As variações menores do terreno devem ser preservadas.');
assert.match(game, /drawTerrainRelief\(ctx, x, y, size, eastSlope, southSlope\)/, 'O relevo suave entre tiles deve ser preservado.');
assert.match(terrainTexture[0], /if \(water\) \{\s*this\.drawWaterTileBase[\s\S]*\} else \{[\s\S]*drawTerrainRelief/, 'Água não deve receber relevo nem textura dos tiles terrestres.');
assert.doesNotMatch(terrainTexture[0], /const depth = ctx\.createRadialGradient/, 'Água não deve repetir gradientes radiais quadrados.');
assert.doesNotMatch(terrainTexture[0], /drawWaterBed/, 'Água não deve receber manchas fechadas que pareçam buracos ou lodo.');
assert.ok(waterRenderer, 'A rotina dedicada da superfície da água deve existir.');
assert.ok(shorelineRenderer, 'A rotina dedicada da margem da água deve existir.');
assert.match(game, /const WATER_VISUALS = Object\.freeze/, 'Parâmetros visuais da água devem ficar centralizados.');
assert.match(game, /baseTint:[\s\S]*deepTint:[\s\S]*shallowTint:[\s\S]*surfaceTint:[\s\S]*highlightTint:[\s\S]*rippleTint:[\s\S]*edgeTint:/, 'A paleta limpa e os tons de profundidade da água devem ficar centralizados.');
assert.match(game, /baseSpeed:[\s\S]*highlightSpeed:[\s\S]*rippleSpeed:[\s\S]*distortion:[\s\S]*surfaceOpacity:[\s\S]*highlightOpacity:[\s\S]*edgeInset:[\s\S]*edgeRadius:[\s\S]*isolatedRadius:/, 'Camadas e contorno visual da água devem possuir controles independentes.');
assert.match(game, /if \(tile\.kind === 'water'\) return WATER_VISUALS\.baseTint/, 'A água deve usar a base azul-esverdeada limpa do renderer.');
assert.match(game, /waterTileVisualCache = \{ world: null, tiles: new Map\(\) \}/, 'Ruído da água deve ser pré-calculado e reutilizado por tile.');
assert.match(game, /drawWaterTileBase\(ctx, tile, biome, x, y, size\)[\s\S]*edgeN&&edgeW[\s\S]*quadraticCurveTo/, 'A silhueta visual da água deve suavizar os cantos externos sem alterar os tiles lógicos.');
assert.match(waterRenderer[0], /baseTime[\s\S]*highlightTime[\s\S]*rippleTime/, 'Movimento da água deve usar três ritmos independentes.');
assert.match(waterRenderer[0], /quadraticCurveTo/, 'Brilhos da água devem ser curvos, curtos e irregulares.');
assert.doesNotMatch(waterRenderer[0], /ctx\.(ellipse|arc)\(/, 'Ondulações e correntes não devem desenhar círculos.');
assert.doesNotMatch(waterRenderer[0], /globalCompositeOperation|multiply|waterDeep|ctx\.fill\(/, 'Água animada não deve voltar a criar manchas escuras fechadas.');
assert.doesNotMatch(waterRenderer[0], /for\s*\(let px=/, 'Água não deve voltar a desenhar faixas paralelas por todo o tile.');
assert.doesNotMatch(waterRenderer[0], /ctx\.rect\(x,y,size,size\);ctx\.clip/, 'Animação não deve denunciar quadrados por recorte repetido.');
assert.match(game, /terrainSpeedMultiplier\(entity\)/, 'Movimento deve considerar o tipo de terreno.');
assert.match(game, /tile\?\.kind === 'water' \? \.55 : 1/, 'Água deve reduzir a velocidade do jogador.');
assert.doesNotMatch(game, /drawWaterWake/, 'A água não deve criar anéis circulares ao redor do jogador.');
assert.match(world, /if \(kind === 'water'\) blocked = false/, 'Água deve permanecer atravessável.');
assert.match(game, /renderStartX=Math\.max\(0,startX-TERRAIN_CHUNK_OVERLAP\)/, 'Chunks vizinhos devem se sobrepor para ocultar a grade grande.');
assert.match(game, /x:renderStartX \* size, y:renderStartY \* size/, 'A sobreposição deve manter o alinhamento do mundo.');
assert.match(game, /drawShoreline\(ctx, tile, x, y, size\)/, 'Água e terreno devem possuir transição de margem.');
assert.match(game, /if \(tile\.kind !== 'water'\) return/, 'A margem deve ser desenhada somente pelo lado da água, sem linha duplicada.');
assert.match(shorelineRenderer[0], /createLinearGradient[\s\S]*WATER_VISUALS\.edgeTint[\s\S]*addColorStop\(1,'rgba\(22,66,78,0\)'\)/, 'A profundidade da margem deve desaparecer suavemente na superfície.');
assert.doesNotMatch(shorelineRenderer[0], /style\.shore|waterDeep|multiply/, 'A margem não deve herdar cores de barro ou lodo do bioma.');
assert.match(game, /const waterNow=performance\.now\(\)/, 'O tempo da água deve ser calculado uma única vez por frame.');
assert.match(game, /drawWater\(ctx, tile, px, py, size, waterNow\)/, 'Todas as camadas devem compartilhar o instante do frame sem sincronizar suas fases.');
assert.doesNotMatch(waterRenderer[0], /performance\.now\(\)/, 'O renderer não deve consultar o relógio novamente para cada tile de água.');
assert.match(game, /createRadialGradient\(cx-5,baseY-31/, 'Copas de árvores devem receber volume por iluminação radial.');
assert.match(game, /tile\.object === 'crystal'[\s\S]*shadowBlur=10/, 'Cristais devem manter brilho volumétrico próprio.');
assert.match(game, /for \(let cy=chunkStartY;cy<chunkEndY;cy\+\+\)/, 'O frame deve desenhar chunks cacheados, não reconstruir todo o chão.');
assert.doesNotMatch(game, /setInterval\([^)]*drawTerrain/, 'O aprimoramento do mapa não pode criar polling de renderização.');

console.log('ASTRAEON MAP VISUALS V1 terrain, water, relief and objects validation OK');
