(function(global){
'use strict';
const $=s=>document.querySelector(s),$$=s=>Array.from(document.querySelectorAll(s));
const state={installed:false,contentObserver:null,spawnTimer:null,lineTimers:new Map(),drag:null,ownRows:[],ownSelected:null};
const client=()=>global.AstraeonAdminAuth?.client;
const userId=()=>global.AstraeonAdminAuth?.session?.user?.id||null;
const ed=()=>global.astraeonEditor;
const prod=()=>global.AstraeonAdminProductionV6;
const CLASS_LABELS={Warrior:'Guerreiro',Mage:'Mago',Archer:'Arqueiro',Assassin:'Assassino',Paladine:'Paladino'};
function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
function ensureStyle(){if(document.querySelector('link[data-admin-v63]'))return;const l=document.createElement('link');l.rel='stylesheet';l.href='src/admin-v63.css';l.dataset.adminV63='1';document.head.appendChild(l);}
function activateTab(button){const panel=$('#adminPanel');panel?.querySelectorAll('.admin-tab').forEach(t=>t.classList.toggle('active',t===button));}
function tabByText(text){const needle=text.toLocaleLowerCase('pt-BR');return $$('#adminPanel .admin-tabs .admin-tab').find(b=>b.textContent.trim().toLocaleLowerCase('pt-BR')===needle)||null;}
function visibleTitles(){const panel=$('#adminPanel');if(!panel)return;const title=panel.querySelector('.admin-head-copy b');if(title)title.textContent='ADMIN STUDIO';const subtitle=panel.querySelector('.admin-head-copy small');if(subtitle)subtitle.textContent='World Production · ferramentas administrativas em tempo real.';const brand=$('.studio-brand small');if(brand)brand.textContent='ADMIN STUDIO';document.title='ASTRAEON — ADMIN STUDIO';}
function explainGameplay(){const page=$('#adminContent .admin-page.active'),h=page?.querySelector('.admin-page-head h3');if(!h||h.textContent.trim()!=='Gameplay')return;h.textContent='Regras do Jogo';const p=page.querySelector('.admin-page-head p');if(p)p.textContent='Ajuste regras globais que influenciam combate, recompensas, corrida e recursos do servidor.';if(!page.querySelector('.gameplay-explain-v63')){const note=document.createElement('section');note.className='gameplay-explain-v63';note.innerHTML='<b>O que esta área controla?</b><span>Multiplicadores de dano, XP e ouro afetam o balanceamento global. God Mode serve para testes administrativos. Fôlego e corrida definem consumo, regeneração e velocidade. A mochila do Astraeon é fixa em 25 espaços.</span>';page.querySelector('.admin-grid')?.before(note);}const bag=$('#agBag');if(bag){bag.value='25';bag.disabled=true;bag.closest('.admin-field')?.classList.add('locked-field-v63');}}
async function ownCharactersPage(){const content=$('#adminContent');if(!content)return;content.innerHTML='<div class="admin-page active"><p class="admin-note">Carregando seus personagens…</p></div>';const{data,error}=await client().rpc('admin_list_characters_v6');if(error){content.innerHTML=`<div class="admin-page active"><div class="admin-warning">${esc(error.message)}</div></div>`;return;}state.ownRows=(data||[]).filter(r=>r.user_id===userId());if(!state.ownSelected||!state.ownRows.some(r=>r.character_id===state.ownSelected))state.ownSelected=state.ownRows[0]?.character_id||null;renderOwnCharacters();}
function ownCard(r){const c=global.AstraeonWorld?.CLASS_DATA?.[r.class_id],sprite=c?`Assets/Classes/${c.sprite}`:'';return `<button class="own-char-card-v63 ${r.character_id===state.ownSelected?'active':''}" data-own-char="${esc(r.character_id)}">${sprite?`<img src="${esc(sprite)}" alt="">`:'<b>A</b>'}<span><small>Slot ${Number(r.slot)} · ${esc(CLASS_LABELS[r.class_id]||r.class_id)}</small><strong>${esc(r.name)}</strong><em>Nv. ${Number(r.level)||1}</em></span></button>`;}
function renderOwnCharacters(){const content=$('#adminContent'),r=state.ownRows.find(x=>x.character_id===state.ownSelected),save=r?.save_data&&typeof r.save_data==='object'?r.save_data:{},p=save.player||{},c=r&&global.AstraeonWorld?.CLASS_DATA?.[r.class_id],sprite=c?`Assets/Classes/${c.sprite}`:'';content.innerHTML=`<div class="admin-page active own-characters-v63"><div class="admin-page-head"><div><h3>Meus Personagens</h3><p>Seus quatro vínculos astrais, com ficha e save editáveis diretamente no Supabase.</p></div><span class="admin-badge">${state.ownRows.length}/4 personagens</span></div><div class="own-char-layout-v63"><aside class="own-char-list-v63">${state.ownRows.map(ownCard).join('')||'<div class="admin-card"><p>Nenhum personagem criado nesta conta.</p></div>'}</aside><main class="own-char-detail-v63">${r?`<div class="own-char-hero-v63">${sprite?`<img src="${esc(sprite)}" alt="">`:''}<div><span>${esc(CLASS_LABELS[r.class_id]||r.class_id)} · SLOT ${Number(r.slot)}</span><h3>${esc(r.name)}</h3><p>Nível ${Number(r.level)||1} · atualizado ${r.save_updated_at?esc(new Date(r.save_updated_at).toLocaleString('pt-BR')):'sem save'}</p></div></div><div class="own-char-fields-v63"><label>Nome<input id="ownNameV63" maxlength="18" value="${esc(r.name)}"></label><label>Classe<select id="ownClassV63">${Object.keys(CLASS_LABELS).map(k=>`<option value="${k}" ${k===r.class_id?'selected':''}>${CLASS_LABELS[k]}</option>`).join('')}</select></label><label>Nível<input id="ownLevelV63" type="number" min="1" max="999" value="${Number(r.level)||1}"></label><label>Ouro<input id="ownGoldV63" type="number" min="0" value="${Number(save.gold)||0}"></label><label>Vida<input id="ownHpV63" type="number" min="0" value="${Number(p.hp)||0}"></label><label>Mana<input id="ownManaV63" type="number" min="0" value="${Number(p.mana)||0}"></label></div><div class="own-char-save-v63"><span id="ownStatusV63">Pronto para editar.</span><button id="ownSaveV63" class="admin-btn primary">Salvar personagem</button></div>`:'<div class="admin-card"><p>Selecione um personagem.</p></div>'}</main></div></div>`;$$('[data-own-char]').forEach(b=>b.onclick=()=>{state.ownSelected=b.dataset.ownChar;renderOwnCharacters();});$('#ownSaveV63')?.addEventListener('click',saveOwnCharacter);}
async function saveOwnCharacter(){const r=state.ownRows.find(x=>x.character_id===state.ownSelected);if(!r)return;const out=$('#ownStatusV63'),save=structuredClone(r.save_data||{});save.player=save.player&&typeof save.player==='object'?save.player:{};save.player.name=$('#ownNameV63').value.trim();save.player.classId=$('#ownClassV63').value;save.player.level=Math.max(1,Number($('#ownLevelV63').value)||1);save.player.hp=Math.max(0,Number($('#ownHpV63').value)||0);save.player.mana=Math.max(0,Number($('#ownManaV63').value)||0);save.gold=Math.max(0,Number($('#ownGoldV63').value)||0);out.textContent='Salvando…';const{error}=await client().rpc('admin_update_character_v6',{target_character:r.character_id,target_name:save.player.name,target_class_id:save.player.classId,target_level:save.player.level,target_save:save});if(error){out.textContent=`Erro: ${error.message}`;out.classList.add('error');return;}out.textContent='Salvo no Supabase';out.classList.remove('error');await ownCharactersPage();}
function patchNavigation(){const tabs=$('#adminPanel .admin-tabs');if(!tabs)return;tabs.querySelector('[data-admin-tab="mobs"]')?.remove();tabs.querySelector('[data-admin-tab="items"]')?.remove();const cls=tabs.querySelector('[data-admin-tab="classes"]');if(cls)cls.textContent='Balanceamento das Classes';const gp=tabs.querySelector('[data-admin-tab="gameplay"]');if(gp)gp.textContent='Regras do Jogo';const old=tabs.querySelector('[data-admin-tab="player"]');if(old&&!old.dataset.v63Own){const b=old.cloneNode(true);b.textContent='Meus Personagens';b.dataset.v63Own='1';b.addEventListener('click',()=>{activateTab(b);void ownCharactersPage();});old.replaceWith(b);}const all=$('[data-admin-character-v6]');if(all)all.textContent='Todos os Personagens';}
function dashboardTools(){const page=$('#adminContent .admin-page.active'),h=page?.querySelector('.admin-page-head h3');if(!h||!h.textContent.toLocaleLowerCase('pt-BR').includes('visão geral')||page.querySelector('.admin-tool-grid-v63'))return;const tools=[['Meus Personagens','Seus heróis e saves','✦'],['Regras do Jogo','Multiplicadores e recursos','⚙'],['Balanceamento das Classes','Atributos base','⚔'],['MobList & Drops','Criaturas, spawn e loot','◉'],['ItemList','Catálogo de itens','◇'],['Objetos & Áreas','Cena e colisões','▦'],['Mapas & Locais','Mundos conectados','⌖'],['Mensagens do Sistema','Anúncios do servidor','☷'],['Contas & Personagens','Usuários e acessos','♙']];const box=document.createElement('section');box.className='admin-tool-grid-v63';box.innerHTML=tools.map(([t,d,i])=>`<button data-tool-link="${esc(t)}"><i>${i}</i><span><b>${esc(t)}</b><small>${esc(d)}</small></span></button>`).join('');box.addEventListener('click',e=>{const name=e.target.closest('[data-tool-link]')?.dataset.toolLink,tab=name&&tabByText(name);tab?.click();});const anchor=page.querySelector('.studio-dashboard-addon')||page.querySelector('.admin-grid');anchor?.insertAdjacentElement('afterend',box);}
function improveItems(){const page=$('#adminContent .item-editor-page');if(!page||page.dataset.v63==='1')return;page.dataset.v63='1';page.querySelector('.admin-page-head p').textContent='Catálogo visual do servidor. Selecione um item para editar atributos, classes, imagem e disponibilidade.';page.classList.add('item-editor-v63');const detail=$('#itemEditorDetail');if(detail)new MutationObserver(()=>detail.querySelector('.item-detail-editor')?.classList.add('item-detail-v63')).observe(detail,{childList:true});}
function improveSceneOverview(){const page=$('#adminContent .scene-overview-page');if(!page||page.dataset.v63==='1')return;page.dataset.v63='1';page.querySelector('.admin-page-head p').textContent='Selecione para editar no Canvas ou remova aqui. Todas as alterações são sincronizadas em tempo real.';for(const btn of $$('[data-fo],[data-fz]')){const wrap=document.createElement('div');wrap.className='scene-row-v63';btn.parentNode.insertBefore(wrap,btn);wrap.appendChild(btn);const del=document.createElement('button');del.className='scene-row-delete-v63';del.textContent='Remover';del.type='button';del.onclick=e=>{e.preventDefault();e.stopPropagation();const d=ed()?.design;if(!d)return;if(btn.dataset.fo)d.sceneObjects=(d.sceneObjects||[]).filter(x=>x.id!==btn.dataset.fo);else d.zones=(d.zones||[]).filter(x=>x.id!==btn.dataset.fz);ed().markDirty?.();ed().addHistory?.('Objeto/área removido');ed().refreshAll?.();ed().draw?.();setTimeout(()=>tabByText('Objetos & Áreas')?.click(),60);};wrap.appendChild(del);} }
async function injectSystemLineControls(){const cards=$$('.admin-system-message[data-system-message]').filter(c=>!c.querySelector('[data-line-width-v63]'));if(!cards.length)return;const ids=cards.map(c=>Number(c.dataset.systemMessage)).filter(Number.isFinite),{data,error}=await client().from('system_messages').select('id,line_width').in('id',ids);if(error)return;const map=new Map((data||[]).map(r=>[String(r.id),Number(r.line_width)||220]));for(const card of cards){const id=card.dataset.systemMessage,value=map.get(id)||220,host=card.querySelector('.admin-system-message-main');if(!host)continue;const row=document.createElement('div');row.className='system-line-control-v63';row.innerHTML=`<label>Linhas laterais <input data-line-width-v63="${esc(id)}" type="range" min="40" max="420" step="10" value="${value}"><output>${value}px</output></label><small>Comprimento visual das linhas que acompanham o anúncio central.</small>`;host.appendChild(row);const input=row.querySelector('input'),out=row.querySelector('output');input.addEventListener('input',()=>{out.textContent=`${input.value}px`;clearTimeout(state.lineTimers.get(id));state.lineTimers.set(id,setTimeout(async()=>{const{error}=await client().from('system_messages').update({line_width:Number(input.value)}).eq('id',Number(id));out.textContent=error?'Erro':`${input.value}px · salvo`;},450));});}}
async function injectMobSpawnRates(){if(!$('#mobDetailName')||$('#mobSpawnRatesV63'))return;const type=$('.mob-detail-portrait small')?.textContent?.trim();if(!type)return;const [{data:maps,error:me},{data:mob,error:ce}]=await Promise.all([client().from('world_maps').select('map_key,name,is_default').eq('enabled',true).order('map_order'),client().from('mob_configs').select('spawn_rates').eq('mob_type',type).maybeSingle()]);if(me||ce)return;const rates=mob?.spawn_rates&&typeof mob.spawn_rates==='object'?mob.spawn_rates:{};const section=document.createElement('section');section.id='mobSpawnRatesV63';section.className='mob-spawn-v63';section.innerHTML=`<div class="place-section-head"><div><h4>Rate de Spawn por mapa</h4><small>100% = quantidade padrão do mapa</small></div></div><div class="mob-spawn-grid-v63">${(maps||[]).map(m=>{const v=Number.isFinite(Number(rates[m.map_key]))?Number(rates[m.map_key]):100;return `<label data-map-rate="${esc(m.map_key)}"><span><b>${esc(m.name)}</b><small>${esc(m.map_key)}${m.is_default?' · default':''}</small></span><input type="range" min="0" max="300" step="5" value="${v}"><output>${v}%</output></label>`;}).join('')}</div>`;$('#mobDetailDrops')?.parentElement?.insertBefore(section,$('#mobDetailDrops')?.previousElementSibling||$('#mobDetailDrops'));section.querySelectorAll('[data-map-rate]').forEach(row=>{const input=row.querySelector('input'),out=row.querySelector('output');input.addEventListener('input',()=>{out.textContent=`${input.value}%`;clearTimeout(state.spawnTimer);state.spawnTimer=setTimeout(async()=>{rates[row.dataset.mapRate]=Number(input.value);const{error}=await client().from('mob_configs').update({spawn_rates:rates,updated_by:userId()}).eq('mob_type',type);out.textContent=error?'Erro':`${input.value}% · salvo`;},420);});});}
function zoneHit(x,y,z){if(z.shape==='circle')return Math.hypot(x-Number(z.cx),y-Number(z.cy))<=Number(z.radius||0);if(z.shape==='polygon'){const pts=z.points||[];let inside=false;for(let i=0,j=pts.length-1;i<pts.length;j=i++){const a=pts[i],b=pts[j];if(((a.y>y)!==(b.y>y))&&(x<(b.x-a.x)*(y-a.y)/(b.y-a.y||1e-9)+a.x))inside=!inside;}return inside;}return x>=Math.min(z.x1,z.x2)&&x<=Math.max(z.x1,z.x2)&&y>=Math.min(z.y1,z.y2)&&y<=Math.max(z.y1,z.y2);}
function worldPoint(ev){const e=ed(),r=e.canvas.getBoundingClientRect(),sx=ev.clientX-r.left,sy=ev.clientY-r.top;return{x:(sx-e.view.x)/e.view.zoom,y:(sy-e.view.y)/e.view.zoom};}
function beginCanvasDrag(ev){const e=ed();if(!e||ev.target!==e.canvas||e.tool!=='select'||ev.button!==0)return;const p=worldPoint(ev),d=e.design,object=[...(d.sceneObjects||[])].reverse().find(o=>Math.abs(p.x-o.x)<=Math.max(8,Number(o.width)/2)&&Math.abs(p.y-o.y)<=Math.max(8,Number(o.height)/2)),zone=object?null:[...(d.zones||[])].reverse().find(z=>zoneHit(p.x,p.y,z));if(!object&&!zone)return;state.drag={object,zone,last:p,moved:false};if(prod()?.state){prod().state.selectedObject=object||null;prod().state.selectedZone=zone||null;}e.canvas.setPointerCapture?.(ev.pointerId);}
function shiftZone(z,dx,dy){if(z.shape==='circle'){z.cx+=dx;z.cy+=dy;}else if(z.shape==='polygon'){for(const p of z.points||[]){p.x+=dx;p.y+=dy;}}else{z.x1+=dx;z.x2+=dx;z.y1+=dy;z.y2+=dy;}}
function moveCanvasDrag(ev){const d=state.drag,e=ed();if(!d||ev.target!==e.canvas)return;const p=worldPoint(ev),dx=p.x-d.last.x,dy=p.y-d.last.y;if(Math.hypot(dx,dy)<.15)return;d.moved=true;d.last=p;if(d.object){d.object.x=Math.round((d.object.x+dx)*10)/10;d.object.y=Math.round((d.object.y+dy)*10)/10;}else shiftZone(d.zone,dx,dy);e.draw?.();ev.preventDefault();}
function endCanvasDrag(){const d=state.drag,e=ed();if(!d)return;state.drag=null;if(d.moved){e.markDirty?.();e.addHistory?.(d.object?'Objeto movido':'Área movida');e.refreshAll?.();e.draw?.();}}
function installCanvasDrag(){if(document.documentElement.dataset.canvasDragV63)return;document.documentElement.dataset.canvasDragV63='1';global.addEventListener('pointerdown',beginCanvasDrag,true);global.addEventListener('pointermove',moveCanvasDrag,true);global.addEventListener('pointerup',endCanvasDrag,true);global.addEventListener('pointercancel',endCanvasDrag,true);}
function contentEnhance(){visibleTitles();patchNavigation();dashboardTools();explainGameplay();improveItems();improveSceneOverview();void injectSystemLineControls();void injectMobSpawnRates();const all=$('[data-admin-character-v6]');if(all)all.textContent='Todos os Personagens';}
function install(){if(state.installed||!$('#adminPanel')||Number(global.AstraeonAdminAuth?.access)!==3){setTimeout(install,80);return;}state.installed=true;ensureStyle();visibleTitles();patchNavigation();installCanvasDrag();const content=$('#adminContent');if(content){state.contentObserver=new MutationObserver(()=>queueMicrotask(contentEnhance));state.contentObserver.observe(content,{childList:true,subtree:true});}new MutationObserver(()=>{visibleTitles();patchNavigation();}).observe($('#adminPanel'),{childList:true,subtree:true});contentEnhance();document.body.classList.add('admin-v63-ready');}
if(document.readyState==='loading')global.addEventListener('DOMContentLoaded',install);else install();global.AstraeonAdminV63={state,install,ownCharactersPage};
})(window);
