(function(){
'use strict';
const W=window.AstraeonWorld;
if(!W)return;
const STORAGE='astraeon:v3c:admin';
const ITEM_CATALOG={warrior_blade:'Espada de Astrium',mage_staff:'Cetro de Lúmen',archer_bow:'Arco de Éter',assassin_blades:'Lâminas do Vazio',paladine_mace:'Maça Solar',rune_blade:'Lâmina Rúnica',lumen_hood:'Capuz de Lúmen',frost_crown:'Coroa de Nivora',wanderer_cloak:'Manto do Caminhante',astrium_armor:'Peitoral de Astrium',void_gloves:'Luvas do Vazio',hunter_boots:'Botas de Caçador',solar_boots:'Passos de Solvar',ether_ring:'Anel de Éter',umbria_ring:'Selo de Umbria',climate_talisman:'Talismã Climático',convergence_amulet:'Amuleto da Convergência',astral_core:'Núcleo de Astraeon',red_potion:'Poção Rubra',blue_potion:'Poção de Éter',astral_fragment:'Fragmento Astral',core_fragment:'Fragmento de Núcleo',bastion_helm:'Elmo do Bastião',bastion_plate:'Couraça do Bastião',bastion_gauntlets:'Manoplas Quebra-Runa',bastion_boots:'Grevas da Vanguarda',arcanist_circlet:'Círculo do Arcanista',arcanist_robe:'Veste da Maré Astral',arcanist_gloves:'Luvas de Conjuração',arcanist_steps:'Passos da Miragem',ranger_hood:'Capuz do Olho Verde',ranger_vest:'Colete da Fronteira',ranger_bracers:'Braçadeiras do Falcão',ranger_boots:'Botas do Passo Silencioso',void_mask:'Máscara do Vazio',void_armor:'Armadura das Sombras',void_grips:'Punhos da Execução',void_steps:'Passos Sem Eco',solar_crown:'Coroa do Juramento Solar',solar_plate:'Armadura da Aurora',solar_gauntlets:'Manoplas da Consagração',solar_greaves:'Grevas do Peregrino Solar'};
const CLASS_LABEL={Warrior:'Guerreiro',Mage:'Mago',Archer:'Arqueiro',Assassin:'Assassino',Paladine:'Paladino'};
const num=(v,f=0)=>Number.isFinite(Number(v))?Number(v):f;
function defaults(){return{version:'3.0-C',enabled:true,gameplay:{godMode:false,damageMultiplier:1,damageTakenMultiplier:1,xpMultiplier:1,goldMultiplier:1,lootChance:.18,backpackCapacity:30,staminaMax:100,staminaDrain:24,staminaRegen:19,staminaDelay:.65,sprintMultiplier:1.55},classes:{},mobs:{},items:{},biomes:{}}}
function deepMerge(a,b){if(!b||typeof b!=='object')return a;for(const[k,v]of Object.entries(b)){if(v&&typeof v==='object'&&!Array.isArray(v)&&a[k]&&typeof a[k]==='object'&&!Array.isArray(a[k]))deepMerge(a[k],v);else a[k]=v;}return a;}
function load(){try{return deepMerge(defaults(),JSON.parse(localStorage.getItem(STORAGE)||'{}'));}catch(_){return defaults();}}
function save(cfg){localStorage.setItem(STORAGE,JSON.stringify(cfg));}
function esc(v){return String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));}
function field(id,label,value,type='number',step='1'){return`<div class="admin-field"><label for="${id}">${label}</label><input id="${id}" type="${type}" ${type==='number'?`step="${step}"`:''} value="${esc(value)}"></div>`}
function selectField(id,label,options,value){return`<div class="admin-field"><label for="${id}">${label}</label><select id="${id}">${options.map(([v,l])=>`<option value="${esc(v)}" ${v===value?'selected':''}>${esc(l)}</option>`).join('')}</select></div>`}
function install(){
 const editor=window.astraeonEditor;if(!editor||document.querySelector('#adminPanel'))return;let cfg=load();
 const btn=document.createElement('button');btn.id='adminOpenBtn';btn.className='btn admin-open-btn';btn.textContent='Admin 3.0-C';(document.querySelector('.top-actions')||document.querySelector('.topbar'))?.prepend(btn);
 const root=document.createElement('div');root.id='adminPanel';root.className='hidden';root.innerHTML=`<div class="admin-shell"><header class="admin-head"><div class="admin-head-mark">A</div><div class="admin-head-copy"><b>ASTRAEON · ADMIN CONSOLE</b><small>Personagem, balanceamento, itens, mobs, biomas, saves e configurações avançadas.</small></div><div class="admin-head-actions"><button id="adminExport" class="admin-btn">Exportar</button><button id="adminClose" class="admin-btn danger">Fechar</button></div></header><div class="admin-body"><nav class="admin-tabs"><button class="admin-tab active" data-admin-tab="dashboard">Visão geral</button><button class="admin-tab" data-admin-tab="player">Personagem</button><button class="admin-tab" data-admin-tab="gameplay">Gameplay</button><button class="admin-tab" data-admin-tab="classes">Classes</button><button class="admin-tab" data-admin-tab="mobs">Mobs</button><button class="admin-tab" data-admin-tab="items">Itens</button><button class="admin-tab" data-admin-tab="world">Biomas</button><button class="admin-tab" data-admin-tab="advanced">Avançado</button></nav><main id="adminContent" class="admin-content"></main></div></div>`;document.body.appendChild(root);
 const content=root.querySelector('#adminContent');let current='dashboard';const q=s=>content.querySelector(s);const notify=t=>editor.notify?.(t);const readSave=()=>{try{return JSON.parse(localStorage.getItem(W.STORAGE_SAVE)||'null')}catch(_){return null}};
 const header=(t,d,e='')=>`<div class="admin-page active"><div class="admin-page-head"><div><h3>${t}</h3><p>${d}</p></div>${e}</div>`;
 function dashboard(){const s=readSave(),world=W.loadWorldDesign();return header('Visão geral','Estado atual e atalhos administrativos.')+`<div class="admin-grid two"><section class="admin-card"><h4>Jogo salvo</h4><div class="admin-statline"><span>Personagem</span><b>${esc(s?.player?.name||'Nenhum save')}</b></div><div class="admin-statline"><span>Classe / nível</span><b>${esc(s?.player?.classId||'—')} · ${s?.player?.level||'—'}</b></div><div class="admin-statline"><span>Itens</span><b>${s?.inventory?.length||0}</b></div><div class="admin-statline"><span>Ouro</span><b>${s?.gold||0}</b></div></section><section class="admin-card"><h4>Mundo</h4><div class="admin-statline"><span>Seed</span><b>${esc(world?.seed||editor.design?.seed||'—')}</b></div><div class="admin-statline"><span>Overrides</span><b>${Object.keys(world?.overrides||editor.design?.overrides||{}).length}</b></div><div class="admin-statline"><span>Spawns manuais</span><b>${(world?.spawns||editor.design?.spawns||[]).length}</b></div><div class="admin-statline"><span>Admin</span><b><span class="admin-badge">${cfg.enabled?'ATIVO':'DESATIVADO'}</span></b></div></section></div><div class="admin-actions"><button id="adminToggleEnabled" class="admin-btn primary">${cfg.enabled?'Desativar overrides':'Ativar overrides'}</button><button id="adminPlay" class="admin-btn success">▶ Salvar e testar</button><button id="adminResetConfig" class="admin-btn danger">Resetar Admin</button></div><p class="admin-note">O painel Avançado permite editar diretamente o JSON do Admin, do save e do mundo, funcionando como acesso irrestrito aos dados locais.</p></div>`}
 function player(){const s=readSave();if(!s?.player)return header('Personagem','Edite diretamente o save local.')+`<div class="admin-card admin-warning"><h4>Nenhum save encontrado</h4><p class="admin-note">Crie uma jornada no jogo primeiro.</p></div></div>`;const p=s.player;return header('Personagem','Altera imediatamente os dados persistidos.')+`<div class="admin-grid">${field('apName','Nome',p.name||'Viajante','text')}${selectField('apClass','Classe',Object.entries(CLASS_LABEL),p.classId||'Warrior')}${field('apLevel','Nível',p.level||1)}${field('apGold','Ouro',s.gold||0)}${field('apXp','XP atual',p.xp||0)}${field('apXpNext','XP próximo nível',p.xpNext||100)}${field('apHp','Vida atual',p.hp||p.maxHp)}${field('apMaxHp','Vida máxima',p.maxHp||100)}${field('apMana','Mana atual',p.mana||p.maxMana)}${field('apMaxMana','Mana máxima',p.maxMana||100)}${field('apStamina','Fôlego atual',s.stamina??100)}${field('apStaminaMax','Fôlego máximo',s.staminaMax||100)}${field('apPower','Poder',p.power||1)}${field('apDefense','Defesa',p.defense||0)}${field('apSpeed','Velocidade',p.speed||170)}${field('apRange','Alcance',p.range||60)}${field('apCrit','Crítico (0–1)',p.crit||0,'number','.001')}${field('apBag','Slots da mochila',s.backpackCapacity||30)}</div><div class="admin-actions"><button id="adminSavePlayer" class="admin-btn primary">Salvar personagem</button><button id="adminFullRestore" class="admin-btn success">Restaurar vida/mana/fôlego</button></div></div>`}
 function gameplay(){const g=cfg.gameplay;return header('Gameplay','Regras globais aplicadas pelo runtime 3.0-C.')+`<div class="admin-grid"><div class="admin-card admin-toggle"><span><b>God Mode</b><br><small>Ignora dano recebido.</small></span><input id="agGod" type="checkbox" ${g.godMode?'checked':''}></div>${field('agDmg','Dano causado ×',g.damageMultiplier,'number','.05')}${field('agTaken','Dano recebido ×',g.damageTakenMultiplier,'number','.05')}${field('agXp','XP ×',g.xpMultiplier,'number','.05')}${field('agGold','Ouro ×',g.goldMultiplier,'number','.05')}${field('agLoot','Chance de loot (0–1)',g.lootChance,'number','.01')}${field('agBag','Capacidade mochila',g.backpackCapacity)}${field('agStMax','Fôlego máximo',g.staminaMax)}${field('agStDrain','Consumo fôlego/s',g.staminaDrain,'number','.5')}${field('agStRegen','Regeneração/s',g.staminaRegen,'number','.5')}${field('agStDelay','Atraso regeneração',g.staminaDelay,'number','.05')}${field('agSprint','Multiplicador corrida',g.sprintMultiplier,'number','.05')}</div><div class="admin-actions"><button id="adminSaveGameplay" class="admin-btn primary">Aplicar gameplay</button></div></div>`}
 function classes(){const ids=Object.keys(W.CLASS_DATA),id=cfg._classSelected||ids[0],v={...W.CLASS_DATA[id],...(cfg.classes[id]||{})};return header('Classes','Edite atributos base de novos personagens.',selectField('adminClassSelect','Classe',ids.map(x=>[x,CLASS_LABEL[x]||x]),id))+`<div class="admin-grid">${field('acHp','Vida base',v.hp)}${field('acMana','Mana base',v.mana)}${field('acSpeed','Velocidade',v.speed)}${field('acPower','Poder',v.power)}${field('acDefense','Defesa',v.defense)}${field('acRange','Alcance',v.range)}${field('acCrit','Crítico (0–1)',v.crit,'number','.001')}</div><div class="admin-actions"><button id="adminSaveClass" class="admin-btn primary">Salvar classe</button><button id="adminResetClass" class="admin-btn">Remover override</button></div></div>`}
 function mobs(){const ids=Object.keys(W.MOB_DATA),id=cfg._mobSelected||ids[0],v={...W.MOB_DATA[id],...(cfg.mobs[id]||{})},gold=Array.isArray(v.gold)?v.gold:W.MOB_DATA[id].gold;return header('Mobs','Balanceie criaturas sem alterar os assets.',selectField('adminMobSelect','Criatura',ids.map(x=>[x,x]),id))+`<div class="admin-grid">${field('amHp','Vida',v.hp)}${field('amPower','Dano',v.power)}${field('amSpeed','Velocidade',v.speed)}${field('amXp','XP',v.xp)}${field('amGoldMin','Ouro mínimo',gold?.[0]||0)}${field('amGoldMax','Ouro máximo',gold?.[1]||0)}</div><div class="admin-actions"><button id="adminSaveMob" class="admin-btn primary">Salvar mob</button><button id="adminResetMob" class="admin-btn">Remover override</button></div></div>`}
 function items(){const ids=Object.keys(ITEM_CATALOG),id=cfg._itemSelected||ids[0],ov=cfg.items[id]||{};return header('Itens','Overrides sobre o catálogo 3.0-A.',selectField('adminItemSelect','Item',ids.map(x=>[x,ITEM_CATALOG[x]]),id))+`<div class="admin-grid">${selectField('aiRarity','Raridade',[['','Manter original'],['common','Comum'],['uncommon','Incomum'],['rare','Raro'],['epic','Épico'],['legendary','Lendário']],ov.rarity||'')}${field('aiPower','Poder bônus',ov.stats?.power??'','number','.001')}${field('aiDefense','Defesa bônus',ov.stats?.defense??'','number','.001')}${field('aiHp','Vida bônus',ov.stats?.maxHp??'','number','.001')}${field('aiMana','Mana bônus',ov.stats?.maxMana??'','number','.001')}${field('aiSpeed','Velocidade bônus',ov.stats?.speed??'','number','.001')}${field('aiRange','Alcance bônus',ov.stats?.range??'','number','.001')}${field('aiCrit','Crítico bônus',ov.stats?.crit??'','number','.001')}<div class="admin-field"><label for="aiClasses">Classes permitidas</label><input id="aiClasses" type="text" value="${esc((ov.allowedClasses||[]).join(','))}" placeholder="Warrior,Mage..."></div></div><div class="admin-actions"><button id="adminSaveItem" class="admin-btn primary">Salvar item</button><button id="adminResetItem" class="admin-btn">Remover override</button></div></div>`}
 function world(){const ids=W.BIOME_ORDER,id=cfg._biomeSelected||ids[0],v={...W.BIOMES[id],...(cfg.biomes[id]||{})};return header('Biomas','Mude identidade climática e cores.',selectField('adminBiomeSelect','Bioma',ids.map(x=>[x,W.BIOMES[x].name]),id))+`<div class="admin-grid">${field('abClimate','Clima',v.climate,'text')}${field('abAccent','Cor de destaque',v.accent,'color')}${field('abWater','Cor da água',v.water,'color')}${selectField('abWeather','Clima visual',[['leaves','Folhas'],['dust','Poeira'],['snow','Neve'],['rain','Chuva'],['embers','Brasas']],v.weather)}</div><div class="admin-actions"><button id="adminSaveBiome" class="admin-btn primary">Salvar bioma</button><button id="adminResetBiome" class="admin-btn">Remover override</button><button id="adminRebuildWorld" class="admin-btn success">Regerar preview</button></div></div>`}
 function advanced(){return header('Avançado','Acesso direto aos blocos JSON persistidos.')+`<div class="admin-grid two"><div class="admin-field"><label>Admin config JSON</label><textarea id="adminJsonConfig" spellcheck="false">${esc(JSON.stringify(cfg,null,2))}</textarea><button id="adminApplyConfigJson" class="admin-btn primary">Aplicar Admin JSON</button></div><div class="admin-field"><label>Save JSON</label><textarea id="adminJsonSave" spellcheck="false">${esc(JSON.stringify(readSave()||{},null,2))}</textarea><button id="adminApplySaveJson" class="admin-btn primary">Aplicar Save JSON</button></div><div class="admin-field"><label>Mundo JSON</label><textarea id="adminJsonWorld" spellcheck="false">${esc(JSON.stringify(W.loadWorldDesign()||editor.design||{},null,2))}</textarea><button id="adminApplyWorldJson" class="admin-btn primary">Aplicar Mundo JSON</button></div><section class="admin-card admin-warning"><h4>Operações destrutivas</h4><p class="admin-note">Afetam somente o localStorage deste navegador.</p><div class="admin-actions"><button id="adminDeleteSave" class="admin-btn danger">Apagar save</button><button id="adminDeleteWorld" class="admin-btn danger">Apagar mundo customizado</button><button id="adminDeleteAll" class="admin-btn danger">Apagar tudo Astraeon</button></div></section></div></div>`}
 const pages={dashboard,player,gameplay,classes,mobs,items,world,advanced};
 function render(){content.innerHTML=(pages[current]||dashboard)();bindPage()}
 function bindPage(){
  q('#adminToggleEnabled')?.addEventListener('click',()=>{cfg.enabled=!cfg.enabled;save(cfg);render();notify(`Admin overrides ${cfg.enabled?'ativados':'desativados'}.`)});q('#adminPlay')?.addEventListener('click',()=>{editor.save?.();location.href='index.html'});q('#adminResetConfig')?.addEventListener('click',()=>{if(confirm('Resetar todas as configurações Admin?')){cfg=defaults();save(cfg);render();notify('Admin resetado.')}});
  q('#adminSavePlayer')?.addEventListener('click',()=>{const s=readSave();if(!s?.player)return;const p=s.player;p.name=q('#apName').value.trim()||p.name;p.classId=q('#apClass').value;p.level=Math.max(1,num(q('#apLevel').value,1));s.gold=Math.max(0,num(q('#apGold').value,0));p.xp=Math.max(0,num(q('#apXp').value,0));p.xpNext=Math.max(1,num(q('#apXpNext').value,100));p.maxHp=Math.max(1,num(q('#apMaxHp').value,p.maxHp));p.hp=Math.max(0,Math.min(p.maxHp,num(q('#apHp').value,p.hp)));p.maxMana=Math.max(0,num(q('#apMaxMana').value,p.maxMana));p.mana=Math.max(0,Math.min(p.maxMana,num(q('#apMana').value,p.mana)));s.staminaMax=Math.max(1,num(q('#apStaminaMax').value,100));s.stamina=Math.max(0,Math.min(s.staminaMax,num(q('#apStamina').value,s.staminaMax)));p.power=Math.max(0,num(q('#apPower').value,p.power));p.defense=Math.max(0,num(q('#apDefense').value,p.defense));p.speed=Math.max(1,num(q('#apSpeed').value,p.speed));p.range=Math.max(1,num(q('#apRange').value,p.range));p.crit=Math.max(0,Math.min(1,num(q('#apCrit').value,p.crit)));s.backpackCapacity=Math.max(1,Math.floor(num(q('#apBag').value,30)));localStorage.setItem(W.STORAGE_SAVE,JSON.stringify(s));notify('Personagem salvo.');render()});q('#adminFullRestore')?.addEventListener('click',()=>{const s=readSave();if(!s?.player)return;s.player.hp=s.player.maxHp;s.player.mana=s.player.maxMana;s.stamina=s.staminaMax||100;localStorage.setItem(W.STORAGE_SAVE,JSON.stringify(s));notify('Recursos restaurados.');render()});
  q('#adminSaveGameplay')?.addEventListener('click',()=>{cfg.gameplay={...cfg.gameplay,godMode:q('#agGod').checked,damageMultiplier:Math.max(0,num(q('#agDmg').value,1)),damageTakenMultiplier:Math.max(0,num(q('#agTaken').value,1)),xpMultiplier:Math.max(0,num(q('#agXp').value,1)),goldMultiplier:Math.max(0,num(q('#agGold').value,1)),lootChance:Math.max(0,Math.min(1,num(q('#agLoot').value,.18))),backpackCapacity:Math.max(1,Math.floor(num(q('#agBag').value,30))),staminaMax:Math.max(1,num(q('#agStMax').value,100)),staminaDrain:Math.max(0,num(q('#agStDrain').value,24)),staminaRegen:Math.max(0,num(q('#agStRegen').value,19)),staminaDelay:Math.max(0,num(q('#agStDelay').value,.65)),sprintMultiplier:Math.max(.1,num(q('#agSprint').value,1.55))};save(cfg);notify('Gameplay Admin salvo.')});
  q('#adminClassSelect')?.addEventListener('change',e=>{cfg._classSelected=e.target.value;render()});q('#adminSaveClass')?.addEventListener('click',()=>{const id=cfg._classSelected||Object.keys(W.CLASS_DATA)[0];cfg.classes[id]={hp:num(q('#acHp').value),mana:num(q('#acMana').value),speed:num(q('#acSpeed').value),power:num(q('#acPower').value),defense:num(q('#acDefense').value),range:num(q('#acRange').value),crit:num(q('#acCrit').value)};save(cfg);notify(`${CLASS_LABEL[id]||id} atualizado.`)});q('#adminResetClass')?.addEventListener('click',()=>{delete cfg.classes[cfg._classSelected||Object.keys(W.CLASS_DATA)[0]];save(cfg);render();notify('Override da classe removido.')});
  q('#adminMobSelect')?.addEventListener('change',e=>{cfg._mobSelected=e.target.value;render()});q('#adminSaveMob')?.addEventListener('click',()=>{const id=cfg._mobSelected||Object.keys(W.MOB_DATA)[0];cfg.mobs[id]={hp:num(q('#amHp').value),power:num(q('#amPower').value),speed:num(q('#amSpeed').value),xp:num(q('#amXp').value),gold:[num(q('#amGoldMin').value),num(q('#amGoldMax').value)]};save(cfg);notify(`${id} atualizado.`)});q('#adminResetMob')?.addEventListener('click',()=>{delete cfg.mobs[cfg._mobSelected||Object.keys(W.MOB_DATA)[0]];save(cfg);render();notify('Override do mob removido.')});
  q('#adminItemSelect')?.addEventListener('change',e=>{cfg._itemSelected=e.target.value;render()});q('#adminSaveItem')?.addEventListener('click',()=>{const id=cfg._itemSelected||Object.keys(ITEM_CATALOG)[0],stats={};[['power','#aiPower'],['defense','#aiDefense'],['maxHp','#aiHp'],['maxMana','#aiMana'],['speed','#aiSpeed'],['range','#aiRange'],['crit','#aiCrit']].forEach(([k,s])=>{if(q(s).value!=='')stats[k]=num(q(s).value)});const rarity=q('#aiRarity').value,classes=q('#aiClasses').value.split(',').map(x=>x.trim()).filter(Boolean);cfg.items[id]={...(rarity?{rarity}:{}),...(Object.keys(stats).length?{stats}:{}),...(classes.length?{allowedClasses:classes}:{})};save(cfg);notify(`${ITEM_CATALOG[id]} atualizado.`)});q('#adminResetItem')?.addEventListener('click',()=>{delete cfg.items[cfg._itemSelected||Object.keys(ITEM_CATALOG)[0]];save(cfg);render();notify('Override do item removido.')});
  q('#adminBiomeSelect')?.addEventListener('change',e=>{cfg._biomeSelected=e.target.value;render()});q('#adminSaveBiome')?.addEventListener('click',()=>{const id=cfg._biomeSelected||W.BIOME_ORDER[0];cfg.biomes[id]={climate:q('#abClimate').value,accent:q('#abAccent').value,water:q('#abWater').value,weather:q('#abWeather').value};save(cfg);Object.assign(W.BIOMES[id],cfg.biomes[id]);editor.rebuild?.();editor.refreshAll?.();notify(`${W.BIOMES[id].name} atualizado.`)});q('#adminResetBiome')?.addEventListener('click',()=>{delete cfg.biomes[cfg._biomeSelected||W.BIOME_ORDER[0]];save(cfg);notify('Override do bioma removido. Recarregue o editor para restaurar a base.');render()});q('#adminRebuildWorld')?.addEventListener('click',()=>{for(const[id,ov]of Object.entries(cfg.biomes))if(W.BIOMES[id])Object.assign(W.BIOMES[id],ov);editor.rebuild?.();editor.refreshAll?.();notify('Preview regenerado.')});
  q('#adminApplyConfigJson')?.addEventListener('click',()=>{try{cfg=deepMerge(defaults(),JSON.parse(q('#adminJsonConfig').value));save(cfg);render();notify('Admin JSON aplicado.')}catch(_){notify('Admin JSON inválido.')}});q('#adminApplySaveJson')?.addEventListener('click',()=>{try{localStorage.setItem(W.STORAGE_SAVE,JSON.stringify(JSON.parse(q('#adminJsonSave').value)));notify('Save JSON aplicado.')}catch(_){notify('Save JSON inválido.')}});q('#adminApplyWorldJson')?.addEventListener('click',()=>{try{const o=JSON.parse(q('#adminJsonWorld').value);W.saveWorldDesign(o);editor.design=o;editor.design.overrides=editor.design.overrides||{};editor.design.spawns=Array.isArray(editor.design.spawns)?editor.design.spawns:[];editor.rebuild?.();editor.fitWorld?.();editor.refreshAll?.();notify('Mundo JSON aplicado.')}catch(_){notify('Mundo JSON inválido.')}});
  q('#adminDeleteSave')?.addEventListener('click',()=>{if(confirm('Apagar o save do personagem?')){localStorage.removeItem(W.STORAGE_SAVE);render();notify('Save apagado.')}});q('#adminDeleteWorld')?.addEventListener('click',()=>{if(confirm('Apagar o mundo customizado?')){localStorage.removeItem(W.STORAGE_WORLD);notify('Mundo customizado apagado.')}});q('#adminDeleteAll')?.addEventListener('click',()=>{if(confirm('Apagar save, mundo e configurações Astraeon deste navegador?')){Object.keys(localStorage).filter(k=>k.startsWith('astraeon:')).forEach(k=>localStorage.removeItem(k));cfg=defaults();render();notify('Dados Astraeon removidos.')}})
 }
 root.querySelectorAll('[data-admin-tab]').forEach(t=>t.addEventListener('click',()=>{current=t.dataset.adminTab;root.querySelectorAll('[data-admin-tab]').forEach(x=>x.classList.toggle('active',x===t));render()}));btn.addEventListener('click',()=>{cfg=load();root.classList.remove('hidden');render()});root.querySelector('#adminClose').addEventListener('click',()=>root.classList.add('hidden'));root.addEventListener('click',e=>{if(e.target===root)root.classList.add('hidden')});root.querySelector('#adminExport').addEventListener('click',async()=>{const text=JSON.stringify({admin:cfg,save:readSave(),world:W.loadWorldDesign()||editor.design},null,2);try{await navigator.clipboard.writeText(text);notify('Pacote Admin copiado.')}catch(_){notify('Não foi possível copiar automaticamente.')}});window.addEventListener('keydown',e=>{if(window.AstraeonInputGuardV1?.blocksPanelHotkeys(e))return;if(e.key==='F10'){e.preventDefault();root.classList.toggle('hidden');if(!root.classList.contains('hidden'))render()}});for(const[id,ov]of Object.entries(cfg.biomes||{}))if(W.BIOMES[id])Object.assign(W.BIOMES[id],ov);document.title='ASTRAEON 3.0-C — Editor Admin';const brand=document.querySelector('.brand small');if(brand)brand.textContent='Editor Astral 3.0-C · Admin';
}
if(document.readyState==='loading')window.addEventListener('DOMContentLoaded',()=>setTimeout(install,0));else setTimeout(install,0);
})();
