(function(global){
'use strict';
const $=s=>document.querySelector(s),$$=s=>Array.from(document.querySelectorAll(s));
const COSTS=[10,20,18,24,42];
const state={installed:false,macroHeld:false,macroIndex:0,lastMacroCast:0,sunAngle:0,skillEdit:new Map(),touchPointers:new Map()};
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
function game(){return global.astraeon;}
function installStyle(){if($('#gameplayV7Style'))return;const s=document.createElement('style');s.id='gameplayV7Style';s.textContent=`
#mobileControls .skill-hold-arming{position:relative;overflow:visible}#mobileControls .skill-hold-arming:after{content:"";position:absolute;inset:-6px;border-radius:50%;pointer-events:none;background:conic-gradient(#8be8ff var(--hold-progress,0deg),rgba(139,232,255,.12) 0);-webkit-mask:radial-gradient(farthest-side,transparent calc(100% - 3px),#000 0);mask:radial-gradient(farthest-side,transparent calc(100% - 3px),#000 0);animation:skillHoldChargeV7 5s linear forwards;filter:drop-shadow(0 0 6px rgba(115,221,255,.6))}@keyframes skillHoldChargeV7{to{transform:rotate(360deg)}}#mobileControls .skill-editing{z-index:80!important;outline:1px solid rgba(111,232,255,.72)!important;box-shadow:0 0 0 5px rgba(76,208,255,.12),0 0 22px rgba(79,218,255,.32)!important;touch-action:none!important}#mobileControls .skill-editing:before{content:"MOVER · PINÇA";position:absolute;left:50%;bottom:calc(100% + 8px);transform:translateX(-50%);padding:4px 6px;border:1px solid rgba(107,218,255,.34);border-radius:5px;background:rgba(2,10,14,.92);color:#bff4ff;font:700 7px Inter,sans-serif;letter-spacing:.09em;white-space:nowrap}.skill-macro-pulse{animation:skillMacroPulseV7 .26s ease}@keyframes skillMacroPulseV7{50%{transform:scale(1.08);filter:brightness(1.4)}}.astra-sun-v7{position:fixed;z-index:4;width:34px;height:34px;border-radius:50%;pointer-events:none;background:radial-gradient(circle,#fff6c5 0 15%,#f3c758 36%,rgba(238,171,53,.32) 57%,transparent 74%);filter:drop-shadow(0 0 14px rgba(255,201,87,.62));opacity:.66;mix-blend-mode:screen;transition:opacity .6s}.game-running .astra-sun-v7{opacity:.72}body:not(.game-running) .astra-sun-v7{opacity:0}
`;document.head.appendChild(s);}
function installSun(){if($('#astraSunV7'))return;const el=document.createElement('div');el.id='astraSunV7';el.className='astra-sun-v7';document.body.appendChild(el);}
function sunVector(g){const clock=Number(g?.worldClock);state.sunAngle=Number.isFinite(clock)?clock*Math.PI*2:(performance.now()/90000)*Math.PI*2;const sx=Math.cos(state.sunAngle),sy=Math.sin(state.sunAngle);return{sx,sy,dx:-sx*13,dy:-sy*8};}
function drawBodyShadow(ctx,x,y,rx=14,ry=5,strength=.28){const g=game(),v=sunVector(g);ctx.save();ctx.translate(x+v.dx,y+12+v.dy);ctx.rotate(Math.atan2(v.dy,v.dx)*.18);ctx.fillStyle=`rgba(0,0,0,${strength})`;ctx.beginPath();ctx.ellipse(0,0,rx*(1.05+Math.abs(v.dx)/30),ry,0,0,Math.PI*2);ctx.fill();ctx.restore();}
function drawObjectShadows(g,ctx){const design=global.AstraeonProductionV6?.state?.design;const v=sunVector(g);ctx.save();ctx.fillStyle='rgba(0,0,0,.16)';for(const o of design?.sceneObjects||[]){if(o.visible===false||!o.collision)continue;const x=Number(o.x)||0,y=Number(o.y)||0,w=Math.max(4,Number(o.width)||36),h=Math.max(4,Number(o.height)||36);ctx.save();ctx.translate(x+v.dx*1.3,y+v.dy*1.3);ctx.rotate((Number(o.rotation)||0)*Math.PI/180);ctx.globalAlpha=.14+Math.min(.18,h/260);if(o.shape==='circle'||o.shape==='ellipse'){ctx.beginPath();ctx.ellipse(0,0,w/2,h/2,0,0,Math.PI*2);ctx.fill();}else ctx.fillRect(-w/2,-h/2,w,h);ctx.restore();}for(const s of g.world?.cityStructures||[]){if(s.type==='lamp'||s.type==='fountain')continue;const x=(s.x+s.w/2)*(global.AstraeonWorld?.TILE||36),y=(s.y+s.h/2)*(global.AstraeonWorld?.TILE||36),w=s.w*(global.AstraeonWorld?.TILE||36),h=s.h*(global.AstraeonWorld?.TILE||36);ctx.save();ctx.translate(v.dx*1.25,v.dy*1.25);ctx.globalAlpha=.14;ctx.fillRect(x-w/2,y-h/2,w,h);ctx.restore();}ctx.restore();}
function animateSun(){const g=game(),el=$('#astraSunV7');if(el&&g){const t=(Number(g.worldClock)||0)%1;el.style.left=`${clamp(8+t*84,6,92)}vw`;el.style.top=`${8+Math.sin(t*Math.PI)*12}vh`;}requestAnimationFrame(animateSun);}
function installShadows(g){if(g.shadowsV7Installed)return;g.shadowsV7Installed=true;if(typeof g.drawTerrain==='function'){const original=g.drawTerrain.bind(g);g.drawTerrain=function(ctx){const r=original(ctx);if(this.player)drawObjectShadows(this,ctx);return r;};}if(typeof g.drawMobs==='function'){const original=g.drawMobs.bind(g);g.drawMobs=function(ctx){for(const m of this.mobs||[])if(!m.dead)drawBodyShadow(ctx,m.x,m.y,13,4.5,.24);for(const n of this.npcsV4||[])drawBodyShadow(ctx,n.x,n.y,12,4,.2);return original(ctx);};}if(typeof g.drawPlayer==='function'){const original=g.drawPlayer.bind(g);g.drawPlayer=function(ctx){if(this.player)drawBodyShadow(ctx,this.player.x,this.player.y,14,4.8,.3);return original(ctx);};}}
function canCast(g,index){return !!g?.running&&!g.paused&&(Number(g.cooldowns?.[index])||0)<=.001&&(Number(g.player?.mana)||0)>=COSTS[index];}
function macroStep(force=false){const g=game();if(!g||!g.running||g.paused)return false;const now=performance.now();if(!force&&now-state.lastMacroCast<235)return false;for(let k=0;k<5;k++){const i=(state.macroIndex+k)%5;if(!canCast(g,i))continue;state.macroIndex=(i+1)%5;state.lastMacroCast=now;g.castSkill?.(i);const btn=$$(`#hotbar .skill`)[i];btn?.classList.remove('skill-macro-pulse');if(btn){void btn.offsetWidth;btn.classList.add('skill-macro-pulse');}return true;}return false;}
function installMouseMacro(g){if(g.skillMacroV7Installed)return;g.skillMacroV7Installed=true;const canvas=g.canvas||$('#world');canvas?.addEventListener('contextmenu',e=>e.preventDefault());canvas?.addEventListener('pointerdown',e=>{if(e.button!==2||!g.running||g.paused)return;e.preventDefault();state.macroHeld=true;macroStep(true);},{capture:true});global.addEventListener('pointerup',e=>{if(e.button===2)state.macroHeld=false;},true);global.addEventListener('blur',()=>state.macroHeld=false);const originalUpdate=g.update.bind(g);g.update=function(dt){const r=originalUpdate(dt);if(state.macroHeld)macroStep(false);return r;};}
function focusChat(){const input=$('#onlineChatInput'),chat=$('#onlineChat');if(!input||!chat)return false;chat.classList.remove('collapsed','collapsed-mobile','chat-pro-collapsed');chat.dataset.chatCollapsed='false';const toggle=$('#onlineChatToggle');if(toggle){toggle.textContent='▾';toggle.setAttribute('aria-expanded','true');}input.disabled=false;input.removeAttribute('disabled');setTimeout(()=>input.focus(),0);return true;}
function installEnterChat(g){if(g.enterChatV7Installed)return;g.enterChatV7Installed=true;global.addEventListener('keydown',e=>{if(e.key!=='Enter'||!g.running||g.paused)return;const tag=document.activeElement?.tagName;if(['TEXTAREA','SELECT'].includes(tag))return;if(document.activeElement?.id==='onlineChatInput')return;e.preventDefault();e.stopImmediatePropagation();if(!focusChat())setTimeout(focusChat,80);},true);}
function loadSkillLayout(btn){try{const all=JSON.parse(localStorage.getItem('astraeon:v7:mobile-skill-layout')||'{}'),v=all[btn.dataset.skill];if(!v)return;btn.style.translate=`${Number(v.x)||0}px ${Number(v.y)||0}px`;btn.style.scale=String(clamp(Number(v.scale)||1,.72,1.65));btn.dataset.skillX=String(Number(v.x)||0);btn.dataset.skillY=String(Number(v.y)||0);btn.dataset.skillScale=String(clamp(Number(v.scale)||1,.72,1.65));}catch(_){}}
function saveSkillLayout(btn){try{const all=JSON.parse(localStorage.getItem('astraeon:v7:mobile-skill-layout')||'{}');all[btn.dataset.skill]={x:Number(btn.dataset.skillX)||0,y:Number(btn.dataset.skillY)||0,scale:Number(btn.dataset.skillScale)||1};localStorage.setItem('astraeon:v7:mobile-skill-layout',JSON.stringify(all));}catch(_){}}
function installMobileSkillEditor(){const buttons=$$('#mobileControls [data-skill]');if(!buttons.length)return;buttons.forEach(btn=>{if(btn.dataset.skillEditV7==='1')return;btn.dataset.skillEditV7='1';loadSkillLayout(btn);let armTimer=null,armed=false,start=null,pinchStart=null;const pointers=new Map();function cancelArm(){clearTimeout(armTimer);armTimer=null;btn.classList.remove('skill-hold-arming');}function arm(e){if(e.pointerType==='mouse')return;pointers.set(e.pointerId,{x:e.clientX,y:e.clientY});start={x:e.clientX,y:e.clientY,bx:Number(btn.dataset.skillX)||0,by:Number(btn.dataset.skillY)||0};btn.classList.add('skill-hold-arming');armTimer=setTimeout(()=>{armed=true;btn.classList.remove('skill-hold-arming');btn.classList.add('skill-editing');navigator.vibrate?.(45);},5000);}function move(e){if(!pointers.has(e.pointerId))return;pointers.set(e.pointerId,{x:e.clientX,y:e.clientY});if(!armed)return;e.preventDefault();const vals=Array.from(pointers.values());if(vals.length>=2){const d=Math.hypot(vals[0].x-vals[1].x,vals[0].y-vals[1].y);if(!pinchStart)pinchStart={d,scale:Number(btn.dataset.skillScale)||1};const scale=clamp(pinchStart.scale*(d/Math.max(1,pinchStart.d)),.72,1.65);btn.dataset.skillScale=String(scale);btn.style.scale=String(scale);}else if(start){const x=start.bx+(e.clientX-start.x),y=start.by+(e.clientY-start.y);btn.dataset.skillX=String(Math.round(x));btn.dataset.skillY=String(Math.round(y));btn.style.translate=`${Math.round(x)}px ${Math.round(y)}px`;}}function end(e){pointers.delete(e.pointerId);if(!armed){cancelArm();return;}if(!pointers.size){armed=false;pinchStart=null;btn.classList.remove('skill-editing');saveSkillLayout(btn);navigator.vibrate?.(25);}else if(pointers.size<2)pinchStart=null;}btn.addEventListener('pointerdown',arm,{passive:true});btn.addEventListener('pointermove',move,{passive:false});btn.addEventListener('pointerup',end);btn.addEventListener('pointercancel',end);});}
function install(){const g=game();if(state.installed||!g)return;state.installed=true;installStyle();installSun();installShadows(g);installMouseMacro(g);installEnterChat(g);installMobileSkillEditor();requestAnimationFrame(animateSun);document.body.classList.add('astraeon-gameplay-v7');}
function wait(){if(game()&&$('#world'))install();else setTimeout(wait,70);}if(document.readyState==='loading')global.addEventListener('DOMContentLoaded',wait);else wait();global.AstraeonGameplayV7={state,install,macroStep,focusChat};
})(window);
