(function(global){
'use strict';
const W=global.AstraeonWorld;
const $=s=>document.querySelector(s),$$=s=>Array.from(document.querySelectorAll(s));
const BAG_CAPACITY=25;
const SKILL_COSTS=[10,20,18,24,42];
const state={installed:false,macroHeld:false,macroIndex:0,macroTimer:null,spawnRates:new Map(),spawnTimer:null,mobilePointers:new Map(),mobileEdit:null};
function game(){return global.astraeon;}function mp(){return global.AstraeonMultiplayerV4?.state||null;}function mapKey(g){return g?.currentMapKey||global.AstraeonWorldMapsV61?.state?.currentKey||'map1';}
function clamp(v,a,b){return Math.max(a,Math.min(b,v));}
function ensureStyle(){if(document.querySelector('link[data-gameplay-v63]'))return;const l=document.createElement('link');l.rel='stylesheet';l.href='src/gameplay-v63.css';l.dataset.gameplayV63='1';document.head.appendChild(l);}

function updatePointer(g,e){const r=g.canvas?.getBoundingClientRect();if(!r)return;g.mouse.x=e.clientX-r.left;g.mouse.y=e.clientY-r.top;g.mouse.worldX=(g.camera?.x||0)+g.mouse.x;g.mouse.worldY=(g.camera?.y||0)+g.mouse.y;}
function readySkill(g){for(let n=0;n<5;n++){const i=(state.macroIndex+n)%5,cooldown=Number(g.cooldowns?.[i])||0,cost=SKILL_COSTS[i]||0;if(cooldown<=.001&&Number(g.player?.mana||0)>=cost){state.macroIndex=(i+1)%5;return i;}}return-1;}
function macroTick(){clearTimeout(state.macroTimer);const g=game();if(!state.macroHeld||!g?.running||g.paused||!g.player)return;const i=readySkill(g);if(i>=0)g.castSkill?.(i);state.macroTimer=setTimeout(macroTick,i>=0?72:115);}
function installCombat(g){if(g.combatMouseV63)return;g.combatMouseV63=true;const canvas=g.canvas||$('#world');if(!canvas)return;
 canvas.addEventListener('pointerdown',e=>{if(!g.running||g.paused)return;updatePointer(g,e);if(e.button===2){e.preventDefault();e.stopImmediatePropagation();state.macroHeld=true;macroTick();}else if(e.button===0){/* left click remains the native damage/basic attack path */}},true);
 global.addEventListener('pointerup',e=>{if(e.button===2){state.macroHeld=false;clearTimeout(state.macroTimer);}},true);global.addEventListener('blur',()=>{state.macroHeld=false;clearTimeout(state.macroTimer);});canvas.addEventListener('contextmenu',e=>e.preventDefault(),true);
}

function installEnterChat(g){if(g.enterChatV63)return;g.enterChatV63=true;global.addEventListener('keydown',e=>{if(e.key!=='Enter'||!g.running||g.paused)return;const active=document.activeElement;if(active?.matches?.('input,textarea,select,[contenteditable="true"]'))return;const chat=$('#onlineChat'),input=$('#onlineChatInput');if(!chat||!input)return;e.preventDefault();e.stopImmediatePropagation();chat.classList.remove('collapsed','collapsed-mobile','chat-pro-collapsed');chat.dataset.chatCollapsed='false';const toggle=$('#onlineChatToggle');if(toggle){toggle.textContent='▾';toggle.setAttribute('aria-expanded','true');}if(input.disabled){$('#onlineAccountPanel')?.classList.remove('hidden');global.astraeon?.toast?.('Entre em sua conta para conversar no mundo.');return;}requestAnimationFrame(()=>input.focus());},true);}

function normalizeBag(g,{dropOverflow=false}={}){g.backpackCapacity=BAG_CAPACITY;if(!Array.isArray(g.inventory)||g.inventory.length<=BAG_CAPACITY)return;const overflow=g.inventory.splice(BAG_CAPACITY);if(dropOverflow&&g.player){overflow.forEach((item,i)=>g.pickups?.push({type:'loot',x:g.player.x+(i%5-2)*14,y:g.player.y+22+Math.floor(i/5)*12,value:item,life:90,persistent:true,blockedByCapacity:true}));g.toast?.(`${overflow.length} item(ns) excedentes ficaram no chão: mochila 25/25.`);}}
function installCapacity(g){if(g.capacityV63)return;g.capacityV63=true;normalizeBag(g);const start=g.startNew.bind(g),cont=g.continueGame.bind(g),save=g.save.bind(g);g.startNew=function(){const r=start();normalizeBag(this,{dropOverflow:true});this.renderInventory?.();return r;};g.continueGame=function(){const r=cont();normalizeBag(this,{dropOverflow:true});this.renderInventory?.();return r;};g.save=function(){normalizeBag(this);const r=save();try{const d=JSON.parse(localStorage.getItem(W.STORAGE_SAVE)||'{}');d.backpackCapacity=BAG_CAPACITY;localStorage.setItem(W.STORAGE_SAVE,JSON.stringify(d));}catch(_){}return r;};}

function sunVector(g){const clock=Number(g.worldClock);const phase=Number.isFinite(clock)?clock:(performance.now()/180000)%1;const angle=phase*Math.PI*2-Math.PI*.72;const elevation=.22+.78*Math.abs(Math.sin(angle));const length=7+(1-elevation)*22;return{x:Math.cos(angle)*length,y:Math.sin(angle)*length*.65+5,alpha:.11+(1-elevation)*.11,elevation};}
function entityShadow(ctx,g,x,y,rx=13,ry=5){const s=sunVector(g);ctx.save();ctx.translate(x+s.x,y+s.y);ctx.rotate(Math.atan2(s.y,s.x)*.16);ctx.scale(1+(1-s.elevation)*.75,1);ctx.globalAlpha=s.alpha;ctx.filter='blur(1.3px)';ctx.fillStyle='#000';ctx.beginPath();ctx.ellipse(0,0,rx,ry,0,0,Math.PI*2);ctx.fill();ctx.restore();}
function objectShadows(ctx,g){const d=global.AstraeonProductionV6?.state?.design||W?.loadWorldDesign?.();if(!d?.sceneObjects)return;for(const o of d.sceneObjects){if(!o?.collision||o.visible===false)continue;const w=Math.max(8,Number(o.width)||36),h=Math.max(8,Number(o.height)||36);entityShadow(ctx,g,Number(o.x)||0,(Number(o.y)||0)+h*.27,Math.max(8,w*.42),Math.max(3,h*.12));}}
function updateSunDom(g){const el=$('#astraeonSunV63');if(!el)return;const v=sunVector(g),phase=(Number(g.worldClock)||0)%1;el.style.setProperty('--sun-x',`${10+phase*80}vw`);el.style.setProperty('--sun-y',`${5+Math.sin(phase*Math.PI)*7}vh`);el.style.setProperty('--sun-alpha',String(.16+v.elevation*.15));}
function installSun(g){if(g.sunV63)return;g.sunV63=true;let sun=$('#astraeonSunV63');if(!sun){sun=document.createElement('div');sun.id='astraeonSunV63';sun.setAttribute('aria-hidden','true');document.querySelector('#gameRoot')?.appendChild(sun);}const drawPlayer=g.drawPlayer?.bind(g);if(drawPlayer)g.drawPlayer=function(ctx){if(this.player)entityShadow(ctx,this,this.player.x,this.player.y+12,14,4.8);return drawPlayer(ctx);};const drawMobs=g.drawMobs?.bind(g);if(drawMobs)g.drawMobs=function(ctx){for(const m of this.mobs||[])if(!m.dead)entityShadow(ctx,this,m.x,m.y+10,13,4.4);for(const n of this.npcsV4||[])entityShadow(ctx,this,n.x,n.y+11,12,4);return drawMobs(ctx);};const drawPickups=g.drawPickups?.bind(g);if(drawPickups)g.drawPickups=function(ctx){objectShadows(ctx,this);return drawPickups(ctx);};const update=g.update.bind(g);g.update=function(dt){const r=update(dt);updateSunDom(this);return r;};updateSunDom(g);}

async function refreshSpawnRates(){const s=mp();if(!s?.client||!s.session)return;try{const{data,error}=await s.client.from('mob_configs').select('mob_type,enabled,spawn_rates');if(error)return;state.spawnRates.clear();for(const r of data||[])state.spawnRates.set(r.mob_type,{enabled:r.enabled!==false,rates:r.spawn_rates&&typeof r.spawn_rates==='object'?r.spawn_rates:{}});}catch(_){} }
function rateFor(type,key){const c=state.spawnRates.get(type);if(!c)return 100;if(!c.enabled)return 0;const raw=Number(c.rates?.[key]);return Number.isFinite(raw)?clamp(raw,0,300):100;}
function addExtraMob(g,type,count){let attempts=0,added=0;while(added<count&&attempts++<count*90+120){const tx=2+Math.floor(Math.random()*Math.max(2,g.world.width-4)),ty=2+Math.floor(Math.random()*Math.max(2,g.world.height-4)),tile=g.world.get(tx,ty);if(!tile||tile.blocked||tile.kind==='water')continue;if(g.player&&W.dist(tx,ty,g.player.x/W.TILE,g.player.y/W.TILE)<6)continue;g.addMob?.(type,tx*W.TILE+W.TILE/2,ty*W.TILE+W.TILE/2,tile.biome,Math.random);added++;}}
function applySpawnRates(g){if(!g?.world||!Array.isArray(g.mobs))return;const key=mapKey(g),types=new Set([...g.mobs.map(m=>m.type),...state.spawnRates.keys()]);for(const type of types){const rate=rateFor(type,key),list=g.mobs.filter(m=>m.type===type&&!m.dead),base=list.length,target=Math.max(0,Math.round(base*rate/100));if(target<base){let remove=base-target;g.mobs=g.mobs.filter(m=>m.type!==type||m.dead||remove--<=0);}else if(target>base)addExtraMob(g,type,target-base);}}
function installSpawnRates(g){if(g.spawnRatesV63)return;g.spawnRatesV63=true;void refreshSpawnRates();state.spawnTimer=setInterval(refreshSpawnRates,30000);const spawn=g.spawnInitialMobs.bind(g);g.spawnInitialMobs=function(){const r=spawn();applySpawnRates(this);return r;};}

function mobileStore(){try{return JSON.parse(localStorage.getItem('astraeon:v63:mobile-skill-layout')||'{}');}catch(_){return{};}}
function saveMobileStore(v){try{localStorage.setItem('astraeon:v63:mobile-skill-layout',JSON.stringify(v));}catch(_){}}
function applyMobileLayout(){const store=mobileStore();$$('#mobileControls [data-skill]').forEach(btn=>{const k=btn.dataset.skill,v=store[k];if(!v)return;btn.style.setProperty('--skill-dx',`${Number(v.x)||0}px`);btn.style.setProperty('--skill-dy',`${Number(v.y)||0}px`);btn.style.setProperty('--skill-scale',String(clamp(Number(v.scale)||1,.72,1.65)));});}
function chargeVisual(btn,pct){btn.style.setProperty('--hold-charge',`${clamp(pct,0,1)*360}deg`);btn.classList.toggle('skill-hold-charging',pct>0&&pct<1);}
function enterMobileEdit(btn,pointer){state.mobileEdit={btn,skill:btn.dataset.skill,startX:pointer.x,startY:pointer.y,baseX:parseFloat(getComputedStyle(btn).getPropertyValue('--skill-dx'))||0,baseY:parseFloat(getComputedStyle(btn).getPropertyValue('--skill-dy'))||0,baseScale:parseFloat(getComputedStyle(btn).getPropertyValue('--skill-scale'))||1,pinchStart:0,pinchScale:1};btn.classList.add('skill-layout-editing');chargeVisual(btn,1);navigator.vibrate?.(35);}
function finishMobileEdit(){const ed=state.mobileEdit;if(!ed)return;const store=mobileStore();store[ed.skill]={x:parseFloat(getComputedStyle(ed.btn).getPropertyValue('--skill-dx'))||0,y:parseFloat(getComputedStyle(ed.btn).getPropertyValue('--skill-dy'))||0,scale:parseFloat(getComputedStyle(ed.btn).getPropertyValue('--skill-scale'))||1};saveMobileStore(store);ed.btn.classList.remove('skill-layout-editing','skill-hold-charging');chargeVisual(ed.btn,0);state.mobileEdit=null;}
function installMobileSkills(g){const root=$('#mobileControls');if(!root||root.dataset.skillEditV63)return;root.dataset.skillEditV63='1';applyMobileLayout();const holdTimers=new Map(),starts=new Map();root.addEventListener('pointerdown',e=>{const btn=e.target.closest?.('[data-skill]');if(!btn)return;e.preventDefault();e.stopImmediatePropagation();btn.setPointerCapture?.(e.pointerId);state.mobilePointers.set(e.pointerId,{x:e.clientX,y:e.clientY,btn});starts.set(e.pointerId,{x:e.clientX,y:e.clientY,t:performance.now(),btn});const timer=setInterval(()=>{const st=starts.get(e.pointerId);if(!st||state.mobileEdit)return;const pct=(performance.now()-st.t)/5000;chargeVisual(btn,pct);if(pct>=1){clearInterval(timer);holdTimers.delete(e.pointerId);enterMobileEdit(btn,{x:e.clientX,y:e.clientY});}},50);holdTimers.set(e.pointerId,timer);},true);
 root.addEventListener('pointermove',e=>{const p=state.mobilePointers.get(e.pointerId);if(!p)return;p.x=e.clientX;p.y=e.clientY;const ed=state.mobileEdit;if(!ed||ed.btn!==p.btn)return;e.preventDefault();const same=[...state.mobilePointers.values()].filter(x=>x.btn===ed.btn);if(same.length>=2){const d=Math.hypot(same[0].x-same[1].x,same[0].y-same[1].y);if(!ed.pinchStart){ed.pinchStart=d;ed.pinchScale=ed.baseScale;}const scale=clamp(ed.pinchScale*d/Math.max(1,ed.pinchStart),.72,1.65);ed.btn.style.setProperty('--skill-scale',String(scale));}else{const dx=e.clientX-ed.startX,dy=e.clientY-ed.startY;ed.btn.style.setProperty('--skill-dx',`${ed.baseX+dx}px`);ed.btn.style.setProperty('--skill-dy',`${ed.baseY+dy}px`);}},true);
 const finish=e=>{const p=state.mobilePointers.get(e.pointerId),st=starts.get(e.pointerId),timer=holdTimers.get(e.pointerId);if(timer){clearInterval(timer);holdTimers.delete(e.pointerId);}state.mobilePointers.delete(e.pointerId);starts.delete(e.pointerId);if(!p)return;e.preventDefault();e.stopImmediatePropagation();if(state.mobileEdit){if(![...state.mobilePointers.values()].some(x=>x.btn===state.mobileEdit.btn))finishMobileEdit();return;}chargeVisual(p.btn,0);if(st&&performance.now()-st.t<5000)g.castSkill?.(Number(p.btn.dataset.skill)||0);};root.addEventListener('pointerup',finish,true);root.addEventListener('pointercancel',finish,true);
}

function install(){const g=game();if(state.installed||!g||!W){setTimeout(install,80);return;}state.installed=true;ensureStyle();installCombat(g);installEnterChat(g);installCapacity(g);installSun(g);installSpawnRates(g);installMobileSkills(g);document.body.classList.add('astraeon-v63-gameplay');}
if(document.readyState==='loading')global.addEventListener('DOMContentLoaded',install);else install();global.AstraeonGameplayV63={state,install,refreshSpawnRates,applySpawnRates};
})(window);
