(function(global){
'use strict';
const $=s=>document.querySelector(s),$$=s=>Array.from(document.querySelectorAll(s));
const BAG=25;
const SLOT_ORDER=['head','amulet','weapon','chest','relic','hands','ring','boots'];
const STAT_LABELS={strength:'Força',magic:'Magia',dexterity:'Destreza',power:'Poder',defense:'Defesa',maxHp:'Vida máxima',maxMana:'Mana máxima',heal:'Cura',mana:'Mana restaurada',healPct:'Aumento de cura',manaPct:'Aumento de mana',speed:'Velocidade',range:'Alcance',crit:'Crítico'};
const CLASS_LABELS={Warrior:'Guerreiro',Mage:'Mago',Archer:'Arqueiro',Assassin:'Assassino',Paladine:'Paladino'};
const RARITY_LABELS={common:'Comum',uncommon:'Incomum',rare:'Raro',epic:'Épico',legendary:'Lendário'};
const RARITY_BASE={common:90,uncommon:180,rare:420,epic:900,legendary:2200};
const state={installed:false,holdTimer:null,holdTarget:null,tooltipPinned:false};
function game(){return global.astraeon;}function A(){return global.AstraeonItems;}function V3(){return global.AstraeonItemsV3;}
function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
function ensureStyle(){if(document.querySelector('link[data-inventory-v63]'))return;const l=document.createElement('link');l.rel='stylesheet';l.href='src/inventory-v63.css';l.dataset.inventoryV63='1';document.head.appendChild(l);}
function restructure(){const panel=$('#inventoryPanel');if(!panel||panel.dataset.inventoryV63==='1')return;panel.dataset.inventoryV63='1';panel.classList.add('inventory-v63');panel.querySelector('[data-inv-tab="itemlist"]')?.remove();panel.querySelector('[data-inv-panel="itemlist"]')?.remove();const tabs=$('#inventoryMobileTabs');if(tabs)tabs.classList.add('inventory-v63-tabs');const equipment=panel.querySelector('.equipment-column'),backpack=panel.querySelector('.backpack-column');if(equipment){equipment.querySelector('.inventory-column-title small').textContent='Armaduras · armas · acessórios';equipment.querySelector('.inventory-hint')?.remove();}if(backpack){backpack.querySelector('.inventory-column-title small').textContent='25 espaços · 5 × 5';$('#itemDetails')?.classList.add('inventory-details-hidden');}let tip=$('#itemTooltipV63');if(!tip){tip=document.createElement('aside');tip.id='itemTooltipV63';tip.className='item-tooltip-v63';tip.setAttribute('role','tooltip');tip.innerHTML='<div class="item-tooltip-inner"></div>';panel.querySelector('.inventory-overlay-card')?.appendChild(tip);} }
function purchaseValue(item){if(Number(item?.buyPrice)>0)return Math.max(1,Math.floor(Number(item.buyPrice)));const stats=item?.stats||{},score=Object.entries(stats).reduce((n,[k,v])=>{const x=Math.abs(Number(v)||0);return n+(k==='crit'?x*1300:k.endsWith('Pct')?x*4:x*5);},0)+(Number(item?.power)||0)*7+(Number(item?.heal)||0)*2+(Number(item?.mana)||0)*2;return Math.max(10,Math.round((RARITY_BASE[item?.rarity]||90)+(Number(item?.level)||1)*8+score));}
function saleValue(item){return Math.max(1,Math.floor(purchaseValue(item)*.1));}
function allStats(item){const merged={...(item?.stats||{})};for(const k of ['power','defense','heal','mana'])if(Number(item?.[k])&&merged[k]==null)merged[k]=Number(item[k]);return Object.entries(merged).filter(([,v])=>Number(v)!==0&&v!=null).map(([k,v])=>({key:k,label:STAT_LABELS[k]||k,value:Number(v)}));}
function statText(s){const pct=s.key==='crit'?`${(s.value*100).toFixed(s.value<.1?1:0)}%`:s.key.endsWith('Pct')?`${s.value}%`:String(s.value);return `${s.label} ${s.value>0?'+':''}${pct}`;}
function tooltipHtml(item){const art=V3()?.artFor?.(item)||item?.imageUrl||'',classes=item?.allowedClasses?.length?item.allowedClasses.map(c=>CLASS_LABELS[c]||c).join(', '):'Todas as classes',stats=allStats(item);return `<div class="tooltip-v63-head" data-rarity="${esc(item?.rarity||'common')}">${art?`<img src="${esc(art)}" alt="">`:`<b>${esc(item?.icon||'◇')}</b>`}<div><span>${esc(RARITY_LABELS[item?.rarity]||'Comum')} · ${esc(item?.slot||item?.type||'Item')}</span><h3>${esc(item?.name||'Item')}</h3></div></div><p>${esc(item?.description||'Item encontrado em Astraeon.')}</p><div class="tooltip-v63-stats">${stats.length?stats.map(s=>`<span>${esc(statText(s))}</span>`).join(''):'<span>Sem atributos adicionais</span>'}</div><div class="tooltip-v63-meta"><div><small>Classes</small><b>${esc(classes)}</b></div><div><small>Valor de venda</small><b>${saleValue(item)} ouro</b></div>${item?.qty?`<div><small>Quantidade</small><b>${Number(item.qty)||1}</b></div>`:''}</div>`;}
function itemFromNode(g,node){if(!node)return null;if(node.matches('#inventoryGrid [data-index]'))return g.inventory?.[Number(node.dataset.index)]||null;if(node.matches('#equipmentGrid [data-slot]'))return g.equipment?.[node.dataset.slot]||null;return null;}
function positionTooltip(tip,node){const panel=$('#inventoryPanel .inventory-overlay-card'),r=node.getBoundingClientRect(),pr=panel?.getBoundingClientRect();if(!pr)return;const width=300;let left=r.right-pr.left+10,top=r.top-pr.top;if(left+width>pr.width-12)left=Math.max(12,r.left-pr.left-width-10);top=clamp(top,12,Math.max(12,pr.height-330));tip.style.left=`${left}px`;tip.style.top=`${top}px`;}
function clamp(v,a,b){return Math.max(a,Math.min(b,v));}
function showTooltip(g,node,{pinned=false}={}){const item=itemFromNode(g,node),tip=$('#itemTooltipV63');if(!item||!tip)return;tip.querySelector('.item-tooltip-inner').innerHTML=tooltipHtml(item);positionTooltip(tip,node);tip.classList.add('show');state.tooltipPinned=!!pinned;node.classList.add('tooltip-source');}
function hideTooltip(force=false){if(state.tooltipPinned&&!force)return;$('#itemTooltipV63')?.classList.remove('show');$$('#inventoryPanel .tooltip-source').forEach(n=>n.classList.remove('tooltip-source'));if(force)state.tooltipPinned=false;}
function cancelHold(){clearTimeout(state.holdTimer);state.holdTimer=null;if(state.holdTarget){state.holdTarget.classList.remove('item-hold-loading');state.holdTarget.style.removeProperty('--item-hold');state.holdTarget=null;}}
function installTooltip(g){const panel=$('#inventoryPanel');if(!panel||panel.dataset.tooltipV63==='1')return;panel.dataset.tooltipV63='1';panel.addEventListener('pointerover',e=>{const n=e.target.closest?.('#inventoryGrid [data-index],#equipmentGrid [data-slot]');if(!n||e.pointerType==='touch'||state.tooltipPinned)return;showTooltip(g,n);});panel.addEventListener('pointerout',e=>{const n=e.target.closest?.('#inventoryGrid [data-index],#equipmentGrid [data-slot]');if(!n||n.contains(e.relatedTarget))return;hideTooltip();});panel.addEventListener('pointerdown',e=>{const n=e.target.closest?.('#inventoryGrid [data-index],#equipmentGrid [data-slot]');if(!n||e.button!==0)return;hideTooltip(true);cancelHold();state.holdTarget=n;n.classList.add('item-hold-loading');const started=performance.now();const tick=()=>{if(state.holdTarget!==n)return;const p=clamp((performance.now()-started)/680,0,1);n.style.setProperty('--item-hold',`${p*360}deg`);if(p<1)requestAnimationFrame(tick);};requestAnimationFrame(tick);state.holdTimer=setTimeout(()=>{n.classList.remove('item-hold-loading');n.style.removeProperty('--item-hold');state.holdTarget=null;showTooltip(g,n,{pinned:true});},680);});panel.addEventListener('pointerup',cancelHold);panel.addEventListener('pointercancel',cancelHold);panel.addEventListener('pointermove',e=>{if(!state.holdTarget)return;const r=state.holdTarget.getBoundingClientRect();if(e.clientX<r.left-12||e.clientX>r.right+12||e.clientY<r.top-12||e.clientY>r.bottom+12)cancelHold();});panel.addEventListener('click',e=>{if(state.tooltipPinned&&!e.target.closest('#itemTooltipV63')&&!e.target.closest('[data-index],[data-slot]'))hideTooltip(true);});}
function artify(g){$$('#inventoryGrid .item-card-slot[data-index]').forEach(el=>{const item=g.inventory?.[Number(el.dataset.index)],strong=el.querySelector('strong');if(!item||!strong)return;const art=V3()?.artFor?.(item)||item.imageUrl||'';if(art)strong.innerHTML=`<img src="${esc(art)}" alt="">`;});$$('#equipmentGrid .equipment-slot[data-slot]').forEach(el=>{const item=g.equipment?.[el.dataset.slot],strong=el.querySelector('strong');if(!item||!strong)return;const art=V3()?.artFor?.(item)||item.imageUrl||'';if(art)strong.innerHTML=`<img src="${esc(art)}" alt="">`;});}
function patchGrid(g){const grid=$('#inventoryGrid');if(!grid)return;const children=Array.from(grid.children);children.slice(BAG).forEach(n=>n.remove());while(grid.children.length<BAG){const empty=document.createElement('button');empty.className='inventory-slot empty';empty.disabled=true;grid.appendChild(empty);}grid.dataset.slots='25';const meta=$('#inventoryMeta');if(meta){const count=Math.min(BAG,g.inventory?.length||0);meta.innerHTML=`<span>${CLASS_LABELS[g.player?.classId]||g.player?.classId||'Viajante'}</span><b>${count}/${BAG} espaços</b><b>${Number(g.gold)||0} ouro</b>`;}const equipment=$('#equipmentGrid');if(equipment){SLOT_ORDER.forEach((slot,i)=>{const el=equipment.querySelector(`[data-slot="${slot}"]`);if(el)el.style.setProperty('--slot-order',String(i+1));});}artify(g);}
function installRender(g){if(g.inventoryV63)return;g.inventoryV63=true;const original=g.renderInventory?.bind(g);if(!original)return;g.renderInventory=function(){this.backpackCapacity=BAG;const r=original();restructure();patchGrid(this);return r;};g.backpackCapacity=BAG;restructure();installTooltip(g);g.renderInventory();}
function install(){const g=game();if(state.installed||!g||!A()||!V3()){setTimeout(install,80);return;}state.installed=true;ensureStyle();installRender(g);document.body.classList.add('astraeon-inventory-v63');}
if(document.readyState==='loading')global.addEventListener('DOMContentLoaded',install);else install();global.AstraeonInventoryV63={state,install,saleValue,purchaseValue};
})(window);
