(function(global){
'use strict';
const $=s=>document.querySelector(s),$$=s=>Array.from(document.querySelectorAll(s));
const RARITY={common:['Comum','#aaa59a'],uncommon:['Incomum','#7ac793'],rare:['Raro','#6ba9ef'],epic:['Épico','#c47df0'],legendary:['Lendário','#efbd56']};
const STAT_LABELS={strength:'Força',magic:'Magia',dexterity:'Destreza',power:'Poder',defense:'Defesa',maxHp:'Vida',maxMana:'Mana',heal:'Cura',mana:'Mana restaurada',healPct:'Aumento de cura',manaPct:'Aumento de mana',speed:'Velocidade',range:'Alcance',crit:'Crítico'};
const CLASS_LABELS={Warrior:'Guerreiro',Mage:'Mago',Archer:'Arqueiro',Assassin:'Assassino',Paladine:'Paladino'};
const state={installed:false,hoverTimer:null,holdTimer:null,holdTarget:null};
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function game(){return global.astraeon;}
function ensureCss(){if(document.querySelector('link[data-inventory-v7]'))return;const l=document.createElement('link');l.rel='stylesheet';l.href='src/inventory-v7.css';l.dataset.inventoryV7='1';document.head.appendChild(l);}
function ensureShell(){const panel=$('#inventoryPanel');if(!panel)return;panel.querySelector('[data-inv-tab="itemlist"]')?.remove();panel.querySelector('[data-inv-panel="itemlist"]')?.remove();let legend=panel.querySelector('.inventory-v7-legend');if(!legend){legend=document.createElement('div');legend.className='inventory-v7-legend';legend.innerHTML='<span class="armor"><i></i>Armaduras</span><span class="weapon"><i></i>Armas & Escudo</span><span class="mantle"><i></i>Manto do Reino</span><span class="accessory"><i></i>Acessórios</span>';panel.querySelector('.equipment-portrait')?.insertAdjacentElement('beforebegin',legend);} }
function estimateBuy(item){const direct=Number(item?.buyPrice??item?.buy_price??item?.price);if(Number.isFinite(direct)&&direct>0)return direct;const base={common:80,uncommon:160,rare:320,epic:700,legendary:1400}[item?.rarity]||80;let score=0;for(const v of Object.values(item?.stats||{}))score+=Math.abs(Number(v)||0);score+=Math.abs(Number(item?.power)||0)+Math.abs(Number(item?.heal)||0)/3+Math.abs(Number(item?.mana)||0)/3;return Math.max(20,Math.round(base+score*24));}
function saleValue(item){return Math.max(1,Math.floor(estimateBuy(item)*.1));}
function itemFromTarget(target){const g=game();if(!g||!target)return null;const inv=target.closest?.('#inventoryGrid [data-index]');if(inv)return g.inventory?.[Number(inv.dataset.index)]||null;const eq=target.closest?.('#equipmentGrid [data-slot]');if(eq)return g.equipment?.[eq.dataset.slot]||null;return null;}
function art(item){try{return global.AstraeonItemsV3?.artFor?.(item)||item?.imageUrl||item?.image_url||'';}catch(_){return item?.imageUrl||item?.image_url||'';}}
function stats(item){const out=[];const source={...(item?.stats||{})};for(const k of ['power','defense','heal','mana'])if(Number(item?.[k]))source[k]=item[k];for(const [k,v] of Object.entries(source)){const n=Number(v);if(!Number.isFinite(n)||!n||!STAT_LABELS[k])continue;const pct=k.endsWith('Pct')||k==='crit';const display=k==='crit'?`${(n*100).toFixed(n<.1?1:0)}%`:`${n>0?'+':''}${n}${pct?'%':''}`;out.push([STAT_LABELS[k],display]);}return out;}
function ensureTooltip(){let tip=$('#itemTooltipV7');if(!tip){tip=document.createElement('aside');tip.id='itemTooltipV7';tip.className='item-tooltip-v7';document.body.appendChild(tip);}let hold=$('#itemHoldV7');if(!hold){hold=document.createElement('i');hold.id='itemHoldV7';hold.className='item-hold-v7';document.body.appendChild(hold);}return{tip,hold};}
function renderTooltip(item){const {tip}=ensureTooltip(),r=RARITY[item?.rarity]||RARITY.common,rows=stats(item),classes=(item?.allowedClasses||[]).map(c=>CLASS_LABELS[c]||c);tip.style.setProperty('--rarity',r[1]);tip.innerHTML=`<header><div class="art">${art(item)?`<img src="${esc(art(item))}" alt="">`:(item?.icon||'◇')}</div><div><span>${esc(r[0])} · ${esc(item?.slot||item?.type||'Item')}</span><h3>${esc(item?.name||'Item')}</h3><small>${item?.level?`Nível ${Number(item.level)} · `:''}${item?.qty>1?`Qtd. ${Number(item.qty)}`:'Equipamento de Astra'}</small></div></header><div class="body"><p class="desc">${esc(item?.description||'Item encontrado durante sua jornada em Astra.')}</p><div class="stats">${rows.length?rows.map(([k,v])=>`<span class="stat"><span>${esc(k)}</span><b>${esc(v)}</b></span>`).join(''):'<span class="stat"><span>Atributos</span><b>Sem bônus</b></span>'}</div>${classes.length?`<span class="stat"><span>Classes</span><b>${esc(classes.join(', '))}</b></span>`:''}</div><footer><span>Valor de venda</span><b>${saleValue(item)} ouro</b></footer>`;return tip;}
function positionTip(tip,x,y){if(innerWidth<=760)return;const pad=12,w=310,h=Math.min(360,tip.offsetHeight||260);let left=x+18,top=y+18;if(left+w>innerWidth-pad)left=x-w-18;if(top+h>innerHeight-pad)top=innerHeight-h-pad;tip.style.left=`${Math.max(pad,left)}px`;tip.style.top=`${Math.max(pad,top)}px`;}
function show(item,x,y){if(!item)return;const tip=renderTooltip(item);positionTip(tip,x,y);requestAnimationFrame(()=>tip.classList.add('show'));}
function hide(){clearTimeout(state.hoverTimer);$('#itemTooltipV7')?.classList.remove('show');}
function cancelHold(){clearTimeout(state.holdTimer);state.holdTimer=null;state.holdTarget=null;$('#itemHoldV7')?.classList.remove('active');}
function fillEmptySlots(){const grid=$('#inventoryGrid');if(!grid)return;grid.querySelectorAll('.inventory-v7-empty-slot').forEach(x=>x.remove());const visible=grid.querySelectorAll('.item-card-slot[data-index]').length;for(let i=visible;i<25;i++){const e=document.createElement('div');e.className='inventory-v7-empty-slot';e.setAttribute('aria-hidden','true');grid.appendChild(e);}}
function decorateSlots(){const grid=$('#equipmentGrid');if(grid)grid.querySelectorAll('[data-slot]').forEach(el=>{const s=el.dataset.slot;el.dataset.inventoryCategory=['head','chest','hands','boots'].includes(s)?'armor':s==='weapon'?'weapon':s==='relic'?'mantle':'accessory';});fillEmptySlots();}
function bindTooltip(){const panel=$('#inventoryPanel');if(!panel||panel.dataset.tooltipV7==='1')return;panel.dataset.tooltipV7='1';panel.addEventListener('pointerover',e=>{if(e.pointerType==='touch')return;const item=itemFromTarget(e.target);if(!item)return;clearTimeout(state.hoverTimer);state.hoverTimer=setTimeout(()=>show(item,e.clientX,e.clientY),260);});panel.addEventListener('pointermove',e=>{const tip=$('#itemTooltipV7');if(tip?.classList.contains('show'))positionTip(tip,e.clientX,e.clientY);});panel.addEventListener('pointerout',e=>{if(e.target.closest?.('#inventoryGrid [data-index],#equipmentGrid [data-slot]'))hide();});panel.addEventListener('pointerdown',e=>{const item=itemFromTarget(e.target);if(!item)return;const {hold}=ensureTooltip();state.holdTarget=item;hold.style.left=`${e.clientX}px`;hold.style.top=`${e.clientY}px`;hold.classList.remove('active');void hold.offsetWidth;hold.classList.add('active');state.holdTimer=setTimeout(()=>{hold.classList.remove('active');show(item,e.clientX,e.clientY);state.holdTimer=null;},700);},{capture:true});global.addEventListener('pointerup',cancelHold,true);global.addEventListener('pointercancel',cancelHold,true);}
function hookRender(g){if(g.inventoryV7Installed)return;g.inventoryV7Installed=true;g.backpackCapacity=25;const original=g.renderInventory?.bind(g);if(original)g.renderInventory=function(){const r=original();ensureShell();decorateSlots();const meta=$('#inventoryMeta');if(meta&&this.player){const count=this.inventory?.length||0;meta.firstChild&&(meta.firstChild.textContent=`${count} itens · ${this.gold||0} ouro · `);}return r;};const originalStart=g.startNew?.bind(g);if(originalStart)g.startNew=function(){const r=originalStart();this.backpackCapacity=25;this.renderInventory?.();return r;};const originalContinue=g.continueGame?.bind(g);if(originalContinue)g.continueGame=function(){const r=originalContinue();this.backpackCapacity=25;this.renderInventory?.();return r;};}
function install(){const g=game();if(state.installed||!g)return;state.installed=true;ensureCss();ensureShell();hookRender(g);bindTooltip();decorateSlots();new MutationObserver(decorateSlots).observe($('#inventoryGrid')||document.body,{childList:true,subtree:false});document.body.classList.add('inventory-v7-ready');}
function wait(){if(game()&&$('#inventoryPanel'))install();else setTimeout(wait,70);}if(document.readyState==='loading')global.addEventListener('DOMContentLoaded',wait);else wait();global.AstraeonInventoryV7={install,saleValue};
})(window);
