(function () {
  'use strict';

  const W = window.AstraeonWorld;
  if (!W) return;

  const SLOT_META = {
    weapon: { label: 'Arma', icon: '⚔' },
    head: { label: 'Elmo', icon: '♜' },
    chest: { label: 'Peitoral', icon: '◈' },
    hands: { label: 'Luvas', icon: '✦' },
    boots: { label: 'Botas', icon: '⌁' },
    ring: { label: 'Anel', icon: '◌' },
    amulet: { label: 'Amuleto', icon: '◇' },
    relic: { label: 'Relicário', icon: '✧' }
  };

  const RARITY = {
    common: { label: 'Comum', mult: 1 },
    uncommon: { label: 'Incomum', mult: 1.18 },
    rare: { label: 'Raro', mult: 1.42 },
    epic: { label: 'Épico', mult: 1.72 },
    legendary: { label: 'Lendário', mult: 2.12 }
  };

  const ITEMS = {
    warrior_blade: { id:'warrior_blade', name:'Espada de Astrium', type:'equipment', slot:'weapon', rarity:'rare', icon:'⚔', description:'Lâmina de liga astral equilibrada para combate frontal.', stats:{power:4} },
    mage_staff: { id:'mage_staff', name:'Cetro de Lúmen', type:'equipment', slot:'weapon', rarity:'rare', icon:'⚕', description:'Canaliza a luz da Convergência e amplia o fluxo de mana.', stats:{power:4,maxMana:12} },
    archer_bow: { id:'archer_bow', name:'Arco de Éter', type:'equipment', slot:'weapon', rarity:'rare', icon:'➶', description:'Arco leve com corda astral para tiros precisos a longa distância.', stats:{power:4,range:16} },
    assassin_blades: { id:'assassin_blades', name:'Lâminas do Vazio', type:'equipment', slot:'weapon', rarity:'rare', icon:'⚔', description:'Par de lâminas rápidas afinadas para golpes críticos.', stats:{power:4,crit:.025} },
    paladine_mace: { id:'paladine_mace', name:'Maça Solar', type:'equipment', slot:'weapon', rarity:'rare', icon:'✹', description:'Arma jurada que converte impacto em proteção.', stats:{power:3,defense:2} },
    rune_blade: { id:'rune_blade', name:'Lâmina Rúnica', type:'equipment', slot:'weapon', rarity:'uncommon', icon:'⚔', description:'Uma lâmina marcada por runas instáveis.', stats:{power:3} },
    lumen_hood: { id:'lumen_hood', name:'Capuz de Lúmen', type:'equipment', slot:'head', rarity:'uncommon', icon:'♜', description:'Tecido vivo do bosque que protege sem pesar.', stats:{defense:2,maxMana:6} },
    frost_crown: { id:'frost_crown', name:'Coroa de Nivora', type:'equipment', slot:'head', rarity:'rare', icon:'♜', description:'Cristais glaciais estabilizam mente e corpo.', stats:{defense:3,maxMana:12} },
    wanderer_cloak: { id:'wanderer_cloak', name:'Manto do Caminhante', type:'equipment', slot:'chest', rarity:'uncommon', icon:'◈', description:'Manto resistente feito para atravessar climas extremos.', stats:{defense:3,maxHp:12} },
    astrium_armor: { id:'astrium_armor', name:'Peitoral de Astrium', type:'equipment', slot:'chest', rarity:'rare', icon:'◈', description:'Placas leves que reverberam contra impactos.', stats:{defense:5,maxHp:24} },
    void_gloves: { id:'void_gloves', name:'Luvas do Vazio', type:'equipment', slot:'hands', rarity:'rare', icon:'✦', description:'Luvas que aceleram reações no instante do golpe.', stats:{power:2,crit:.02} },
    hunter_boots: { id:'hunter_boots', name:'Botas de Caçador', type:'equipment', slot:'boots', rarity:'uncommon', icon:'⌁', description:'Solado flexível para deslocamentos rápidos entre biomas.', stats:{speed:8,defense:1} },
    solar_boots: { id:'solar_boots', name:'Passos de Solvar', type:'equipment', slot:'boots', rarity:'rare', icon:'⌁', description:'Botas aquecidas por minério solar.', stats:{speed:12,maxHp:8} },
    ether_ring: { id:'ether_ring', name:'Anel de Éter', type:'equipment', slot:'ring', rarity:'rare', icon:'◌', description:'Aumenta a ressonância ofensiva do portador.', stats:{power:2,crit:.018} },
    umbria_ring: { id:'umbria_ring', name:'Selo de Umbria', type:'equipment', slot:'ring', rarity:'epic', icon:'◌', description:'Um anel escuro que recompensa precisão e risco.', stats:{power:3,crit:.035} },
    climate_talisman: { id:'climate_talisman', name:'Talismã Climático', type:'equipment', slot:'amulet', rarity:'rare', icon:'◇', description:'Equilibra a energia do corpo em condições hostis.', stats:{maxHp:18,maxMana:10,defense:2} },
    convergence_amulet: { id:'convergence_amulet', name:'Amuleto da Convergência', type:'equipment', slot:'amulet', rarity:'epic', icon:'◇', description:'Condensa ecos de vários biomas em um único foco.', stats:{power:3,defense:2,maxMana:16} },
    astral_core: { id:'astral_core', name:'Núcleo de Astra', type:'equipment', slot:'relic', rarity:'legendary', icon:'✧', description:'Relíquia da Convergência. Vibra com a energia do continente.', stats:{power:8,defense:4,maxHp:30,maxMana:20} },
    red_potion: { id:'red_potion', name:'Poção Rubra', type:'consumable', rarity:'common', icon:'♥', description:'Restaura 45 de vida.', heal:45, stackable:true },
    blue_potion: { id:'blue_potion', name:'Poção de Éter', type:'consumable', rarity:'uncommon', icon:'✦', description:'Restaura 55 de mana.', mana:55, stackable:true },
    astral_fragment: { id:'astral_fragment', name:'Fragmento Astral', type:'material', rarity:'uncommon', icon:'◆', description:'Matéria condensada usada por artesãos da Convergência.', stackable:true },
    core_fragment: { id:'core_fragment', name:'Fragmento de Núcleo', type:'material', rarity:'rare', icon:'◆', description:'Fragmento de um núcleo antigo ainda carregado de energia.', stackable:true }
  };

  const CLASS_WEAPON = { Warrior:'warrior_blade', Mage:'mage_staff', Archer:'archer_bow', Assassin:'assassin_blades', Paladine:'paladine_mace' };
  const LOOT_BY_BIOME = {
    forest:['lumen_hood','hunter_boots','ether_ring','red_potion','astral_fragment'],
    steppe:['rune_blade','solar_boots','astrium_armor','red_potion','core_fragment'],
    frost:['frost_crown','climate_talisman','blue_potion','core_fragment'],
    swamp:['void_gloves','umbria_ring','blue_potion','astral_fragment'],
    highland:['astrium_armor','convergence_amulet','rune_blade','core_fragment']
  };

  function cloneItem(id, overrides={}) {
    const src=ITEMS[id]; if(!src) return null;
    const out={...src,stats:{...(src.stats||{})},...overrides};
    if(src.stats||overrides.stats) out.stats={...(src.stats||{}),...(overrides.stats||{})};
    if(out.stackable&&!out.qty) out.qty=1;
    return out;
  }
  function slug(text){return String(text||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();}
  function inferLegacySlot(item){const n=slug(item?.name);if(n.includes('espada')||n.includes('lamina')||n.includes('cetro')||n.includes('arco')||n.includes('maca'))return'weapon';if(n.includes('capuz')||n.includes('coroa')||n.includes('elmo'))return'head';if(n.includes('manto')||n.includes('peitoral')||n.includes('armadura'))return'chest';if(n.includes('luva'))return'hands';if(n.includes('bota')||n.includes('passos'))return'boots';if(n.includes('anel')||n.includes('selo'))return'ring';if(n.includes('talisma')||n.includes('amuleto'))return'amulet';return'relic';}
  function normalizeLegacyItem(raw){
    if(!raw)return null;if(raw.id&&ITEMS[raw.id])return cloneItem(raw.id,raw);
    const byName=Object.values(ITEMS).find(x=>slug(x.name)===slug(raw.name));if(byName)return cloneItem(byName.id,raw);
    if(raw.heal)return{id:`legacy-${slug(raw.name).replace(/\s+/g,'-')||'potion'}`,name:raw.name||'Poção',type:'consumable',rarity:raw.rarity||'common',icon:'♥',description:`Restaura ${raw.heal} de vida.`,heal:raw.heal,stackable:true,qty:raw.qty||1};
    if(raw.type==='Material')return{id:`legacy-${slug(raw.name).replace(/\s+/g,'-')||'material'}`,name:raw.name||'Material',type:'material',rarity:raw.rarity||'common',icon:'◆',description:'Material obtido durante a exploração.',stackable:true,qty:raw.qty||1};
    const slot=inferLegacySlot(raw);return{id:`legacy-${slug(raw.name).replace(/\s+/g,'-')||'equipment'}`,name:raw.name||'Equipamento',type:'equipment',slot,rarity:raw.rarity||'common',icon:SLOT_META[slot]?.icon||'◇',description:'Equipamento legado migrado para o sistema 2.1.',stats:{power:Number(raw.power)||0,defense:Number(raw.defense)||0}};
  }

  function install(){
    const game=window.astraeon;if(!game||game.inventoryV21Installed)return;game.inventoryV21Installed=true;
    game.equipment=Object.fromEntries(Object.keys(SLOT_META).map(k=>[k,null]));
    game.discoveredItems=new Set();game.inventoryFilter='all';game.itemListFilter='all';game.inventorySearch='';game.itemListSearch='';game.selectedInventoryRef=null;game.baseStats=null;
    const originalSave=game.save.bind(game),originalStartNew=game.startNew.bind(game),originalContinue=game.continueGame.bind(game),originalGainXp=game.gainXp.bind(game),originalRollLoot=game.rollLoot.bind(game),originalUpdatePickups=game.updatePickups.bind(game),originalTogglePanel=game.togglePanel.bind(game);

    game.starterInventory=function(classId){return[cloneItem(CLASS_WEAPON[classId]||'warrior_blade'),cloneItem('red_potion',{qty:3}),cloneItem('astral_fragment',{qty:2})];};
    game.rollLoot=function(mob){const pool=LOOT_BY_BIOME[mob?.biome]||Object.keys(ITEMS);const id=pool[Math.floor(Math.random()*pool.length)];if(!ITEMS[id])return originalRollLoot(mob);const source=ITEMS[id];if(source.type==='equipment'){const r=Math.random(),rarity=r>.985?'legendary':r>.90?'epic':r>.72?'rare':r>.36?'uncommon':source.rarity||'common',mult=RARITY[rarity]?.mult||1,levelScale=1+Math.max(0,(this.player?.level||1)-1)*.07,stats={};Object.entries(source.stats||{}).forEach(([k,v])=>{const n=Number(v)||0;stats[k]=k==='crit'?+(n*mult).toFixed(3):Math.max(1,Math.round(n*mult*levelScale));});return cloneItem(id,{rarity,stats,level:this.player?.level||1,uid:`${id}-${Date.now().toString(36)}-${Math.random().toString(36).slice(2,6)}`});}return cloneItem(id,{qty:1});};

    game.captureBaseStats=function(subtractEquipped=false){const p=this.player,out={maxHp:Number(p.maxHp)||1,maxMana:Number(p.maxMana)||0,power:Number(p.power)||0,defense:Number(p.defense)||0,speed:Number(p.speed)||0,range:Number(p.range)||0,crit:Number(p.crit)||0};if(subtractEquipped&&this.equipment){const b=this.getEquipmentBonuses();Object.keys(out).forEach(k=>out[k]-=b[k]||0);}return out;};
    game.getEquipmentBonuses=function(){const b={maxHp:0,maxMana:0,power:0,defense:0,speed:0,range:0,crit:0};Object.values(this.equipment||{}).forEach(item=>Object.entries(item?.stats||{}).forEach(([k,v])=>{if(k in b)b[k]+=Number(v)||0;}));return b;};
    game.recalculateEquipmentStats=function(){if(!this.player||!this.baseStats)return;const p=this.player,beforeHp=Math.max(1,p.maxHp||1),beforeMana=Math.max(1,p.maxMana||1),hpRatio=Math.max(0,Math.min(1,p.hp/beforeHp)),manaRatio=Math.max(0,Math.min(1,p.mana/beforeMana)),b=this.getEquipmentBonuses();p.maxHp=Math.max(1,Math.round(this.baseStats.maxHp+b.maxHp));p.maxMana=Math.max(0,Math.round(this.baseStats.maxMana+b.maxMana));p.power=Math.max(0,Math.round(this.baseStats.power+b.power));p.defense=Math.max(0,Math.round(this.baseStats.defense+b.defense));p.speed=Math.max(60,Math.round(this.baseStats.speed+b.speed));p.range=Math.max(32,Math.round(this.baseStats.range+b.range));p.crit=Math.max(0,Math.min(.75,+(this.baseStats.crit+b.crit).toFixed(3)));p.hp=Math.min(p.maxHp,Math.max(1,Math.round(p.maxHp*hpRatio)));p.mana=Math.min(p.maxMana,Math.max(0,Math.round(p.maxMana*manaRatio)));};

    game.startNew=function(){originalStartNew();if(!this.player)return;this.equipment=Object.fromEntries(Object.keys(SLOT_META).map(k=>[k,null]));this.inventory=(this.inventory||[]).map(normalizeLegacyItem).filter(Boolean);this.baseStats=this.captureBaseStats();this.discoveredItems=new Set(this.inventory.map(i=>i.id).filter(Boolean));this.renderInventory();this.save();};
    game.continueGame=function(){let raw=null;try{raw=JSON.parse(localStorage.getItem(W.STORAGE_SAVE)||'null');}catch(_){}originalContinue();if(!this.player)return;this.inventory=(this.inventory||[]).map(normalizeLegacyItem).filter(Boolean);this.equipment=Object.fromEntries(Object.keys(SLOT_META).map(k=>[k,null]));if(raw?.equipment)for(const slot of Object.keys(SLOT_META))this.equipment[slot]=normalizeLegacyItem(raw.equipment[slot]);this.baseStats=raw?.baseStats||this.captureBaseStats(true);this.discoveredItems=new Set(raw?.discoveredItems||[]);this.inventory.forEach(i=>i?.id&&this.discoveredItems.add(i.id));Object.values(this.equipment).forEach(i=>i?.id&&this.discoveredItems.add(i.id));this.recalculateEquipmentStats();this.renderInventory();};
    game.save=function(){originalSave();if(!this.player)return;try{const data=JSON.parse(localStorage.getItem(W.STORAGE_SAVE)||'{}');data.inventorySystem='2.1';data.inventory=this.inventory;data.equipment=this.equipment;data.baseStats=this.baseStats;data.discoveredItems=Array.from(this.discoveredItems||[]);localStorage.setItem(W.STORAGE_SAVE,JSON.stringify(data));}catch(_){}};
    game.gainXp=function(amount){if(!this.baseStats)return originalGainXp(amount);const p=this.player;p.xp+=amount;while(p.xp>=p.xpNext){p.xp-=p.xpNext;p.level++;p.xpNext=Math.round(p.xpNext*1.32);this.baseStats.maxHp+=14;this.baseStats.maxMana+=8;this.baseStats.power+=2;this.baseStats.defense+=p.level%2;this.recalculateEquipmentStats();p.hp=p.maxHp;p.mana=p.maxMana;this.toast(`Nível ${p.level}! Seu vínculo astral cresceu.`);this.beep(880,.16,.05);}};

    game.addInventoryItem=function(raw){const item=normalizeLegacyItem(raw);if(!item)return false;if(item.stackable){const existing=this.inventory.find(x=>x?.id===item.id&&x.stackable);if(existing)existing.qty=(existing.qty||1)+(item.qty||1);else this.inventory.push(item);}else this.inventory.push(item);if(item.id)this.discoveredItems.add(item.id);return true;};
    game.equipItem=function(index,forcedSlot){const item=normalizeLegacyItem(this.inventory[index]);if(!item||item.type!=='equipment'){this.toast('Este item não pode ser equipado.');return false;}const slot=forcedSlot||item.slot;if(!SLOT_META[slot]||item.slot!==slot){this.toast(`Esse item pertence ao slot ${SLOT_META[item.slot]?.label||'correto'}.`);return false;}const old=this.equipment[slot];this.inventory.splice(index,1);if(old)this.inventory.push(old);this.equipment[slot]=item;this.discoveredItems.add(item.id);this.selectedInventoryRef={source:'equipment',slot};this.recalculateEquipmentStats();this.renderInventory();this.save();this.toast(`${item.name} equipado.`);this.beep(690,.05,.022);return true;};
    game.unequipItem=function(slot){const item=this.equipment?.[slot];if(!item)return false;this.inventory.push(item);this.equipment[slot]=null;this.selectedInventoryRef={source:'inventory',index:this.inventory.length-1};this.recalculateEquipmentStats();this.renderInventory();this.save();this.toast(`${item.name} voltou para a mochila.`);return true;};
    game.useInventoryItem=function(index){const item=this.inventory[index];if(!item||item.type!=='consumable')return false;let used=false;if(item.heal&&this.player.hp<this.player.maxHp){this.player.hp=Math.min(this.player.maxHp,this.player.hp+item.heal);used=true;}if(item.mana&&this.player.mana<this.player.maxMana){this.player.mana=Math.min(this.player.maxMana,this.player.mana+item.mana);used=true;}if(!used){this.toast('Você já está com os recursos cheios.');return false;}item.qty=(item.qty||1)-1;if(item.qty<=0)this.inventory.splice(index,1);this.selectedInventoryRef=null;this.renderInventory();this.save();this.toast(`${item.name} utilizado.`);this.beep(760,.05,.02);return true;};
    game.getSelectedItem=function(){const ref=this.selectedInventoryRef;if(!ref)return null;if(ref.source==='equipment')return this.equipment?.[ref.slot]||null;if(ref.source==='catalog')return cloneItem(ref.id);return this.inventory?.[ref.index]||null;};
    game.selectInventoryItem=function(ref){this.selectedInventoryRef=ref;this.renderInventory();};
    game.itemTypeLabel=function(item){if(item.type==='equipment')return SLOT_META[item.slot]?.label||'Equipamento';if(item.type==='consumable')return'Consumível';if(item.type==='material')return'Material';return'Item';};
    game.itemStatsText=function(item){const labels={power:'Poder',defense:'Defesa',maxHp:'Vida',maxMana:'Mana',speed:'Velocidade',range:'Alcance',crit:'Crítico'},parts=[];Object.entries(item?.stats||{}).forEach(([k,v])=>{if(v)parts.push(`${labels[k]||k} +${k==='crit'?`${(v*100).toFixed(1)}%`:v}`);});if(item?.heal)parts.push(`Cura +${item.heal}`);if(item?.mana)parts.push(`Mana +${item.mana}`);return parts;};

    game.renderItemDetails=function(root){if(!root)return;const item=this.getSelectedItem();if(!item){root.innerHTML='<div class="item-details-empty"><strong>Selecione um item</strong><span>Clique para ver atributos. Duplo clique ou botão direito equipa/usa rapidamente.</span></div>';return;}const statText=this.itemStatsText(item),equipped=this.selectedInventoryRef?.source==='equipment',owned=this.selectedInventoryRef?.source==='inventory'||equipped;root.dataset.rarity=item.rarity||'common';root.innerHTML=`<div class="detail-title"><span class="detail-icon">${item.icon||'◇'}</span><div><small>${RARITY[item.rarity]?.label||'Comum'} · ${this.itemTypeLabel(item)}</small><h3>${item.name}</h3></div></div><p>${item.description||'Item encontrado em Astraeon.'}</p><div class="detail-stats">${statText.length?statText.map(x=>`<span>${x}</span>`).join(''):'<span>Sem bônus de combate</span>'}</div><div class="detail-actions">${item.type==='equipment'&&owned?`<button id="detailPrimaryAction" class="inventory-action primary">${equipped?'Desequipar':'Equipar'}</button>`:''}${item.type==='consumable'&&this.selectedInventoryRef?.source==='inventory'?'<button id="detailPrimaryAction" class="inventory-action primary">Usar</button>':''}<button id="detailClearAction" class="inventory-action">Fechar detalhe</button></div>`;root.querySelector('#detailPrimaryAction')?.addEventListener('click',()=>{const ref=this.selectedInventoryRef;if(!ref)return;if(item.type==='equipment')ref.source==='equipment'?this.unequipItem(ref.slot):this.equipItem(ref.index);else if(item.type==='consumable'&&ref.source==='inventory')this.useInventoryItem(ref.index);});root.querySelector('#detailClearAction')?.addEventListener('click',()=>{this.selectedInventoryRef=null;this.renderInventory();});};

    game.renderItemList=function(root){if(!root)return;const search=slug(this.itemListSearch),filter=this.itemListFilter||'all',owned=new Map();this.inventory.forEach(i=>owned.set(i.id,(owned.get(i.id)||0)+(i.qty||1)));Object.values(this.equipment||{}).forEach(i=>i&&owned.set(i.id,(owned.get(i.id)||0)+1));const list=Object.values(ITEMS).filter(item=>(filter==='all'||item.type===filter||item.slot===filter)&&(!search||slug(`${item.name} ${item.description} ${item.slot||''}`).includes(search)));root.innerHTML=list.map(item=>{const discovered=this.discoveredItems.has(item.id),count=owned.get(item.id)||0,stats=this.itemStatsText(item).slice(0,2).join(' · ');return`<button class="itemlist-row ${discovered?'':'undiscovered'}" data-id="${item.id}" data-rarity="${item.rarity}"><span class="itemlist-icon">${discovered?item.icon:'?'}</span><span class="itemlist-copy"><b>${discovered?item.name:'Item não descoberto'}</b><small>${discovered?`${RARITY[item.rarity].label} · ${this.itemTypeLabel(item)}${stats?` · ${stats}`:''}`:'Explore o mundo para registrar este item.'}</small></span><em>${count?`x${count}`:discovered?'0':'—'}</em></button>`;}).join('')||'<div class="itemlist-empty">Nenhum item corresponde ao filtro.</div>';root.querySelectorAll('.itemlist-row:not(.undiscovered)').forEach(btn=>btn.addEventListener('click',()=>{const id=btn.dataset.id,invIndex=this.inventory.findIndex(i=>i?.id===id);if(invIndex>=0)this.selectedInventoryRef={source:'inventory',index:invIndex};else{const slot=Object.keys(this.equipment).find(k=>this.equipment[k]?.id===id);this.selectedInventoryRef=slot?{source:'equipment',slot}:{source:'catalog',id};}this.renderInventory();}));};

    game.renderInventory=function(){const grid=document.querySelector('#inventoryGrid'),meta=document.querySelector('#inventoryMeta'),equipGrid=document.querySelector('#equipmentGrid'),stats=document.querySelector('#equipmentStats'),details=document.querySelector('#itemDetails'),itemList=document.querySelector('#itemListResults');if(!grid||!equipGrid||!this.player)return;this.inventory=(this.inventory||[]).map(normalizeLegacyItem).filter(Boolean);this.inventory.forEach(i=>i?.id&&this.discoveredItems.add(i.id));const equippedCount=Object.values(this.equipment||{}).filter(Boolean).length;if(meta)meta.textContent=`${this.inventory.length} itens na mochila · ${equippedCount}/${Object.keys(SLOT_META).length} equipados · ${this.gold} ouro`;const search=slug(this.inventorySearch),filter=this.inventoryFilter||'all',rows=this.inventory.map((item,index)=>({item,index})).filter(({item})=>(filter==='all'||item.type===filter)&&(!search||slug(`${item.name} ${item.description} ${item.slot||''}`).includes(search)));grid.innerHTML='';const capacity=Math.max(30,Math.ceil(Math.max(rows.length,1)/6)*6);rows.forEach(({item,index})=>{const slot=document.createElement('button');slot.className='inventory-slot item-card-slot';slot.dataset.rarity=item.rarity||'common';slot.draggable=true;slot.dataset.index=String(index);slot.innerHTML=`<strong>${item.icon||'◇'}</strong><span>${item.name}</span>${item.qty?`<em>${item.qty}</em>`:''}`;slot.title=`${RARITY[item.rarity]?.label||'Comum'} · ${this.itemTypeLabel(item)}`;slot.classList.toggle('selected',this.selectedInventoryRef?.source==='inventory'&&this.selectedInventoryRef.index===index);slot.addEventListener('click',()=>this.selectInventoryItem({source:'inventory',index}));slot.addEventListener('dblclick',()=>item.type==='equipment'?this.equipItem(index):item.type==='consumable'?this.useInventoryItem(index):null);slot.addEventListener('contextmenu',e=>{e.preventDefault();if(item.type==='equipment')this.equipItem(index);else if(item.type==='consumable')this.useInventoryItem(index);});slot.addEventListener('dragstart',e=>{e.dataTransfer.setData('text/astraeon-item',JSON.stringify({source:'inventory',index}));e.dataTransfer.effectAllowed='move';});grid.appendChild(slot);});for(let i=rows.length;i<capacity;i++){const empty=document.createElement('button');empty.className='inventory-slot empty';empty.disabled=true;grid.appendChild(empty);}grid.ondragover=e=>{if(e.dataTransfer.types.includes('text/astraeon-item'))e.preventDefault();};grid.ondrop=e=>{e.preventDefault();try{const data=JSON.parse(e.dataTransfer.getData('text/astraeon-item'));if(data.source==='equipment')this.unequipItem(data.slot);}catch(_){}};
      equipGrid.innerHTML='';Object.entries(SLOT_META).forEach(([slotId,info])=>{const item=this.equipment?.[slotId],el=document.createElement('button');el.className='equipment-slot';el.dataset.slot=slotId;if(item){el.dataset.rarity=item.rarity||'common';el.draggable=true;el.innerHTML=`<small>${info.label}</small><strong>${item.icon||info.icon}</strong><span>${item.name}</span>`;el.classList.toggle('selected',this.selectedInventoryRef?.source==='equipment'&&this.selectedInventoryRef.slot===slotId);el.addEventListener('click',()=>this.selectInventoryItem({source:'equipment',slot:slotId}));el.addEventListener('dblclick',()=>this.unequipItem(slotId));el.addEventListener('contextmenu',e=>{e.preventDefault();this.unequipItem(slotId);});el.addEventListener('dragstart',e=>{e.dataTransfer.setData('text/astraeon-item',JSON.stringify({source:'equipment',slot:slotId}));e.dataTransfer.effectAllowed='move';});}else{el.classList.add('empty');el.innerHTML=`<small>${info.label}</small><strong>${info.icon}</strong><span>Vazio</span>`;}el.addEventListener('dragover',e=>{if(e.dataTransfer.types.includes('text/astraeon-item')){e.preventDefault();el.classList.add('dragover');}});el.addEventListener('dragleave',()=>el.classList.remove('dragover'));el.addEventListener('drop',e=>{e.preventDefault();el.classList.remove('dragover');try{const data=JSON.parse(e.dataTransfer.getData('text/astraeon-item'));if(data.source==='inventory')this.equipItem(data.index,slotId);}catch(_){}});equipGrid.appendChild(el);});const b=this.getEquipmentBonuses();if(stats)stats.innerHTML=`<div><span>Poder</span><b>${this.player.power}<i>+${b.power}</i></b></div><div><span>Defesa</span><b>${this.player.defense}<i>+${b.defense}</i></b></div><div><span>Vida máx.</span><b>${this.player.maxHp}<i>+${b.maxHp}</i></b></div><div><span>Mana máx.</span><b>${this.player.maxMana}<i>+${b.maxMana}</i></b></div><div><span>Velocidade</span><b>${this.player.speed}<i>+${b.speed}</i></b></div><div><span>Crítico</span><b>${Math.round(this.player.crit*100)}%<i>+${(b.crit*100).toFixed(1)}%</i></b></div>`;this.renderItemDetails(details);this.renderItemList(itemList);};

    game.updatePickups=function(dt){const before=this.inventory.length;originalUpdatePickups(dt);if(this.inventory.length>before){const incoming=this.inventory.splice(before);incoming.forEach(item=>this.addInventoryItem(item));}};
    game.togglePanel=function(panel){originalTogglePanel(panel);if(panel===this.ui.inventoryPanel&&!panel.classList.contains('hidden'))this.renderInventory();};

    document.querySelector('#inventorySearch')?.addEventListener('input',e=>{game.inventorySearch=e.target.value;game.renderInventory();});
    document.querySelector('#itemListSearch')?.addEventListener('input',e=>{game.itemListSearch=e.target.value;game.renderInventory();});
    document.querySelectorAll('[data-inventory-filter]').forEach(btn=>btn.addEventListener('click',()=>{game.inventoryFilter=btn.dataset.inventoryFilter;document.querySelectorAll('[data-inventory-filter]').forEach(x=>x.classList.toggle('active',x===btn));game.renderInventory();}));
    document.querySelectorAll('[data-itemlist-filter]').forEach(btn=>btn.addEventListener('click',()=>{game.itemListFilter=btn.dataset.itemlistFilter;document.querySelectorAll('[data-itemlist-filter]').forEach(x=>x.classList.toggle('active',x===btn));game.renderInventory();}));

    game.inventory=(game.inventory||[]).map(normalizeLegacyItem).filter(Boolean);
    window.AstraeonItems={items:ITEMS,slots:SLOT_META,rarity:RARITY,cloneItem,normalizeLegacyItem};
  }

  window.addEventListener('DOMContentLoaded',install);
})();
