(function(global){
'use strict';
const W=global.AstraeonWorld;
if(!W)return;

const SUPABASE_CDN='https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2.91.0';
const CHAT_OPACITY_KEY='astraeon:v4:chat-opacity';
const state={config:null,client:null,session:null,profile:null,channel:null,channelStatus:'OFFLINE',remote:new Map(),messageIds:new Set(),lastStateAt:0,lastPresenceAt:0,lastStateKey:'',cloudTimer:null,ui:{},initialized:false,gameHooks:false};
const $=s=>document.querySelector(s);
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
const safeUsername=v=>String(v||'').replace(/[^A-Za-z0-9_]/g,'').slice(0,18);
const validUsername=v=>/^[A-Za-z0-9_]{3,18}$/.test(v);
const safeClass=v=>W.CLASS_DATA[v]?v:'Warrior';

function loadSupabase(){return new Promise((resolve,reject)=>{if(global.supabase?.createClient){resolve(global.supabase);return;}let s=document.querySelector('script[data-astraeon-supabase]');if(s){s.addEventListener('load',()=>resolve(global.supabase),{once:true});s.addEventListener('error',reject,{once:true});return;}s=document.createElement('script');s.src=SUPABASE_CDN;s.async=true;s.crossOrigin='anonymous';s.dataset.astraeonSupabase='1';s.onload=()=>global.supabase?.createClient?resolve(global.supabase):reject(new Error('Supabase SDK não iniciou'));s.onerror=()=>reject(new Error('Falha ao carregar Supabase SDK'));document.head.appendChild(s);});}
async function fetchConfig(){try{const r=await fetch('/api/config',{cache:'no-store',headers:{Accept:'application/json'}});if(!r.ok)throw new Error(`HTTP ${r.status}`);const cfg=await r.json();return cfg&&cfg.enabled?cfg:{enabled:false};}catch(_){return {enabled:false};}}

function createUI(){if($('#onlineAccountPanel'))return;document.title='ASTRAEON ONLINE — Multiplayer';const eyebrow=$('#startScreen .eyebrow');if(eyebrow)eyebrow.textContent='ASTRAEON ONLINE · cidades vivas, NPCs e multiplayer';document.querySelectorAll('.world-status .chip').forEach(ch=>{if(ch.textContent.includes('ASTRAEON'))ch.textContent='ASTRAEON ONLINE';});
  const menu=$('.start-panel .menu-actions');if(menu){const b=document.createElement('button');b.id='onlineAccountBtn';b.className='main-btn online-account-btn';b.innerHTML='Conta online <small id="onlineAccountBtnSub">Multiplayer indisponível · modo local</small>';b.addEventListener('click',()=>$('#onlineAccountPanel')?.classList.remove('hidden'));menu.appendChild(b);}
  const status=$('.world-status');if(status){const badge=document.createElement('span');badge.id='onlineWorldBadge';badge.className='chip online-world-badge offline';badge.textContent='● OFFLINE';status.appendChild(badge);}
  const auth=document.createElement('section');auth.id='onlineAccountPanel';auth.className='overlay-panel hidden online-account-panel';auth.innerHTML=`<div class="overlay-card online-account-card"><header class="overlay-head"><div><span class="panel-kicker">Astraeon Online</span><h2>Conta & Nuvem</h2><p>Conta segura, save em Postgres e acesso ao multiplayer.</p></div><button id="onlineAccountClose" class="panelClose" aria-label="Fechar">×</button></header><div id="onlineAuthGuest"><div class="online-auth-tabs"><button class="active" data-online-auth="login">Entrar</button><button data-online-auth="register">Cadastrar</button></div><form id="onlineLoginForm" class="online-auth-form"><label>E-mail<input id="onlineLoginEmail" type="email" autocomplete="email" required maxlength="120"></label><label>Senha<input id="onlineLoginPassword" type="password" autocomplete="current-password" required minlength="10" maxlength="128"></label><button class="inventory-action primary" type="submit">Entrar no Astraeon</button></form><form id="onlineRegisterForm" class="online-auth-form hidden"><label>Nome online<input id="onlineRegisterUsername" autocomplete="username" pattern="[A-Za-z0-9_]{3,18}" minlength="3" maxlength="18" required placeholder="Erick_01"></label><label>E-mail<input id="onlineRegisterEmail" type="email" autocomplete="email" required maxlength="120"></label><label>Senha<input id="onlineRegisterPassword" type="password" autocomplete="new-password" required minlength="10" maxlength="128" placeholder="mínimo 10 caracteres"></label><small class="online-security-note">A senha é processada pelo Supabase Auth e nunca é salva pelo jogo.</small><button class="inventory-action primary" type="submit">Criar conta</button></form></div><div id="onlineAuthMember" class="hidden"><div class="online-profile-card"><span id="onlineProfileAvatar">A</span><div><b id="onlineProfileName">Viajante</b><small id="onlineProfileEmail">—</small></div></div><div class="online-cloud-actions"><button id="onlineCloudPush" class="inventory-action primary">Salvar na nuvem</button><button id="onlineCloudPull" class="inventory-action">Carregar save da nuvem</button><button id="onlineLogout" class="inventory-action danger">Sair da conta</button></div></div><p id="onlineAuthMessage" class="online-auth-message">Configure Supabase no Vercel para ativar o modo online.</p></div>`;document.body.appendChild(auth);
  const chat=document.createElement('section');chat.id='onlineChat';chat.className='online-chat collapsed-mobile';chat.innerHTML=`<header><button id="onlineChatToggle" aria-label="Minimizar chat">▾</button><div><b>Chat de Astra</b><small id="onlineChatStatus">offline</small></div><span id="onlineCount">1 online</span><button id="onlineChatSettings" aria-label="Configurar chat">⚙</button></header><div id="onlineChatSettingsBox" class="online-chat-settings hidden"><label>Transparência <input id="onlineChatOpacity" type="range" min="25" max="95" step="5" value="78"><output id="onlineChatOpacityValue">78%</output></label></div><div id="onlineChatMessages" class="online-chat-messages" aria-live="polite"></div><form id="onlineChatForm"><input id="onlineChatInput" maxlength="240" autocomplete="off" placeholder="Enter para falar no mundo..." disabled><button type="submit" disabled>Enviar</button></form></section>`;document.body.appendChild(chat);
  state.ui={accountBtn:$('#onlineAccountBtn'),accountSub:$('#onlineAccountBtnSub'),badge:$('#onlineWorldBadge'),auth,guest:$('#onlineAuthGuest'),member:$('#onlineAuthMember'),authMessage:$('#onlineAuthMessage'),profileName:$('#onlineProfileName'),profileEmail:$('#onlineProfileEmail'),chat,chatStatus:$('#onlineChatStatus'),onlineCount:$('#onlineCount'),chatMessages:$('#onlineChatMessages'),chatInput:$('#onlineChatInput'),chatSend:$('#onlineChatForm button[type="submit"]'),opacity:$('#onlineChatOpacity'),opacityValue:$('#onlineChatOpacityValue')};
  $('#onlineAccountClose').addEventListener('click',()=>auth.classList.add('hidden'));document.querySelectorAll('[data-online-auth]').forEach(btn=>btn.addEventListener('click',()=>{document.querySelectorAll('[data-online-auth]').forEach(x=>x.classList.toggle('active',x===btn));$('#onlineLoginForm').classList.toggle('hidden',btn.dataset.onlineAuth!=='login');$('#onlineRegisterForm').classList.toggle('hidden',btn.dataset.onlineAuth!=='register');}));$('#onlineChatToggle').addEventListener('click',()=>chat.classList.toggle('collapsed'));$('#onlineChatSettings').addEventListener('click',()=>$('#onlineChatSettingsBox').classList.toggle('hidden'));
  const opacity=clamp(Number(localStorage.getItem(CHAT_OPACITY_KEY))||78,25,95);state.ui.opacity.value=opacity;applyChatOpacity(opacity);state.ui.opacity.addEventListener('input',()=>applyChatOpacity(Number(state.ui.opacity.value)));$('#onlineLoginForm').addEventListener('submit',login);$('#onlineRegisterForm').addEventListener('submit',register);$('#onlineLogout').addEventListener('click',logout);$('#onlineCloudPush').addEventListener('click',()=>saveCloud(true));$('#onlineCloudPull').addEventListener('click',loadCloudSave);$('#onlineChatForm').addEventListener('submit',sendChat);
  global.addEventListener('keydown',e=>{const active=document.activeElement;const inOnlineInput=active?.closest?.('#onlineAccountPanel,#onlineChat,#npcDialogue');if(inOnlineInput){if(e.key==='Escape'){active.blur();return;}e.stopImmediatePropagation();return;}if(e.key==='Enter'&&global.astraeon?.running&&!global.astraeon?.paused&&!state.ui.chatInput.disabled){e.preventDefault();e.stopImmediatePropagation();state.ui.chat.classList.remove('collapsed');state.ui.chatInput.focus();}},true);systemMessage('Chat iniciado em modo local. Entre em uma conta para falar com outros jogadores.');
}

function applyChatOpacity(value){const v=clamp(Number(value)||78,25,95);document.documentElement.style.setProperty('--online-chat-alpha',String(v/100));localStorage.setItem(CHAT_OPACITY_KEY,String(v));if(state.ui.opacityValue)state.ui.opacityValue.textContent=`${v}%`;}
function setAuthMessage(text,type=''){if(!state.ui.authMessage)return;state.ui.authMessage.textContent=text;state.ui.authMessage.dataset.type=type;}
function setStatus(mode,text){state.channelStatus=mode;if(state.ui.badge){state.ui.badge.className=`chip online-world-badge ${mode.toLowerCase()}`;state.ui.badge.textContent=`● ${text||mode}`;}if(state.ui.chatStatus)state.ui.chatStatus.textContent=(text||mode).toLowerCase();}
function systemMessage(text){appendChat({id:`sys-${Date.now()}-${Math.random()}`,username:'Sistema',body:text,created_at:new Date().toISOString(),system:true});}
function appendChat(msg){if(!msg||state.messageIds.has(String(msg.id)))return;state.messageIds.add(String(msg.id));if(state.messageIds.size>400){state.messageIds=new Set(Array.from(state.messageIds).slice(-250));}const box=state.ui.chatMessages;if(!box)return;const row=document.createElement('div');row.className=`online-chat-line${msg.system?' system':''}${msg.user_id===state.session?.user?.id?' mine':''}`;const head=document.createElement('div'),name=document.createElement('b'),time=document.createElement('time'),body=document.createElement('span');name.textContent=msg.username||'Viajante';time.textContent=new Date(msg.created_at||Date.now()).toLocaleTimeString('pt-BR',{hour:'2-digit',minute:'2-digit'});body.textContent=msg.body||'';head.append(name,time);row.append(head,body);box.appendChild(row);while(box.children.length>90)box.firstElementChild.remove();box.scrollTop=box.scrollHeight;const remote=state.remote.get(msg.user_id);if(remote&&!msg.system){remote.chatText=String(msg.body||'').slice(0,80);remote.chatUntil=performance.now()+4800;}}

async function register(e){e.preventDefault();if(!state.client){setAuthMessage('Modo online ainda não está configurado.','error');return;}const username=safeUsername($('#onlineRegisterUsername').value),email=$('#onlineRegisterEmail').value.trim(),password=$('#onlineRegisterPassword').value;if(!validUsername(username)){setAuthMessage('Use 3–18 caracteres: letras, números e _.','error');return;}if(password.length<10){setAuthMessage('Use uma senha com pelo menos 10 caracteres.','error');return;}setAuthMessage('Criando conta...');const {data,error}=await state.client.auth.signUp({email,password,options:{data:{username,display_name:username},emailRedirectTo:`${location.origin}/`}});if(error){setAuthMessage(error.message,'error');return;}if(!data.session)setAuthMessage('Conta criada. Confirme seu e-mail e depois faça login.','ok');else setAuthMessage('Conta criada e conectada.','ok');}
async function login(e){e.preventDefault();if(!state.client){setAuthMessage('Modo online ainda não está configurado.','error');return;}const email=$('#onlineLoginEmail').value.trim(),password=$('#onlineLoginPassword').value;setAuthMessage('Autenticando...');const {error}=await state.client.auth.signInWithPassword({email,password});if(error)setAuthMessage('Não foi possível entrar. Confira e-mail, senha e confirmação da conta.','error');}
async function logout(){if(!state.client)return;await state.client.auth.signOut();}
async function ensureProfile(user){const fallback=`Astral_${String(user.id).replace(/-/g,'').slice(0,8)}`;let {data,error}=await state.client.from('profiles').select('id,username,display_name,class_id,level,last_seen').eq('id',user.id).maybeSingle();if(error)throw error;if(!data){const created=await state.client.from('profiles').insert({id:user.id,username:fallback,display_name:fallback}).select().single();if(created.error)throw created.error;data=created.data;}const desired=safeUsername(user.user_metadata?.username);if(validUsername(desired)&&data.username!==desired&&String(data.username||'').startsWith('Astral_')){const claimed=await state.client.rpc('claim_username',{desired});if(!claimed.error&&claimed.data===true){const refreshed=await state.client.from('profiles').select('id,username,display_name,class_id,level,last_seen').eq('id',user.id).single();if(!refreshed.error)data=refreshed.data;}else if(claimed.data===false){systemMessage(`O nome ${desired} já estava em uso; sua conta ficou como ${data.username}.`);}}return data;}
async function handleSession(session){state.session=session||null;if(!session){disconnectWorld();state.profile=null;state.ui.guest?.classList.remove('hidden');state.ui.member?.classList.add('hidden');state.ui.chatInput.disabled=true;state.ui.chatSend.disabled=true;if(state.ui.accountSub)state.ui.accountSub.textContent=state.config?.enabled?'Entrar ou criar conta · multiplayer':'Multiplayer indisponível · modo local';setStatus('OFFLINE','OFFLINE');setAuthMessage(state.config?.enabled?'Entre para sincronizar seu personagem e acessar o mundo online.':'Configure Supabase no Vercel para ativar o modo online.');return;}try{state.profile=await ensureProfile(session.user);state.ui.guest?.classList.add('hidden');state.ui.member?.classList.remove('hidden');state.ui.profileName.textContent=state.profile.username;state.ui.profileEmail.textContent=session.user.email||'conta autenticada';if(state.ui.accountSub)state.ui.accountSub.textContent=`${state.profile.username} · conectado`;state.ui.chatInput.disabled=false;state.ui.chatSend.disabled=false;setAuthMessage('Conta autenticada. Saves persistentes e multiplayer estão disponíveis.','ok');await state.client.realtime.setAuth(session.access_token);await loadChatHistory();if(global.astraeon?.running)await connectWorld();}catch(err){console.error('[Astraeon Online] perfil',err);setAuthMessage('Banco ainda não foi inicializado. Execute a migration Supabase do projeto.','error');systemMessage('Falha ao carregar perfil online. Confira a configuração do banco.');}}
async function loadChatHistory(){if(!state.client||!state.session)return;const {data,error}=await state.client.from('chat_messages').select('id,user_id,username,body,channel,created_at').eq('channel','world').order('created_at',{ascending:false}).limit(50);if(error){console.warn('[Astraeon Online] chat history',error.message);return;}for(const m of (data||[]).reverse())appendChat(m);}
async function sendChat(e){e.preventDefault();const input=state.ui.chatInput,text=input.value.trim();if(!text)return;if(!state.session||!state.client){systemMessage('Faça login para usar o chat mundial.');return;}if(text.length>240)return;input.value='';if(text==='/clear'){state.ui.chatMessages.innerHTML='';state.messageIds.clear();return;}if(text==='/online'){systemMessage(`${Math.max(1,state.remote.size+1)} jogador(es) online nesta sala.`);return;}const {data,error}=await state.client.from('chat_messages').insert({user_id:state.session.user.id,body:text,channel:'world'}).select('id,user_id,username,body,channel,created_at').single();if(error){systemMessage(error.message.includes('rate')?'Você está enviando mensagens rápido demais.':'Mensagem não enviada.');return;}appendChat(data);}

function presencePayload(){const g=global.astraeon,p=g?.player;return {user_id:state.session?.user?.id,username:state.profile?.username||'Viajante',class_id:safeClass(p?.classId||state.profile?.class_id),level:Number(p?.level||state.profile?.level||1),x:Number(p?.x||0),y:Number(p?.y||0),online_at:new Date().toISOString()};}
function syncPresence(){if(!state.channel)return;const raw=state.channel.presenceState()||{},seen=new Set();for(const presences of Object.values(raw)){for(const p of presences||[]){if(!p?.user_id||p.user_id===state.session?.user?.id)continue;seen.add(p.user_id);let r=state.remote.get(p.user_id);if(!r){r={userId:p.user_id,x:Number(p.x)||0,y:Number(p.y)||0,targetX:Number(p.x)||0,targetY:Number(p.y)||0,lastSeen:performance.now()};state.remote.set(p.user_id,r);}r.username=safeUsername(p.username)||'Viajante';r.classId=safeClass(p.class_id);r.level=Math.max(1,Number(p.level)||1);r.lastSeen=performance.now();}}for(const id of Array.from(state.remote.keys()))if(!seen.has(id))state.remote.delete(id);updateOnlineCount();}
function updateOnlineCount(){const n=Math.max(1,state.remote.size+1);if(state.ui.onlineCount)state.ui.onlineCount.textContent=`${n} online`;if(state.channelStatus==='ONLINE')setStatus('ONLINE',`ONLINE · ${n}`);}
function receiveState(payload){const g=global.astraeon;if(!g?.world||!payload||payload.userId===state.session?.user?.id)return;const x=Number(payload.x),y=Number(payload.y),maxX=g.world.width*W.TILE,maxY=g.world.height*W.TILE;if(!Number.isFinite(x)||!Number.isFinite(y)||x<0||y<0||x>maxX||y>maxY)return;let r=state.remote.get(payload.userId);if(!r){r={userId:payload.userId,x,y,targetX:x,targetY:y,lastSeen:performance.now()};state.remote.set(payload.userId,r);}r.targetX=x;r.targetY=y;r.facing=Number(payload.facing)<0?-1:1;r.classId=safeClass(payload.classId);r.level=clamp(Number(payload.level)||1,1,999);r.username=safeUsername(payload.username)||r.username||'Viajante';r.lastSeen=performance.now();updateOnlineCount();}
function receiveAction(payload){const g=global.astraeon,r=state.remote.get(payload?.userId);if(!g||!r)return;const c=W.CLASS_DATA[r.classId]||W.CLASS_DATA.Warrior;if(payload.type==='skill')g.effects.push({type:'ring',x:r.x,y:r.y,life:.42,max:.42,color:c.color,radius:55+clamp(Number(payload.index)||0,0,4)*12});else g.effects.push({type:'slash',x:r.x+(r.facing||1)*18,y:r.y-5,life:.18,max:.18,color:c.color});}
async function connectWorld(){if(!state.client||!state.session||!global.astraeon?.running)return;disconnectWorld();setStatus('CONNECTING','CONECTANDO');await state.client.realtime.setAuth(state.session.access_token);const topic=state.config?.realtimeTopic||'world:astraeon:main';const channel=state.client.channel(topic,{config:{private:true,broadcast:{self:false,ack:false},presence:{key:state.session.user.id}}});state.channel=channel;channel.on('presence',{event:'sync'},syncPresence).on('presence',{event:'join'},syncPresence).on('presence',{event:'leave'},syncPresence).on('broadcast',{event:'player_state'},({payload})=>receiveState(payload)).on('broadcast',{event:'player_action'},({payload})=>receiveAction(payload)).on('postgres_changes',{event:'INSERT',schema:'public',table:'chat_messages',filter:'channel=eq.world'},payload=>appendChat(payload.new));channel.subscribe(async status=>{if(state.channel!==channel)return;if(status==='SUBSCRIBED'){setStatus('ONLINE','ONLINE');await channel.track(presencePayload());systemMessage('Você entrou no mundo online de Astra.');updateOnlineCount();}else if(status==='CHANNEL_ERROR'||status==='TIMED_OUT'){setStatus('ERROR','ERRO ONLINE');systemMessage('Falha na sala online. Confira as políticas Realtime do Supabase.');}else if(status==='CLOSED'){setStatus('OFFLINE','OFFLINE');}});}
function disconnectWorld(){if(state.channel&&state.client){try{state.client.removeChannel(state.channel);}catch(_){}}state.channel=null;state.remote.clear();updateOnlineCount();}
function sendState(game,now){if(!state.channel||state.channelStatus!=='ONLINE'||!game.player)return;if(now-state.lastStateAt<100)return;const p=game.player,key=`${Math.round(p.x)}:${Math.round(p.y)}:${p.facing}:${p.level}`;if(key===state.lastStateKey&&now-state.lastStateAt<900)return;state.lastStateAt=now;state.lastStateKey=key;void state.channel.send({type:'broadcast',event:'player_state',payload:{userId:state.session.user.id,username:state.profile?.username||p.name,classId:safeClass(p.classId),level:p.level,x:+p.x.toFixed(1),y:+p.y.toFixed(1),facing:p.facing,ts:Date.now()}});if(now-state.lastPresenceAt>15000){state.lastPresenceAt=now;void state.channel.track(presencePayload());}}
function sendAction(type,index){const g=global.astraeon;if(!state.channel||state.channelStatus!=='ONLINE'||!g?.player)return;void state.channel.send({type:'broadcast',event:'player_action',payload:{userId:state.session.user.id,type,index:Number(index)||0,x:g.player.x,y:g.player.y,classId:g.player.classId,ts:Date.now()}});}
function updateRemote(dt){const now=performance.now();for(const [id,r] of state.remote){r.x+=(r.targetX-r.x)*Math.min(1,dt*10);r.y+=(r.targetY-r.y)*Math.min(1,dt*10);if(now-r.lastSeen>12000)state.remote.delete(id);}}
function drawRemotePlayers(game,ctx){const now=performance.now();for(const r of Array.from(state.remote.values()).sort((a,b)=>a.y-b.y)){if(Math.abs(r.x-game.player.x)>game.viewW*.9+300||Math.abs(r.y-game.player.y)>game.viewH*.9+300)continue;const c=W.CLASS_DATA[r.classId]||W.CLASS_DATA.Warrior,src=`Assets/Classes/${c.sprite}`,img=game.images.get(src);ctx.save();ctx.translate(r.x,r.y);ctx.fillStyle='rgba(65,155,255,.16)';ctx.beginPath();ctx.arc(0,-8,25,0,Math.PI*2);ctx.fill();ctx.strokeStyle='rgba(103,190,255,.65)';ctx.lineWidth=1.5;ctx.stroke();ctx.fillStyle='rgba(0,0,0,.32)';ctx.beginPath();ctx.ellipse(0,12,15,5,0,0,Math.PI*2);ctx.fill();if(img){ctx.save();if(r.facing<0)ctx.scale(-1,1);ctx.globalAlpha=.93;ctx.drawImage(img,-24,-39,48,48);ctx.restore();}else{ctx.fillStyle=c.color;ctx.beginPath();ctx.arc(0,-8,16,0,Math.PI*2);ctx.fill();}ctx.restore();ctx.save();ctx.textAlign='center';ctx.shadowBlur=5;ctx.shadowColor='#000';ctx.font='700 10px Inter,sans-serif';ctx.fillStyle='#8bd2ff';ctx.fillText(`${r.username||'Viajante'} · Nv.${r.level||1}`,r.x,r.y-47);if(r.chatText&&r.chatUntil>now){const txt=r.chatText.length>46?`${r.chatText.slice(0,46)}…`:r.chatText;ctx.font='600 9px Inter,sans-serif';const w=Math.min(250,ctx.measureText(txt).width+16);ctx.fillStyle='rgba(8,12,17,.82)';ctx.fillRect(r.x-w/2,r.y-75,w,17);ctx.fillStyle='#f1eadf';ctx.fillText(txt,r.x,r.y-63);}ctx.restore();}}
function queueCloudSave(){clearTimeout(state.cloudTimer);state.cloudTimer=setTimeout(()=>saveCloud(false),2200);}
async function saveCloud(manual=false){const g=global.astraeon;if(!state.client||!state.session||!g?.player)return false;let save;try{save=JSON.parse(localStorage.getItem(W.STORAGE_SAVE)||'null');}catch(_){return false;}if(!save)return false;const now=new Date().toISOString();const {error}=await state.client.from('player_saves').upsert({user_id:state.session.user.id,save_data:save,world_seed:save.seed||g.world?.seedText||'',updated_at:now},{onConflict:'user_id'});if(error){if(manual)systemMessage('Falha ao salvar na nuvem.');return false;}await state.client.from('profiles').update({display_name:g.player.name,class_id:g.player.classId,level:g.player.level,last_seen:now}).eq('id',state.session.user.id);if(manual){systemMessage('Save enviado para a nuvem.');g.toast?.('Save na nuvem atualizado.');}return true;}
async function loadCloudSave(){const g=global.astraeon;if(!state.client||!state.session)return;if(g?.running){g.toast?.('Volte ao menu antes de carregar um save da nuvem.');return;}const {data,error}=await state.client.from('player_saves').select('save_data,updated_at').eq('user_id',state.session.user.id).maybeSingle();if(error||!data?.save_data){setAuthMessage('Nenhum save foi encontrado na nuvem para esta conta.','error');return;}localStorage.setItem(W.STORAGE_SAVE,JSON.stringify(data.save_data));setAuthMessage(`Save da nuvem carregado (${new Date(data.updated_at).toLocaleString('pt-BR')}).`,'ok');global.astraeon?.toast?.('Save da nuvem pronto. Clique em Continuar.');}
function installGameHooks(){const game=global.astraeon;if(!game||state.gameHooks)return;state.gameHooks=true;const originalStart=game.startNew.bind(game);game.startNew=function(){originalStart();if(this.running&&state.session){void connectWorld();queueCloudSave();}};const originalContinue=game.continueGame.bind(game);game.continueGame=function(){originalContinue();if(this.running&&state.session)void connectWorld();};const originalSave=game.save.bind(game);game.save=function(){originalSave();if(state.session)queueCloudSave();};const originalUpdate=game.update.bind(game);game.update=function(dt){originalUpdate(dt);updateRemote(dt);sendState(this,performance.now());};const originalDrawMobs=game.drawMobs.bind(game);game.drawMobs=function(ctx){originalDrawMobs(ctx);drawRemotePlayers(this,ctx);};const originalMini=game.drawMinimap.bind(game);game.drawMinimap=function(){originalMini();if(!this.world)return;const ctx=this.mctx,size=196;ctx.save();ctx.fillStyle='#66c8ff';for(const r of state.remote.values()){ctx.beginPath();ctx.arc(r.x/(W.TILE*this.world.width)*size,r.y/(W.TILE*this.world.height)*size,2.4,0,Math.PI*2);ctx.fill();}ctx.restore();};const originalAttack=game.basicAttack.bind(game);game.basicAttack=function(){const before=this.player?.attackCd||0;originalAttack();if((this.player?.attackCd||0)>before)sendAction('attack',0);};const originalSkill=game.castSkill.bind(game);game.castSkill=function(index){const before=this.cooldowns?.[index]||0;originalSkill(index);if((this.cooldowns?.[index]||0)>before)sendAction('skill',index);};}
async function init(){if(state.initialized)return;state.initialized=true;createUI();installGameHooks();state.config=await fetchConfig();if(!state.config.enabled){setStatus('OFFLINE','OFFLINE');setAuthMessage('Modo local ativo. No Vercel, configure SUPABASE_URL e SUPABASE_PUBLISHABLE_KEY para habilitar contas e multiplayer.');return;}try{const sdk=await loadSupabase();state.client=sdk.createClient(state.config.supabaseUrl,state.config.supabaseKey,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}});setStatus('CONNECTING','CONECTANDO');const {data}=await state.client.auth.getSession();await handleSession(data.session);state.client.auth.onAuthStateChange((_event,session)=>setTimeout(()=>handleSession(session),0));}catch(err){console.error('[Astraeon Online] init',err);setStatus('ERROR','ERRO');setAuthMessage('A configuração online existe, mas o cliente não conseguiu iniciar.','error');}}
function install(){createUI();installGameHooks();void init();}
global.AstraeonMultiplayerV4={state,install,connectWorld,disconnectWorld,saveCloud,loadCloudSave};
global.addEventListener('DOMContentLoaded',install);
})(window);
