(function(global){
'use strict';
const W=global.AstraeonWorld;
const OW=global.AstraeonOnlineWorld;
if(!W)return;

// Decisão temporária de produção: somente o Mestre de Habilidades permanece ativo.
const NPCS=[
  {id:'skill-master',city:'astralum',name:'Maeron',role:'Mestre de Habilidades',classId:'Mage',dx:0,dy:2,color:'#e5bd67',personality:'solene'}
];

function cityById(id){return (OW?.CITIES||[]).find(c=>c.id===id);}
function makeNpc(def){const c=cityById(def.city);if(!c)return null;return {...def,x:(c.x+def.dx+.5)*W.TILE,y:(c.y+def.dy+.5)*W.TILE,homeX:(c.x+def.dx+.5)*W.TILE,homeY:(c.y+def.dy+.5)*W.TILE,targetX:(c.x+def.dx+.5)*W.TILE,targetY:(c.y+def.dy+.5)*W.TILE,facing:1,speed:40+Math.random()*16,moveTimer:1+Math.random()*3,talk:false,memory:[]};}
function buildNpcs(game){game.npcsV4=NPCS.map(makeNpc).filter(Boolean);}
function safeTarget(game,npc){const c=cityById(npc.city);if(!c)return;for(let i=0;i<14;i++){const tx=c.x+Math.round((Math.random()-.5)*Math.max(3,c.radius-2)*2),ty=c.y+Math.round((Math.random()-.5)*Math.max(3,c.radius-2)*2);const t=game.world?.get(tx,ty);if(t&&!t.blocked&&t.kind!=='water'){npc.targetX=(tx+.5)*W.TILE;npc.targetY=(ty+.5)*W.TILE;return;}}npc.targetX=npc.homeX;npc.targetY=npc.homeY;}
function nearest(game,max=72){if(!game.player)return null;let best=null,bd=max;for(const n of game.npcsV4||[]){const d=W.dist(n.x,n.y,game.player.x,game.player.y);if(d<bd){best=n;bd=d;}}return best;}
function updateNpcs(game,dt){if(!game.world||!game.player)return;for(const n of game.npcsV4||[]){if(n.talk)continue;n.moveTimer-=dt;const d=W.dist(n.x,n.y,n.targetX,n.targetY);if(n.moveTimer<=0||d<8){safeTarget(game,n);n.moveTimer=2.5+Math.random()*5;continue;}const vx=(n.targetX-n.x)/Math.max(1,d),vy=(n.targetY-n.y)/Math.max(1,d);n.facing=vx<-.05?-1:vx>.05?1:n.facing;game.moveEntity?.(n,vx*n.speed*dt,vy*n.speed*dt,8);}}
function drawNpcs(game,ctx){if(!game.player)return;const list=(game.npcsV4||[]).slice().sort((a,b)=>a.y-b.y);const close=nearest(game,78);for(const n of list){if(Math.abs(n.x-game.player.x)>game.viewW*.9+300||Math.abs(n.y-game.player.y)>game.viewH*.9+300)continue;const c=W.CLASS_DATA[n.classId]||W.CLASS_DATA.Warrior,src=`Assets/Classes/${c.sprite}`,img=game.images?.get(src);ctx.save();ctx.translate(n.x,n.y);ctx.fillStyle='rgba(0,0,0,.3)';ctx.beginPath();ctx.ellipse(0,12,13,4.5,0,0,Math.PI*2);ctx.fill();if(img){ctx.save();if(n.facing<0)ctx.scale(-1,1);ctx.globalAlpha=.94;ctx.drawImage(img,-21,-35,42,42);ctx.restore();}else{ctx.fillStyle=n.color;ctx.beginPath();ctx.arc(0,-7,14,0,Math.PI*2);ctx.fill();}if(close===n){ctx.strokeStyle=n.color;ctx.globalAlpha=.5;ctx.lineWidth=2;ctx.beginPath();ctx.arc(0,-7,22,0,Math.PI*2);ctx.stroke();}ctx.restore();ctx.save();ctx.textAlign='center';ctx.shadowBlur=4;ctx.shadowColor='#000';ctx.font='700 10px Inter,sans-serif';ctx.fillStyle=n.color;ctx.fillText(n.name,n.x,n.y-43);ctx.font='600 8px Inter,sans-serif';ctx.fillStyle='#d8d1c4';ctx.fillText(n.role,n.x,n.y-33);if(close===n){ctx.font='700 9px Inter,sans-serif';ctx.fillStyle='#ffe19b';ctx.fillText('Segure E ou clique · Aprender',n.x,n.y+31);}ctx.restore();}}
function createDialogue(){if(document.querySelector('#npcDialogue'))return;const root=document.createElement('section');root.id='npcDialogue';root.className='npc-dialogue hidden';root.innerHTML='<div class="npc-dialogue-card"><header><div><small>IA local contextual</small><h3 id="npcDialogueName">NPC</h3><span id="npcDialogueRole">Habitante de Astraeon</span></div><button id="npcDialogueClose" aria-label="Fechar">×</button></header><div id="npcDialogueMessages" class="npc-dialogue-messages"></div><form id="npcDialogueForm"><input id="npcDialogueInput" maxlength="180" autocomplete="off" placeholder="Pergunte sobre a cidade, missões, clima ou equipamentos..."><button type="submit">Falar</button></form></div>';document.body.appendChild(root);root.querySelector('#npcDialogueClose').addEventListener('click',()=>closeDialogue());root.querySelector('#npcDialogueForm').addEventListener('submit',e=>{e.preventDefault();const input=root.querySelector('#npcDialogueInput'),text=input.value.trim();if(!text)return;input.value='';const game=global.astraeon,npc=game?.activeNpcV4;if(!npc)return;appendDialogue('Você',text,'player');setTimeout(()=>appendDialogue(npc.name,respond(npc,text,game),'npc'),120);});}
function appendDialogue(name,text,type){const box=document.querySelector('#npcDialogueMessages');if(!box)return;const row=document.createElement('div');row.className=`npc-line ${type}`;const b=document.createElement('b'),span=document.createElement('span');b.textContent=name;span.textContent=text;row.append(b,span);box.appendChild(row);box.scrollTop=box.scrollHeight;}
function openDialogue(game,npc){if(npc?.id==='skill-master'&&global.AstraeonSkillsV1?.openMerchant){global.AstraeonSkillsV1.openMerchant();return;}createDialogue();(game.npcsV4||[]).forEach(n=>n.talk=false);npc.talk=true;game.activeNpcV4=npc;const root=document.querySelector('#npcDialogue');root.classList.remove('hidden');root.querySelector('#npcDialogueName').textContent=npc.name;root.querySelector('#npcDialogueRole').textContent=npc.role;root.querySelector('#npcDialogueMessages').innerHTML='';appendDialogue(npc.name,greeting(npc,game),'npc');setTimeout(()=>root.querySelector('#npcDialogueInput')?.focus(),30);}
function closeDialogue(){const game=global.astraeon;if(game?.activeNpcV4)game.activeNpcV4.talk=false;if(game)game.activeNpcV4=null;document.querySelector('#npcDialogue')?.classList.add('hidden');}
function greeting(npc,game){const city=cityById(npc.city);return `Saudações, ${game?.player?.name||'viajante'}. Eu sou ${npc.name}, ${npc.role.toLowerCase()} de ${city?.name||'Astraeon'}. O que deseja saber?`;}
function respond(npc,raw,game){const text=raw.toLocaleLowerCase('pt-BR'),city=cityById(npc.city),biome=city?W.BIOMES[city.biome]:null,p=game?.player;const rules=[
  {keys:['quem é você','quem e voce','seu nome'],answer:`Sou ${npc.name}. Minha função é ${npc.role.toLowerCase()}, e conheço bem ${city?.name||'esta região'}.`},
  {keys:['cidade','onde estou','lugar'],answer:`Você está perto de ${city?.name||'uma cidade de Astraeon'} — ${city?.subtitle||'um refúgio da Convergência'}. As estradas centrais levam ao mercado e aos portões.`},
  {keys:['clima','bioma','tempo'],answer:`Aqui domina ${biome?.climate||'um clima instável'}. ${biome?.feature||'A Convergência altera o terreno ao redor.'}`},
  {keys:['missão','missao','quest','trabalho'],answer:`Explore os arredores de ${city?.name||'Astraeon'}, elimine criaturas e observe os biomas. Quanto mais regiões você estabiliza, mais forte fica seu vínculo astral.`},
  {keys:['arma','equipamento','item','armadura'],answer:npc.role.includes('Ferreiro')?'Traga equipamentos adequados à sua classe. Peças incompatíveis ainda têm valor como descoberta, mas não devem ser equipadas.':'Os melhores itens seguem a identidade da sua classe e a raridade do bioma onde foram encontrados.'},
  {keys:['multiplayer','jogador','online'],answer:'Os ecos que você vê caminhando pelo mundo são outros viajantes conectados à mesma sala de Astraeon. O chat mundial permite conversar com eles.'},
  {keys:['ajuda','dica'],answer:`Se eu fosse você, manteria Fôlego para fugir, espaço livre na mochila e atenção ao mapa. ${city?.name||'As cidades'} são pontos seguros para se orientar.`}
];for(const r of rules)if(r.keys.some(k=>text.includes(k))){npc.memory.push({q:raw,a:r.answer});npc.memory=npc.memory.slice(-6);return r.answer;}const extras=[`A Convergência reage a viajantes fortes. No nível ${p?.level||1}, ainda há muito a descobrir.`,`Ouvi rumores de criaturas raras além dos portões de ${city?.name||'Astraeon'}.`,`Nem toda resposta está em combate. Observe as estradas, os climas e os habitantes das cidades.`,`Posso não conhecer todos os segredos, mas conheço estas ruas melhor que muitos aventureiros.`];const answer=extras[Math.floor(Math.random()*extras.length)];npc.memory.push({q:raw,a:answer});npc.memory=npc.memory.slice(-6);return answer;}
function ensureMobileButton(){const actions=document.querySelector('.touch-actions');if(!actions||document.querySelector('#touchNpcTalk'))return;const btn=document.createElement('button');btn.id='touchNpcTalk';btn.className='touch-npc-talk';btn.innerHTML='☏<small>Falar</small>';btn.addEventListener('pointerdown',e=>{e.preventDefault();const game=global.astraeon,n=game&&nearest(game,82);if(n)openDialogue(game,n);else game?.toast?.('Aproxime-se de um NPC para conversar.');});actions.prepend(btn);}
function install(){const game=global.astraeon;if(!game||game.npcsV4Installed)return;game.npcsV4Installed=true;createDialogue();ensureMobileButton();buildNpcs(game);const originalUpdate=game.update.bind(game);game.update=function(dt){originalUpdate(dt);updateNpcs(this,dt);};const originalDrawMobs=game.drawMobs.bind(game);game.drawMobs=function(ctx){originalDrawMobs(ctx);drawNpcs(this,ctx);};const originalStart=game.startNew.bind(game);game.startNew=function(){originalStart();buildNpcs(this);};const originalContinue=game.continueGame.bind(game);game.continueGame=function(){originalContinue();if(this.running)buildNpcs(this);};let holdE=null;global.addEventListener('keydown',e=>{if(e.key.toLowerCase()!=='e'||e.repeat||!game.running||game.paused)return;if(global.AstraeonInputGuardV1?.blocksPanelHotkeys(e))return;const tag=document.activeElement?.tagName;if(['INPUT','TEXTAREA','SELECT'].includes(tag))return;const n=nearest(game,78);if(n){e.preventDefault();holdE=setTimeout(()=>{holdE=null;if(nearest(game,78)===n)openDialogue(game,n);},450);}});global.addEventListener('keyup',e=>{if(e.key.toLowerCase()==='e'&&holdE){clearTimeout(holdE);holdE=null;}});game.canvas?.addEventListener('pointerup',e=>{if(!game.running||game.paused)return;const n=nearest(game,82);if(!n)return;const r=game.canvas.getBoundingClientRect(),wx=(e.clientX-r.left)/(game.zoom||1)+game.camera.x,wy=(e.clientY-r.top)/(game.zoom||1)+game.camera.y;if(W.dist(wx,wy,n.x,n.y)<=30)openDialogue(game,n);});}
global.AstraeonNPCsV4={NPCS,install,nearest,openDialogue};
global.addEventListener('DOMContentLoaded',install);
})(window);
