(function(global){
'use strict';
const TILE=36,STORAGE='astraeon:v2:quests-v2';
const state={loaded:false,content:null,server:[],local:{},visited:new Set(),claiming:false};
const game=()=>global.astraeon,bus=()=>global.AstraeonEventBusV1,authority=()=>global.AstraeonAuthorityV1;
function readLocal(){try{return JSON.parse(localStorage.getItem(STORAGE)||'{}')||{};}catch(_){return{};}}
function saveLocal(){localStorage.setItem(STORAGE,JSON.stringify(state.local));}
function defs(){return state.content?.quests||[];}function progressFor(id){state.local[id]=state.local[id]||{status:'active',progress:{}};return state.local[id];}
function availableLocal(){for(const q of defs()){const row=state.local[q.questId];if(row?.status==='claimed')continue;if(q.prerequisiteQuest&&state.local[q.prerequisiteQuest]?.status!=='claimed')continue;return{...q,status:row?.status||'active',progress:row?.progress||{}};}return null;}
function active(){if(authority()?.isActive?.()){const rows=state.server||[];return rows.find(q=>q.status==='active')||rows.find(q=>q.status==='completed')||rows.at(-1)||null;}return availableLocal();}
function objectiveDone(obj,progress){return Number(progress?.[obj.id]||0)>=Number(obj.count||1);}
function updateLocalCompletion(q,row){if(q.objectives.every(obj=>objectiveDone(obj,row.progress))&&row.status==='active'){row.status='completed';game()?.toast?.(`Missão concluída: ${q.title}`);saveLocal();}render();}
function applyLocalEvent(event){if(authority()?.isActive?.()||!state.loaded)return;const q=availableLocal();if(!q||q.status!=='active')return;const row=progressFor(q.questId);for(const obj of q.objectives){const match=(obj.type==='kill'&&event.type==='kill'&&obj.target===event.target)||(obj.type==='kill_biome'&&event.type==='kill'&&obj.target===event.biome)||(obj.type==='visit'&&event.type==='visit'&&obj.target===event.target)||(obj.type==='collect'&&event.type==='collect'&&obj.target===event.target);if(match)row.progress[obj.id]=Math.min(Number(obj.count||1),Number(row.progress[obj.id]||0)+Number(event.count||1));}saveLocal();updateLocalCompletion(q,row);}
function itemClone(item){const api=global.AstraeonItems;return api?.cloneItem?.(item.itemId,{qty:item.quantity||1})||{id:item.itemId,name:item.itemId,type:'material',rarity:'rare',qty:item.quantity||1};}
function claimLocal(q){const row=progressFor(q.questId);if(row.status!=='completed')return;const g=game(),rewards=q.rewards||{};if(Number(rewards.xp)>0)g?.gainXp?.(Number(rewards.xp));g.gold=(Number(g.gold)||0)+Number(rewards.gold||0);for(const item of rewards.items||[])g.inventory?.push?.(itemClone(item));row.status='claimed';saveLocal();g?.save?.();g?.toast?.(`Recompensa recebida: ${q.title}`);render();}
async function claim(){const q=active();if(!q||q.status!=='completed'||state.claiming)return;state.claiming=true;try{if(authority()?.isActive?.())await authority().intent('quest_claim',{questId:q.questId});else claimLocal(q);}finally{state.claiming=false;}}
function objectiveLabel(obj,progress){const labels={kill:'Derrote',kill_biome:'Derrote no bioma',visit:'Visite',collect:'Colete'};return`${labels[obj.type]||obj.type} ${obj.target} · ${Math.min(Number(progress?.[obj.id]||0),Number(obj.count||1))}/${obj.count||1}`;}
function render(){const q=active(),card=document.querySelector('.quest-card'),text=document.querySelector('#questText'),fill=document.querySelector('#questFill');if(!card||!text||!fill)return;if(!q){text.textContent='Bosque de Lúmen concluído.';fill.style.width='100%';return;}const progress=q.progress||{},done=q.objectives?.filter(obj=>objectiveDone(obj,progress)).length||0,total=q.objectives?.length||1;text.innerHTML=`<b>${q.title}</b><br><small>${(q.objectives||[]).map(obj=>objectiveLabel(obj,progress)).join(' · ')}</small>`;fill.style.width=`${Math.round(done/total*100)}%`;let button=card.querySelector('#questClaimV2');if(q.status==='completed'){if(!button){button=document.createElement('button');button.id='questClaimV2';button.type='button';button.className='ghost-btn';button.textContent='Resgatar recompensa';card.appendChild(button);button.addEventListener('click',claim);}button.hidden=false;}else if(button)button.hidden=true;}
function checkVisits(){if(!state.loaded||authority()?.isActive?.())return;const g=game(),p=g?.player;if(!p)return;const q=availableLocal();if(q?.status==='active'){const row=progressFor(q.questId);let changed=false;for(const obj of q.objectives||[]){if(obj.type!=='collect')continue;const count=(g.inventory||[]).filter(item=>item?.id===obj.target).reduce((sum,item)=>sum+Math.max(1,Number(item.qty||item.quantity||1)),0);const next=Math.min(Number(obj.count||1),count);if(Number(row.progress[obj.id]||0)!==next){row.progress[obj.id]=next;changed=true;}}if(changed){saveLocal();updateLocalCompletion(q,row);}}for(const [key,place] of Object.entries(state.content?.places||{})){if(state.visited.has(key))continue;const center={x:Number(place.x)*TILE+TILE/2,y:Number(place.y)*TILE+TILE/2};if(Math.hypot(p.x-center.x,p.y-center.y)<=Number(place.radius||3)*TILE){state.visited.add(key);applyLocalEvent({type:'visit',target:key,count:1});}}}
async function load(){try{const r=await fetch('data/quests/lumen.json',{cache:'no-store'});if(!r.ok)throw new Error(`HTTP ${r.status}`);state.content=await r.json();state.local=readLocal();state.loaded=true;render();}catch(error){console.warn('[Astraeon Quests V2]',error);}}
function install(){bus()?.on?.('authority:snapshot',({snapshot})=>{state.server=Array.isArray(snapshot?.quests)?snapshot.quests:[];render();});bus()?.on?.('combat:mob-kill:after',ctx=>{const mob=ctx?.args?.[0];if(mob)applyLocalEvent({type:'kill',target:mob.type,biome:mob.biome,count:1});});bus()?.on?.('game:update:after',checkVisits);void load();}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',install,{once:true});else install();global.AstraeonQuestsV2={state,render,claim,applyLocalEvent};
})(window);
