(function(global){
'use strict';
const C=global.AstraeonSkillsCatalogV1,W=global.AstraeonWorld,$=s=>document.querySelector(s),$$=s=>Array.from(document.querySelectorAll(s));
if(!C||!W)return;
const state={installed:false,learned:new Set(),loadout:Array(5).fill(null),earned:3,spent:0,available:3,serverLevel:1,serverGold:0,remote:false,remoteCharacter:null,purchasing:false,view:null,hold:null,drag:null,lastCharacter:null,syncingCharacter:null};
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const game=()=>global.astraeon,mp=()=>global.AstraeonMultiplayerV4?.state||null,characterId=()=>global.AstraeonCharactersV6?.activeCharacterId||null;
function ensureToastLayer(){const toast=$('#toast');if(toast&&toast.parentElement!==document.body)document.body.appendChild(toast);}
function classGroup(){return C.CLASSES[game()?.player?.classId||game()?.selectedClass||'Warrior']||C.CLASSES.Warrior;}
function localState(){try{return JSON.parse(localStorage.getItem(W.STORAGE_SAVE)||'null')?.skillsV1||null;}catch(_){return null;}}
function recompute(){if(state.remote&&state.remoteCharacter===characterId())return;const level=Math.max(1,Number(game()?.player?.level)||1);state.earned=level*3;state.spent=C.list(game()?.player?.classId).filter(s=>state.learned.has(s.id)).reduce((n,s)=>n+s.cost,0);state.available=Math.max(0,state.earned-state.spent);}
function saveLocal(){const g=game();if(!g?.player)return;recompute();try{const raw=JSON.parse(localStorage.getItem(W.STORAGE_SAVE)||'{}');raw.skillsV1={version:1,learned:[...state.learned],loadout:[...state.loadout]};localStorage.setItem(W.STORAGE_SAVE,JSON.stringify(raw));}catch(_){} }
function installLocal(raw,reset=false){const allowed=new Set(C.list(game()?.player?.classId).map(s=>s.id)),source=reset?null:raw||localState();state.remote=false;state.remoteCharacter=null;state.serverLevel=Math.max(1,Number(game()?.player?.level)||1);state.serverGold=0;state.learned=new Set((source?.learned||[]).filter(id=>allowed.has(id)));state.loadout=Array.from({length:5},(_,i)=>{const id=source?.loadout?.[i];return allowed.has(id)&&state.learned.has(id)?id:null;});recompute();refresh();}
function applyRemote(data,expectedCharacter=characterId()){const responseCharacter=String(data?.characterId||'');if(!data||!expectedCharacter||characterId()!==expectedCharacter||responseCharacter!==String(expectedCharacter))return false;state.learned=new Set((data.learned||[]).map(x=>x.skillId));state.loadout=Array(5).fill(null);for(const row of data.learned||[])if(Number.isInteger(row.slot)&&row.slot>=0&&row.slot<5)state.loadout[row.slot]=row.skillId;state.serverLevel=Math.max(1,Number(data.level)||1);state.serverGold=Math.max(0,Number(data.gold)||0);state.remote=true;state.remoteCharacter=expectedCharacter;state.earned=Number(data.earned)||0;state.spent=Number(data.spent)||0;state.available=Number(data.available)||0;saveLocal();refresh();return true;}
async function syncRemote(requestedCharacter=characterId()){const client=mp()?.client,id=requestedCharacter;if(!client||!mp()?.session||!id)return false;state.syncingCharacter=id;try{const{data,error}=await client.rpc('get_astraeon_skill_state',{target_character:id});if(error)throw error;return applyRemote(data,id);}catch(error){console.warn('[Astraeon Skills] sync',error?.message||error);return false;}finally{if(state.syncingCharacter===id)state.syncingCharacter=null;}}
function selectCharacter(id,{fresh=false}={}){if(!id)return false;state.lastCharacter=id;state.remoteCharacter=null;cancelInteraction();hideTooltip();installLocal(fresh?null:localState(),fresh);void syncRemote(id);return true;}
function createUi(){if($('#skillsPanel'))return;const root=document.createElement('section');root.id='skillsPanel';root.className='skills-panel skills-player-panel hidden';root.setAttribute('aria-label','Grimório de habilidades do personagem');root.innerHTML=`<div class="skills-card skills-player-card"><header class="skills-head"><div class="skills-brand"><span class="skills-emblem">✦</span><div><small>GRIMÓRIO DO VIAJANTE</small><h2>Minhas Habilidades</h2><p>Organize somente os poderes aprendidos e monte sua barra de combate.</p></div></div><div class="skills-wallet"><span><b id="skillsPoints">3</b> pontos livres</span><kbd>H</kbd><button id="skillsClose" aria-label="Fechar">×</button></div></header><div class="skills-master-notice active"><b>Configuração do HUD</b><span>Arraste uma habilidade aprendida até um dos cinco espaços abaixo.</span></div><main id="skillsLibrary" class="skills-domains skills-library"></main><footer class="skills-loadout-shell"><div class="skills-loadout-head"><div><small>HUD DE SKILLS</small><b>Barra equipada</b></div><span>Arraste para substituir · teclas 1–5 para usar</span></div><div id="skillsLoadout" class="skills-loadout" aria-label="Slots do HUD de habilidades"></div><div class="skills-footer"><span>Segure por 1 segundo para ver os detalhes. Clique para equipar com teclado.</span><button id="skillsPlayerClose">Fechar grimório</button></div></footer></div>`;document.body.appendChild(root);
 const merchant=document.createElement('section');merchant.id='skillMerchantPanel';merchant.className='skills-panel skills-merchant-panel hidden';merchant.setAttribute('aria-label','Centro de habilidades de Maeron');merchant.innerHTML=`<div class="skills-master-workspace"><section class="skills-card skills-player-card skills-companion-card" aria-label="Habilidades compradas do personagem"><header class="skills-head"><div class="skills-brand"><span class="skills-emblem">✦</span><div><small>GRIMÓRIO DO VIAJANTE</small><h2>Minhas Habilidades</h2><p>Arraste seus poderes comprados para a barra de combate.</p></div></div><div class="skills-wallet"><span><b id="merchantPlayerSkillsPoints">3</b> pontos livres</span><kbd>H</kbd></div></header><div class="skills-master-notice active"><b>Equipamento</b><span>Arraste uma skill aprendida até um dos cinco slots do HUD.</span></div><main id="merchantPlayerSkillsLibrary" class="skills-domains skills-library"></main><footer class="skills-loadout-shell"><div class="skills-loadout-head"><div><small>HUD DE SKILLS</small><b>Barra equipada</b></div><span>Arraste para substituir</span></div><div id="merchantPlayerSkillsLoadout" class="skills-loadout" aria-label="Slots do HUD ao visitar o Mestre"></div><div class="skills-footer"><span>Skills já compradas · teclas 1–5</span></div></footer></section><section class="skills-card skills-merchant-card" aria-label="Vendas do Mestre de Habilidades"><header class="skills-head"><div class="skills-brand"><span class="skills-emblem skills-master-emblem">M</span><div><small>MAERON · MESTRE DE HABILIDADES</small><h2>Mestre das Habilidades</h2><p>Compre e desbloqueie novos poderes para sua classe.</p></div></div><div class="skills-wallet"><span><b id="merchantSkillsPoints">3</b> pontos</span><span><b id="merchantSkillsGold">0</b> ouro</span><button id="skillMerchantClose" aria-label="Fechar">×</button></div></header><div class="skills-master-notice active"><b>Catálogo do Mestre</b><span>Selecione uma habilidade disponível para confirmar a compra.</span></div><main id="merchantSkillsDomains" class="skills-domains"></main><footer class="skills-footer"><span>Segure uma habilidade por 1 segundo para inspecionar seus efeitos.</span><button id="skillMerchantFooterClose">Sair da oficina</button></footer></section></div>`;document.body.appendChild(merchant);
 const tip=document.createElement('aside');tip.id='skillTooltip';tip.className='skill-tooltip hidden';document.body.appendChild(tip);
 const confirm=document.createElement('section');confirm.id='skillConfirm';confirm.className='skill-confirm hidden';confirm.innerHTML='<div class="skill-confirm-card"><span id="skillConfirmKicker">MESTRE DE HABILIDADES</span><h3 id="skillConfirmTitle">Confirmar</h3><p id="skillConfirmText"></p><div id="skillConfirmSlots" class="skill-confirm-slots hidden"></div><div class="skill-confirm-actions"><button id="skillConfirmCancel">Cancelar</button><button id="skillConfirmAccept">Confirmar</button></div></div>';document.body.appendChild(confirm);
 $('#skillsClose').onclick=close;$('#skillsPlayerClose').onclick=close;$('#skillMerchantClose').onclick=close;$('#skillMerchantFooterClose').onclick=close;$('#skillConfirmCancel').onclick=()=>confirm.classList.add('hidden');root.addEventListener('pointerdown',e=>onSkillPointerDown(e,'player'));merchant.addEventListener('pointerdown',e=>onSkillPointerDown(e,e.target.closest('.skill-node')?.dataset.skillMode||'merchant'));document.addEventListener('pointermove',onSkillPointerMove,{passive:false});document.addEventListener('pointerup',onSkillPointerUp);document.addEventListener('pointercancel',cancelInteraction);document.addEventListener('pointerdown',e=>{if(!e.target.closest('#skillTooltip,.skill-node'))hideTooltip();});
 const utility=$('.utility-stack');if(utility&&!$('#skillsBtn')){const b=document.createElement('button');b.id='skillsBtn';b.className='icon-btn skills-launcher';b.title='Minhas habilidades (H)';b.innerHTML='H';b.onclick=openPlayer;utility.prepend(b);}const touch=$('#mobileControls .touch-actions');if(touch&&!$('#touchSkills')){const b=document.createElement('button');b.id='touchSkills';b.innerHTML='✦<small>Skills</small>';b.onpointerdown=e=>{e.preventDefault();openPlayer();};touch.prepend(b);}
}
function playerDomainsHtml(group){const learnedCount=state.learned.size;if(!learnedCount)return'<div class="skills-empty-state"><span>✦</span><h3>Seu grimório está vazio</h3><p>Compre seu primeiro poder com Maeron para começar a montar o HUD.</p></div>';return group.domains.map(domain=>{const learned=domain.skills.filter(skill=>state.learned.has(skill.id));return `<section class="skill-domain" style="--domain:${domain.color}"><header><span>${esc(domain.name)}</span><p>${esc(domain.summary)}</p><em>${learned.length}/10 aprendidas</em></header><div class="skill-path skill-owned-path">${learned.length?learned.map(skill=>skillHtml(skill,domain,'player')).join(''):'<div class="skills-domain-empty">Nenhuma habilidade deste domínio foi aprendida.</div>'}</div></section>`;}).join('');}
function purchaseLevel(){return Math.max(1,Number(game()?.player?.level)||1,state.remote?state.serverLevel:1);}
function purchaseGold(){return state.remote?state.serverGold:Math.max(0,Number(game()?.gold)||0);}
function eligibility(skill){return C.purchaseEligibility({skill,level:purchaseLevel(),available:state.available,gold:purchaseGold(),learned:state.learned});}
function render(){const g=game();if(!g?.player)return;recompute();const group=classGroup(),playerDomains=playerDomainsHtml(group);$('#skillsPoints').textContent=state.available;$('#merchantPlayerSkillsPoints').textContent=state.available;$('#merchantSkillsPoints').textContent=state.available;$('#merchantSkillsGold').textContent=purchaseGold().toLocaleString('pt-BR');$('#skillsLibrary').innerHTML=playerDomains;$('#merchantPlayerSkillsLibrary').innerHTML=playerDomains;
 $('#merchantSkillsDomains').innerHTML=group.domains.map(domain=>`<section class="skill-domain merchant-domain" style="--domain:${domain.color}"><header><span>${esc(domain.name)}</span><p>${esc(domain.summary)}</p><em>${domain.skills.filter(s=>state.learned.has(s.id)).length}/10 adquiridas</em></header><div class="skill-path merchant-skill-grid">${domain.skills.map(skill=>skillHtml(skill,domain,'merchant')).join('')}</div></section>`).join('');renderLoadout('#skillsLoadout');renderLoadout('#merchantPlayerSkillsLoadout');updateHotbar();}
function skillHtml(skill,domain,mode){const learned=state.learned.has(skill.id),equipped=state.loadout.indexOf(skill.id),check=learned?{ok:false,reason:'skill_already_learned'}:eligibility(skill),status=learned?(mode==='merchant'?'Adquirida':equipped>=0?`Equipada · ${equipped+1}`:'Arraste ao HUD'):check.ok?`${skill.cost} pts · disponível`:check.reason==='skill_level_required'?`Nv. ${skill.level} · atual ${purchaseLevel()}`:check.reason==='skill_points_insufficient'?`${skill.cost} pts · faltam ${Math.max(0,skill.cost-state.available)}`:check.reason==='skill_domain_incomplete'?'Complete as 9 anteriores':check.reason==='skill_gold_insufficient'?'5 KK ouro necessários':'Bloqueada';return `<button class="skill-node ${learned?'learned':'locked'} ${check.ok?'purchasable':''} ${equipped>=0?'equipped':''} ${skill.ultimate?'ultimate':''} ${mode==='player'?'skill-draggable':''}" data-skill-id="${skill.id}" data-skill-mode="${mode}" data-purchase-state="${esc(check.reason||'available')}" style="--domain:${domain.color}" aria-label="${esc(skill.name)}"><i>${skill.tier}</i><b>${esc(skill.name)}</b><span>${status}</span>${skill.gold?'<em>5 KK</em>':''}</button>`;}
function renderLoadout(selector){const host=$(selector);if(!host)return;host.innerHTML=state.loadout.map((id,i)=>{const skill=C.get(id);return `<button class="skill-loadout-slot ${skill?'filled':''}" data-loadout-slot="${i}" style="--skill-color:${skill?.domainColor||'#526168'}" aria-label="Slot ${i+1}${skill?`: ${esc(skill.name)}`:': vazio'}"><kbd>${i+1}</kbd><i>${skill?esc(skill.name.slice(0,1)):'+'}</i><span>${skill?esc(skill.name):'Solte aqui'}</span><small>${skill?'Equipada':'Slot vazio'}</small></button>`;}).join('');}
function openPlayer(){if(!game()?.running)return;createUi();ensureToastLayer();state.view='player';$('#skillMerchantPanel').classList.add('hidden');render();$('#skillsPanel').classList.remove('hidden');document.body.classList.add('skills-overlay-open');game().paused=true;}
function openMerchant(){if(!game()?.running)return;createUi();ensureToastLayer();state.view='merchant';$('#skillsPanel').classList.add('hidden');render();$('#skillMerchantPanel').classList.remove('hidden');document.body.classList.add('skills-overlay-open');game().paused=true;void syncRemote();}
function open(merchant=false){return merchant?openMerchant():openPlayer();}
function close(){cancelInteraction();hideTooltip();$('#skillsPanel')?.classList.add('hidden');$('#skillMerchantPanel')?.classList.add('hidden');$('#skillConfirm')?.classList.add('hidden');document.body.classList.remove('skills-overlay-open');if(game()?.running)game().paused=false;state.view=null;}
function onSkillPointerDown(event,mode){const node=event.target.closest('.skill-node');if(!node)return;const skill=C.get(node.dataset.skillId);if(!skill)return;event.preventDefault();cancelInteraction();state.hold={mode,skill,node,pointerId:event.pointerId,x:event.clientX,y:event.clientY,timer:setTimeout(()=>{showTooltip(skill,node);state.hold=null;},1000)};}
function onSkillPointerMove(event){const hold=state.hold;if(state.drag){event.preventDefault();moveDragGhost(event.clientX,event.clientY);highlightDropSlot(event.clientX,event.clientY);return;}if(!hold||hold.pointerId!==event.pointerId)return;const distance=Math.hypot(event.clientX-hold.x,event.clientY-hold.y);if(distance<8)return;if(hold.mode==='player'&&state.learned.has(hold.skill.id)){clearTimeout(hold.timer);beginDrag(hold.skill,event.clientX,event.clientY);state.hold=null;event.preventDefault();}else{clearTimeout(hold.timer);state.hold=null;}}
function onSkillPointerUp(event){if(state.drag){const slot=document.elementFromPoint(event.clientX,event.clientY)?.closest?.('.skill-loadout-slot');const skill=state.drag.skill;finishDrag();if(slot)void equip(skill,Number(slot.dataset.loadoutSlot));return;}const hold=state.hold;if(!hold||hold.pointerId!==event.pointerId)return;clearTimeout(hold.timer);const distance=Math.hypot(event.clientX-hold.x,event.clientY-hold.y),skill=hold.skill,mode=hold.mode;state.hold=null;if(distance<9)activate(skill,mode);}
function cancelInteraction(){if(state.hold)clearTimeout(state.hold.timer);state.hold=null;finishDrag();}
function beginDrag(skill,x,y){hideTooltip();const ghost=document.createElement('div');ghost.className='skill-drag-ghost';ghost.style.setProperty('--skill-color',skill.domainColor);ghost.innerHTML=`<i>${esc(skill.name.slice(0,1))}</i><span>${esc(skill.name)}</span>`;document.body.appendChild(ghost);state.drag={skill,ghost};moveDragGhost(x,y);document.body.classList.add('skill-dragging');}
function moveDragGhost(x,y){if(!state.drag)return;state.drag.ghost.style.transform=`translate3d(${x+14}px,${y+14}px,0)`;}
function highlightDropSlot(x,y){$$('.skill-loadout-slot.drop-target').forEach(el=>el.classList.remove('drop-target'));document.elementFromPoint(x,y)?.closest?.('.skill-loadout-slot')?.classList.add('drop-target');}
function finishDrag(){if(!state.drag)return;state.drag.ghost.remove();state.drag=null;document.body.classList.remove('skill-dragging');$$('.skill-loadout-slot.drop-target').forEach(el=>el.classList.remove('drop-target'));}
function showTooltip(skill,node){if(!skill)return;const tip=$('#skillTooltip'),r=node.getBoundingClientRect();tip.innerHTML=`<header><i style="--domain:${skill.domainColor}">${skill.tier}</i><div><small>${esc(skill.domainName)}</small><b>${esc(skill.name)}</b></div></header><p>${esc(skill.description)}</p><dl><div><dt>Nível</dt><dd>${skill.level}</dd></div><div><dt>Custo</dt><dd>${skill.cost} pts</dd></div><div><dt>Mana</dt><dd>${manaCost(skill)}</dd></div><div><dt>Recarga</dt><dd>${cooldown(skill)}s</dd></div></dl>${skill.gold?'<strong>Ascensão: 5.000.000 de ouro + domínio completo</strong>':''}`;tip.classList.remove('hidden');const w=tip.offsetWidth,h=tip.offsetHeight;tip.style.left=`${Math.max(10,Math.min(innerWidth-w-10,r.right+12))}px`;tip.style.top=`${Math.max(10,Math.min(innerHeight-h-10,r.top))}px`;}
function hideTooltip(){$('#skillTooltip')?.classList.add('hidden');}
function activate(skill,mode){hideTooltip();if(mode==='player'){if(state.learned.has(skill.id))showEquip(skill);return;}if(state.learned.has(skill.id)){game()?.toast?.('Esta habilidade já foi adquirida. Equipe-a no grimório H.');return;}const check=eligibility(skill);if(!check.ok){game()?.toast?.(errorMessage(check.reason,skill));return;}showPurchase(skill);}
function modal(title,text,accept){const box=$('#skillConfirm');$('#skillConfirmTitle').textContent=title;$('#skillConfirmText').textContent=text;$('#skillConfirmSlots').classList.add('hidden');const button=$('#skillConfirmAccept');button.textContent='Confirmar compra';button.onclick=()=>{box.classList.add('hidden');void accept();};box.classList.remove('hidden');}
function showPurchase(skill){const suffix=skill.gold?' e 5.000.000 de ouro':'';modal(`Aprender ${skill.name}?`,`Esta habilidade consome ${skill.cost} pontos${suffix}. ${skill.description}`,()=>purchase(skill));}
function showEquip(skill){const box=$('#skillConfirm'),slots=$('#skillConfirmSlots');$('#skillConfirmTitle').textContent=`Equipar ${skill.name}`;$('#skillConfirmText').textContent='Escolha um dos cinco espaços da barra de habilidades.';slots.innerHTML=state.loadout.map((id,i)=>`<button data-equip-slot="${i}"><kbd>${i+1}</kbd><span>${esc(C.get(id)?.name||'Vazio')}</span></button>`).join('');slots.classList.remove('hidden');$('#skillConfirmAccept').textContent='Cancelar';$('#skillConfirmAccept').onclick=()=>box.classList.add('hidden');slots.querySelectorAll('[data-equip-slot]').forEach(b=>b.onclick=()=>{box.classList.add('hidden');void equip(skill,Number(b.dataset.equipSlot));});box.classList.remove('hidden');}
function errorMessage(error,skill){const m=[error?.code,error?.message,error?.details,error?.hint,error].filter(Boolean).join(' ');if(m.includes('level_required'))return`Nível ${skill?.level||'?'} necessário · o servidor reconheceu nível ${state.remote?state.serverLevel:purchaseLevel()}.`;if(m.includes('points_insufficient'))return`São necessários ${skill?.cost||'?'} pontos · você possui ${state.available}.`;if(m.includes('domain_incomplete'))return'Aprenda as nove habilidades anteriores deste domínio.';if(m.includes('gold_insufficient'))return`São necessários 5.000.000 de ouro autoritativo · saldo ${purchaseGold().toLocaleString('pt-BR')}.`;if(m.includes('already'))return'Habilidade já aprendida.';if(m.includes('wrong_class'))return'Esta habilidade pertence a outra classe.';if(m.includes('access_denied'))return'Este personagem não pertence à conta conectada.';if(/PGRST202|schema cache|does not exist|Could not find the function/i.test(m))return'O servidor ainda não recebeu a atualização do sistema de skills.';if(/fetch|network|timeout|offline/i.test(m))return'Falha de conexão com o Mestre de Habilidades. Tente novamente.';return'A compra foi recusada pelo servidor. As habilidades deste personagem foram sincronizadas novamente.';}
async function purchase(skill){if(state.purchasing)return;state.purchasing=true;const client=mp()?.client,id=characterId();try{if(client&&mp()?.session&&id){const saved=await global.AstraeonCharactersV6?.saveCharacterNow?.();if(saved===false){game().toast('Não foi possível sincronizar o nível atual. Tente salvar novamente.');return;}if(characterId()!==id){game().toast('O personagem ativo mudou. Abra novamente o Mestre de Habilidades.');return;}const{data,error}=await client.rpc('purchase_astraeon_skill',{target_character:id,target_skill:skill.id});if(error){await syncRemote(id);game().toast(errorMessage(error,skill));return;}if(!applyRemote(data,id)){game().toast('A compra não foi aplicada porque o personagem ativo mudou.');return;}if(skill.gold)game().gold=Math.max(0,Number(data.gold)||0);}else{recompute();const check=eligibility(skill);if(!check.ok){game().toast(errorMessage(check.reason,skill));return;}state.learned.add(skill.id);if(skill.gold)game().gold-=skill.gold;saveLocal();refresh();}game().toast(`${skill.name} aprendida com sucesso.`);}catch(error){if(id)await syncRemote(id);game()?.toast?.(errorMessage(error,skill));}finally{state.purchasing=false;}}
async function equip(skill,slot){const client=mp()?.client,id=characterId();if(client&&mp()?.session&&id){const{data,error}=await client.rpc('equip_astraeon_skill',{target_character:id,target_skill:skill.id,target_slot:slot});if(error){game().toast('Não foi possível equipar a habilidade.');return;}if(!applyRemote(data,id)){game().toast('O personagem ativo mudou antes de equipar a habilidade.');return;}}else{state.loadout=state.loadout.map(x=>x===skill.id?null:x);state.loadout[slot]=skill.id;saveLocal();refresh();}game().toast(`${skill.name} equipada no slot ${slot+1}.`);}
function manaCost(skill){return Number(skill?.mana)||0;}
function cooldown(skill){return Number(skill?.cooldown)||30;}
function offensiveSkill(skill){const mechanics=skill?.mechanics||{};return Number(skill?.power)>0||['trailDamage','returnHit','delayedHit','originBlast','exitBlast','rayPower','aftershockPower'].some(key=>Number(mechanics[key])>0);}
function cast(g,index){const skill=C.get(state.loadout[index]);if(!skill||!state.learned.has(skill.id)){g.toast('Nenhuma habilidade equipada neste espaço. Abra o grimório com H.');return;}if(offensiveSkill(skill)&&global.AstraeonProductionV6?.canPlayerAttack&&!global.AstraeonProductionV6.canPlayerAttack(g)){g.toast('Habilidades ofensivas são bloqueadas dentro da área protegida.');return;}if(g.cooldowns[index]>0)return;const cost=manaCost(skill);if(g.player.mana<cost){g.toast('Mana insuficiente.');return;}const result=global.AstraeonSkillEffectsV2?.cast?.(g,skill);if(!result?.ok){g.toast(result?.reason||'A habilidade não encontrou um alvo válido.');return;}global.AstraeonProductionV6?.activity?.();g.player.mana-=cost;g.cooldowns[index]=cooldown(skill);g.beep(590+skill.visualVariant*19,.08,.035);refresh();}
function updateHotbar(){const g=game();if(!g)return;$$('#hotbar .skill').forEach((button,i)=>{const skill=C.get(state.loadout[i]);button.classList.toggle('skill-empty',!skill);button.classList.toggle('skill-equipped',!!skill);button.title=skill?`${skill.name} — ${skill.description}`:`Slot ${i+1} vazio · H para abrir Domínios`;let glyph=button.querySelector('.skill-glyph');if(!glyph){glyph=document.createElement('span');glyph.className='skill-glyph';button.insertBefore(glyph,button.querySelector('.cd'));}glyph.textContent=skill?skill.name.slice(0,1):'·';button.style.setProperty('--skill-color',skill?.domainColor||'#6d7480');});$$('#mobileControls [data-skill]').forEach((button,i)=>{const skill=C.get(state.loadout[i]);button.title=skill?.name||'Slot vazio';button.style.setProperty('--skill-color',skill?.domainColor||'#6d7480');});}
function refresh(){if(($('#skillsPanel')&&!$('#skillsPanel').classList.contains('hidden'))||($('#skillMerchantPanel')&&!$('#skillMerchantPanel').classList.contains('hidden')))render();updateHotbar();}
function installHooks(g){if(g.skillsV1Installed)return;g.skillsV1Installed=true;const start=g.startNew.bind(g),cont=g.continueGame.bind(g),save=g.save.bind(g),gain=g.gainXp.bind(g),update=g.update.bind(g);g.startNew=function(){const r=start();if(this.player){installLocal(null,true);saveLocal();setTimeout(syncRemote,300);}return r;};g.continueGame=function(){const raw=localState(),r=cont();if(this.player){installLocal(raw,false);setTimeout(syncRemote,300);}return r;};g.save=function(){const r=save();saveLocal();return r;};g.gainXp=function(amount){const before=this.player?.level||1,r=gain(amount),after=this.player?.level||before;if(after>before){recompute();this.toast(`Nível ${after}! +${(after-before)*3} pontos de skill.`);refresh();}return r;};g.castSkill=function(index){if(!this.running||this.paused)return;cast(this,Number(index));};g.update=function(dt){global.AstraeonSkillEffectsV2?.beforeUpdate?.(this,dt);try{return update(dt);}finally{global.AstraeonSkillEffectsV2?.afterUpdate?.(this,dt);}};}
async function adminAllSkills(){const client=mp()?.client,id=characterId();if(!client||!id)return game()?.toast?.('Comando disponível apenas online.');const{data:isAdmin,error:aerr}=await client.rpc('astraeon_is_admin');if(aerr||isAdmin!==true)return game()?.toast?.('Comando exclusivo para administradores.');const{data,error}=await client.rpc('admin_unlock_all_astraeon_skills',{target_character:id});if(error){game().toast('Não foi possível liberar as habilidades.');return;}if(!applyRemote(data,id)){game().toast('O personagem ativo mudou durante o comando.');return;}game().toast('ADM: todas as habilidades da classe foram aprendidas.');}
function installAdminCommand(){const wait=()=>{const form=$('#onlineChatForm'),input=$('#onlineChatInput');if(!form||!input){setTimeout(wait,150);return;}if(form.dataset.skillAdminCommand)return;form.dataset.skillAdminCommand='1';form.addEventListener('submit',event=>{if(String(input.value||'').trim().toLowerCase()!=='!allskill')return;event.preventDefault();event.stopImmediatePropagation();input.value='';void adminAllSkills();},true);};wait();}
function installKeyboard(){global.addEventListener('keydown',event=>{if((event.code!=='KeyH'&&event.key.toLowerCase()!=='h')||event.repeat)return;if(global.AstraeonInputGuardV1?.blocksPanelHotkeys(event))return;const active=document.activeElement;if(active?.closest('input,textarea,select,[contenteditable="true"],#onlineChat,#npcDialogue'))return;if(!game()?.running)return;event.preventDefault();event.stopImmediatePropagation();if($('#skillsPanel')?.classList.contains('hidden')!==false)open(false);else close();},true);}
function monitorCharacter(){setInterval(()=>{const id=characterId();if(!id){state.lastCharacter=null;return;}if(id!==state.lastCharacter){selectCharacter(id,{fresh:true});return;}if(state.remoteCharacter!==id&&state.syncingCharacter!==id)void syncRemote(id);},900);}
function install(){if(state.installed)return;const g=game();if(!g){setTimeout(install,80);return;}state.installed=true;createUi();installHooks(g);installKeyboard();installAdminCommand();monitorCharacter();const id=characterId();if(id)selectCharacter(id,{fresh:true});else installLocal(localState(),false);global.AstraeonSkillsV1={state,open,openPlayer,close,openMerchant,syncRemote,selectCharacter,adminAllSkills};}
if(document.readyState==='loading')global.addEventListener('DOMContentLoaded',install);else install();
})(window);
