(function(global){
'use strict';
const C=global.AstraeonSkillsCatalogV1,W=global.AstraeonWorld,$=s=>document.querySelector(s),$$=s=>Array.from(document.querySelectorAll(s));
if(!C||!W)return;
const state={installed:false,learned:new Set(),loadout:Array(5).fill(null),earned:3,spent:0,available:3,serverGold:0,merchant:false,activeDomain:null,hold:null,lastCharacter:null,syncing:false};
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const game=()=>global.astraeon,mp=()=>global.AstraeonMultiplayerV4?.state||null,characterId=()=>global.AstraeonCharactersV6?.activeCharacterId||null;
function classGroup(){return C.CLASSES[game()?.player?.classId||game()?.selectedClass||'Warrior']||C.CLASSES.Warrior;}
function localState(){try{return JSON.parse(localStorage.getItem(W.STORAGE_SAVE)||'null')?.skillsV1||null;}catch(_){return null;}}
function recompute(){const level=Math.max(1,Number(game()?.player?.level)||1);state.earned=level*3;state.spent=C.list(game()?.player?.classId).filter(s=>state.learned.has(s.id)).reduce((n,s)=>n+s.cost,0);state.available=Math.max(0,state.earned-state.spent);}
function saveLocal(){const g=game();if(!g?.player)return;recompute();try{const raw=JSON.parse(localStorage.getItem(W.STORAGE_SAVE)||'{}');raw.skillsV1={version:1,learned:[...state.learned],loadout:[...state.loadout]};localStorage.setItem(W.STORAGE_SAVE,JSON.stringify(raw));}catch(_){} }
function installLocal(raw,reset=false){const allowed=new Set(C.list(game()?.player?.classId).map(s=>s.id)),source=reset?null:raw||localState();state.learned=new Set((source?.learned||[]).filter(id=>allowed.has(id)));state.loadout=Array.from({length:5},(_,i)=>{const id=source?.loadout?.[i];return allowed.has(id)&&state.learned.has(id)?id:null;});recompute();refresh();}
function applyRemote(data){if(!data)return;state.learned=new Set((data.learned||[]).map(x=>x.skillId));state.loadout=Array(5).fill(null);for(const row of data.learned||[])if(Number.isInteger(row.slot)&&row.slot>=0&&row.slot<5)state.loadout[row.slot]=row.skillId;state.earned=Number(data.earned)||0;state.spent=Number(data.spent)||0;state.available=Number(data.available)||0;state.serverGold=Number(data.gold)||0;saveLocal();refresh();}
async function syncRemote(){const client=mp()?.client,id=characterId();if(!client||!mp()?.session||!id||state.syncing)return false;state.syncing=true;try{const{data,error}=await client.rpc('get_astraeon_skill_state',{target_character:id});if(error)throw error;applyRemote(data);return true;}catch(error){console.warn('[Astraeon Skills] sync',error?.message||error);return false;}finally{state.syncing=false;}}
function createUi(){if($('#skillsPanel'))return;const root=document.createElement('section');root.id='skillsPanel';root.className='skills-panel hidden';root.setAttribute('aria-label','Domínios de habilidades');root.innerHTML=`<div class="skills-card"><header class="skills-head"><div class="skills-brand"><span class="skills-emblem">✦</span><div><small>ARSENAL DA CONVERGÊNCIA</small><h2>Domínios de Habilidade</h2><p>Aprenda com o Mestre, especialize seu personagem e equipe cinco poderes.</p></div></div><div class="skills-wallet"><span><b id="skillsPoints">3</b> pontos</span><span><b id="skillsGold">0</b> ouro</span><kbd>H</kbd><button id="skillsClose" aria-label="Fechar">×</button></div></header><div id="skillsMasterNotice" class="skills-master-notice"></div><main id="skillsDomains" class="skills-domains"></main><footer class="skills-footer"><span id="skillsStatus">Segure uma habilidade por 1 segundo para inspecionar.</span><button id="skillsMerchantClose">Fechar painel</button></footer></div>`;document.body.appendChild(root);
 const tip=document.createElement('aside');tip.id='skillTooltip';tip.className='skill-tooltip hidden';document.body.appendChild(tip);
 const confirm=document.createElement('section');confirm.id='skillConfirm';confirm.className='skill-confirm hidden';confirm.innerHTML='<div class="skill-confirm-card"><span id="skillConfirmKicker">MESTRE DE HABILIDADES</span><h3 id="skillConfirmTitle">Confirmar</h3><p id="skillConfirmText"></p><div id="skillConfirmSlots" class="skill-confirm-slots hidden"></div><div class="skill-confirm-actions"><button id="skillConfirmCancel">Cancelar</button><button id="skillConfirmAccept">Confirmar</button></div></div>';document.body.appendChild(confirm);
 $('#skillsClose').onclick=close;$('#skillsMerchantClose').onclick=close;$('#skillConfirmCancel').onclick=()=>confirm.classList.add('hidden');root.addEventListener('pointerdown',onSkillPointerDown);root.addEventListener('pointerup',cancelHold);root.addEventListener('pointercancel',cancelHold);root.addEventListener('pointerleave',cancelHold);document.addEventListener('pointerdown',e=>{if(!e.target.closest('#skillTooltip,.skill-node'))hideTooltip();});
 const utility=$('.utility-stack');if(utility&&!$('#skillsBtn')){const b=document.createElement('button');b.id='skillsBtn';b.className='icon-btn skills-launcher';b.title='Domínios de habilidade (H)';b.innerHTML='H';b.onclick=()=>open(false);utility.prepend(b);}const touch=$('#mobileControls .touch-actions');if(touch&&!$('#touchSkills')){const b=document.createElement('button');b.id='touchSkills';b.innerHTML='✦<small>Skills</small>';b.onpointerdown=e=>{e.preventDefault();open(false);};touch.prepend(b);}
}
function isNearMaster(){const g=game(),n=g?.npcsV4?.find(x=>x.id==='skill-master');return !!(g?.player&&n&&W.dist(g.player.x,g.player.y,n.x,n.y)<=90);}
function canBuy(){return state.merchant||isNearMaster();}
function render(){const g=game();if(!g?.player)return;recompute();const group=classGroup();$('#skillsPoints').textContent=state.available;$('#skillsGold').textContent=(state.serverGold||g.gold||0).toLocaleString('pt-BR');const notice=$('#skillsMasterNotice');notice.classList.toggle('active',canBuy());notice.innerHTML=canBuy()?'<b>Mestre de Habilidades presente</b><span>Selecione uma habilidade bloqueada para aprendê-la.</span>':'<b>Modo de consulta</b><span>Visite o Mestre de Habilidades em Astralum para comprar novos poderes.</span>';
 $('#skillsDomains').innerHTML=group.domains.map(domain=>`<section class="skill-domain" style="--domain:${domain.color}"><header><span>${esc(domain.name)}</span><p>${esc(domain.summary)}</p><em>${domain.skills.filter(s=>state.learned.has(s.id)).length}/10 aprendidas</em></header><div class="skill-path">${domain.skills.map(skill=>skillHtml(skill,domain)).join('')}</div></section>`).join('');updateHotbar();}
function skillHtml(skill,domain){const learned=state.learned.has(skill.id),equipped=state.loadout.indexOf(skill.id),lockedLevel=(game()?.player?.level||1)<skill.level,prior=skill.tier===10&&domain.skills.slice(0,9).some(s=>!state.learned.has(s.id));return `<button class="skill-node ${learned?'learned':'locked'} ${equipped>=0?'equipped':''} ${skill.ultimate?'ultimate':''}" data-skill-id="${skill.id}" style="--domain:${domain.color}" aria-label="${esc(skill.name)}"><i>${skill.tier}</i><b>${esc(skill.name)}</b><span>${learned?(equipped>=0?`Slot ${equipped+1}`:'Aprendida'):lockedLevel?`Nv. ${skill.level}`:prior?'Complete o domínio':`${skill.cost} pts`}</span>${skill.gold?'<em>5 KK</em>':''}</button>`;}
function open(merchant=false){if(!game()?.running)return;state.merchant=!!merchant;createUi();render();$('#skillsPanel').classList.remove('hidden');game().paused=true;}
function close(){cancelHold();hideTooltip();$('#skillsPanel')?.classList.add('hidden');$('#skillConfirm')?.classList.add('hidden');if(game()?.running)game().paused=false;state.merchant=false;}
function onSkillPointerDown(event){const node=event.target.closest('.skill-node');if(!node)return;event.preventDefault();cancelHold();const skill=C.get(node.dataset.skillId);state.hold={timer:setTimeout(()=>{showTooltip(skill,node);state.hold=null;},1000),x:event.clientX,y:event.clientY};node.setPointerCapture?.(event.pointerId);}
function cancelHold(event){if(!state.hold)return;clearTimeout(state.hold.timer);const node=event?.target?.closest?.('.skill-node'),skill=node&&C.get(node.dataset.skillId),dx=event?Math.hypot(event.clientX-state.hold.x,event.clientY-state.hold.y):999;state.hold=null;if(skill&&dx<9)activate(skill);}
function showTooltip(skill,node){if(!skill)return;const tip=$('#skillTooltip'),r=node.getBoundingClientRect();tip.innerHTML=`<header><i style="--domain:${skill.domainColor}">${skill.tier}</i><div><small>${esc(skill.domainName)}</small><b>${esc(skill.name)}</b></div></header><p>${esc(skill.description)}</p><dl><div><dt>Nível</dt><dd>${skill.level}</dd></div><div><dt>Custo</dt><dd>${skill.cost} pts</dd></div><div><dt>Mana</dt><dd>${manaCost(skill)}</dd></div><div><dt>Recarga</dt><dd>${cooldown(skill)}s</dd></div></dl>${skill.gold?'<strong>Ascensão: 5.000.000 de ouro + domínio completo</strong>':''}`;tip.classList.remove('hidden');const w=tip.offsetWidth,h=tip.offsetHeight;tip.style.left=`${Math.max(10,Math.min(innerWidth-w-10,r.right+12))}px`;tip.style.top=`${Math.max(10,Math.min(innerHeight-h-10,r.top))}px`;}
function hideTooltip(){$('#skillTooltip')?.classList.add('hidden');}
function activate(skill){hideTooltip();if(state.learned.has(skill.id)){showEquip(skill);return;}if(!canBuy()){game()?.toast?.('Visite o Mestre de Habilidades em Astralum.');return;}showPurchase(skill);}
function modal(title,text,accept){const box=$('#skillConfirm');$('#skillConfirmTitle').textContent=title;$('#skillConfirmText').textContent=text;$('#skillConfirmSlots').classList.add('hidden');const button=$('#skillConfirmAccept');button.textContent='Confirmar compra';button.onclick=()=>{box.classList.add('hidden');void accept();};box.classList.remove('hidden');}
function showPurchase(skill){const suffix=skill.gold?' e 5.000.000 de ouro':'';modal(`Aprender ${skill.name}?`,`Esta habilidade consome ${skill.cost} pontos${suffix}. ${skill.description}`,()=>purchase(skill));}
function showEquip(skill){const box=$('#skillConfirm'),slots=$('#skillConfirmSlots');$('#skillConfirmTitle').textContent=`Equipar ${skill.name}`;$('#skillConfirmText').textContent='Escolha um dos cinco espaços da barra de habilidades.';slots.innerHTML=state.loadout.map((id,i)=>`<button data-equip-slot="${i}"><kbd>${i+1}</kbd><span>${esc(C.get(id)?.name||'Vazio')}</span></button>`).join('');slots.classList.remove('hidden');$('#skillConfirmAccept').textContent='Cancelar';$('#skillConfirmAccept').onclick=()=>box.classList.add('hidden');slots.querySelectorAll('[data-equip-slot]').forEach(b=>b.onclick=()=>{box.classList.add('hidden');void equip(skill,Number(b.dataset.equipSlot));});box.classList.remove('hidden');}
function errorMessage(error){const m=String(error?.message||error||'');if(m.includes('level_required'))return'Nível insuficiente.';if(m.includes('points_insufficient'))return'Pontos de skill insuficientes.';if(m.includes('domain_incomplete'))return'Aprenda as nove habilidades anteriores deste domínio.';if(m.includes('gold_insufficient'))return'Ouro insuficiente no progresso do servidor.';if(m.includes('already'))return'Habilidade já aprendida.';return'Não foi possível concluir a compra.';}
async function purchase(skill){const client=mp()?.client,id=characterId();if(client&&mp()?.session&&id){const{data,error}=await client.rpc('purchase_astraeon_skill',{target_character:id,target_skill:skill.id});if(error){game().toast(errorMessage(error));return;}applyRemote(data);if(skill.gold)game().gold=Math.max(0,Number(data.gold)||0);}else{recompute();const domain=classGroup().domains.find(d=>d.code===skill.domain);if((game().player.level||1)<skill.level||state.available<skill.cost||(skill.tier===10&&domain.skills.slice(0,9).some(s=>!state.learned.has(s.id)))||(skill.gold&&(game().gold||0)<skill.gold)){game().toast('Requisitos insuficientes para esta habilidade.');return;}state.learned.add(skill.id);if(skill.gold)game().gold-=skill.gold;saveLocal();refresh();}game().toast(`${skill.name} aprendida.`);}
async function equip(skill,slot){const client=mp()?.client,id=characterId();if(client&&mp()?.session&&id){const{data,error}=await client.rpc('equip_astraeon_skill',{target_character:id,target_skill:skill.id,target_slot:slot});if(error){game().toast('Não foi possível equipar a habilidade.');return;}applyRemote(data);}else{state.loadout=state.loadout.map(x=>x===skill.id?null:x);state.loadout[slot]=skill.id;saveLocal();refresh();}game().toast(`${skill.name} equipada no slot ${slot+1}.`);}
function manaCost(skill){return skill.ultimate?60:8+skill.tier*3;}
function cooldown(skill){return skill.ultimate?30:+Math.max(3,9.5-skill.tier*.45).toFixed(1);}
function targetFor(g,p,range=300){return g.closestMobTo(g.mouse.worldX,g.mouse.worldY,90)||g.closestMobTo(p.x,p.y,range);}
function cast(g,index){const skill=C.get(state.loadout[index]);if(!skill||!state.learned.has(skill.id)){g.toast('Nenhuma habilidade equipada neste espaço. Abra os Domínios com H.');return;}if(g.cooldowns[index]>0)return;const p=g.player,cost=manaCost(skill),target=targetFor(g,p,p.range*1.8),e=skill.effect;if(['strike','projectile','execute','drain'].includes(e)&&!target){g.toast('Nenhum alvo ao alcance.');return;}if(p.mana<cost){g.toast('Mana insuficiente.');return;}p.mana-=cost;g.cooldowns[index]=cooldown(skill);const amount=Math.round(p.power*skill.power/100),color=skill.domainColor;
 if(['strike','projectile','execute','drain'].includes(e)&&target){let damage=amount;if(e==='execute'&&target.hp/target.maxHp<.3)damage=Math.round(damage*1.5);g.hitMob(target,damage,Math.random()<p.crit+(skill.tier>=7?.15:0));if(e==='drain')p.hp=Math.min(p.maxHp,p.hp+Math.round(damage*.25));g.effects.push({type:e==='projectile'?'projectile':'slash',x:p.x,y:p.y,tx:target.x,ty:target.y,life:.3,max:.3,color});}
 else if(e==='dash'){const vx=g.mouse.worldX-p.x,vy=g.mouse.worldY-p.y,d=Math.max(1,Math.hypot(vx,vy)),step=85+skill.tier*9;g.moveEntity(p,vx/d*step,vy/d*step,10);g.areaDamage(p.x,p.y,55,amount);g.effects.push({type:'trail',x:p.x,y:p.y,life:.45,max:.45,color,radius:step});}
 else if(['area','trap'].includes(e)){const radius=70+skill.tier*9;g.areaDamage(p.x,p.y,radius,amount);g.effects.push({type:'ring',x:p.x,y:p.y,life:.6,max:.6,color,radius});}
 else if(e==='nova'){const radius=105+skill.tier*10,x=g.mouse.worldX,y=g.mouse.worldY;g.areaDamage(x,y,radius,amount);g.effects.push({type:'nova',x,y,life:.8,max:.8,color,radius});g.camera.shake=6;}
 else if(e==='shield'){p.invuln=Math.max(p.invuln,.7+skill.tier*.12);p.hp=Math.min(p.maxHp,p.hp+12+skill.tier*5);g.effects.push({type:'shield',x:p.x,y:p.y,life:p.invuln,max:p.invuln,color,radius:38});}
 else if(e==='heal'){p.hp=Math.min(p.maxHp,p.hp+18+skill.tier*7);p.mana=Math.min(p.maxMana,p.mana+8+skill.tier*3);g.effects.push({type:'shield',x:p.x,y:p.y,life:.8,max:.8,color,radius:42});}
 else if(e==='buff'){if(g.skillBuff){p.power=g.skillBuff.power;p.speed=g.skillBuff.speed;}g.skillBuff={until:performance.now()+(3+Math.floor(skill.tier/2))*1000,power:p.power,speed:p.speed,multiplier:1+(12+skill.tier*2)/100};p.power=Math.round(p.power*g.skillBuff.multiplier);p.speed=Math.round(p.speed*g.skillBuff.multiplier);g.effects.push({type:'burst',x:p.x,y:p.y,life:1,max:1,color,radius:60});}
 else if(e==='ultimate'){g.areaDamage(p.x,p.y,250,amount);p.hp=Math.min(p.maxHp,p.hp+Math.round(p.maxHp*.25));p.mana=Math.min(p.maxMana,p.mana+Math.round(p.maxMana*.2));g.effects.push({type:'nova',x:p.x,y:p.y,life:1.2,max:1.2,color,radius:250});g.camera.shake=10;}
 else if(!target)g.toast('Nenhum alvo ao alcance.');g.beep(620+skill.tier*25,.08,.035);refresh();}
function updateHotbar(){const g=game();if(!g)return;$$('#hotbar .skill').forEach((button,i)=>{const skill=C.get(state.loadout[i]);button.classList.toggle('skill-empty',!skill);button.classList.toggle('skill-equipped',!!skill);button.title=skill?`${skill.name} — ${skill.description}`:`Slot ${i+1} vazio · H para abrir Domínios`;let glyph=button.querySelector('.skill-glyph');if(!glyph){glyph=document.createElement('span');glyph.className='skill-glyph';button.insertBefore(glyph,button.querySelector('.cd'));}glyph.textContent=skill?skill.name.slice(0,1):'·';button.style.setProperty('--skill-color',skill?.domainColor||'#6d7480');});$$('#mobileControls [data-skill]').forEach((button,i)=>{const skill=C.get(state.loadout[i]);button.title=skill?.name||'Slot vazio';button.style.setProperty('--skill-color',skill?.domainColor||'#6d7480');});}
function refresh(){if($('#skillsPanel')&&!$('#skillsPanel').classList.contains('hidden'))render();updateHotbar();}
function installHooks(g){if(g.skillsV1Installed)return;g.skillsV1Installed=true;const start=g.startNew.bind(g),cont=g.continueGame.bind(g),save=g.save.bind(g),gain=g.gainXp.bind(g),update=g.update.bind(g);g.startNew=function(){const r=start();if(this.player){installLocal(null,true);saveLocal();setTimeout(syncRemote,300);}return r;};g.continueGame=function(){const raw=localState(),r=cont();if(this.player){installLocal(raw,false);setTimeout(syncRemote,300);}return r;};g.save=function(){const r=save();saveLocal();return r;};g.gainXp=function(amount){const before=this.player?.level||1,r=gain(amount),after=this.player?.level||before;if(after>before){recompute();this.toast(`Nível ${after}! +${(after-before)*3} pontos de skill.`);refresh();}return r;};g.castSkill=function(index){if(!this.running||this.paused)return;cast(this,Number(index));};g.update=function(dt){const r=update(dt);if(this.skillBuff&&performance.now()>=this.skillBuff.until&&this.player){this.player.power=this.skillBuff.power;this.player.speed=this.skillBuff.speed;this.skillBuff=null;}return r;};}
async function adminAllSkills(){const client=mp()?.client,id=characterId();if(!client||!id)return game()?.toast?.('Comando disponível apenas online.');const{data:isAdmin,error:aerr}=await client.rpc('astraeon_is_admin');if(aerr||isAdmin!==true)return game()?.toast?.('Comando exclusivo para administradores.');const{data,error}=await client.rpc('admin_unlock_all_astraeon_skills',{target_character:id});if(error){game().toast('Não foi possível liberar as habilidades.');return;}applyRemote(data);game().toast('ADM: todas as habilidades da classe foram aprendidas.');}
function installAdminCommand(){const wait=()=>{const form=$('#onlineChatForm'),input=$('#onlineChatInput');if(!form||!input){setTimeout(wait,150);return;}if(form.dataset.skillAdminCommand)return;form.dataset.skillAdminCommand='1';form.addEventListener('submit',event=>{if(String(input.value||'').trim().toLowerCase()!=='!allskill')return;event.preventDefault();event.stopImmediatePropagation();input.value='';void adminAllSkills();},true);};wait();}
function installKeyboard(){global.addEventListener('keydown',event=>{if((event.code!=='KeyH'&&event.key.toLowerCase()!=='h')||event.repeat)return;const active=document.activeElement;if(active?.closest('input,textarea,select,[contenteditable="true"],#onlineChat,#npcDialogue'))return;if(!game()?.running)return;event.preventDefault();event.stopImmediatePropagation();if($('#skillsPanel')?.classList.contains('hidden')!==false)open(false);else close();},true);}
function monitorCharacter(){setInterval(()=>{const id=characterId();if(id&&id!==state.lastCharacter){state.lastCharacter=id;void syncRemote();}},900);}
function install(){if(state.installed)return;const g=game();if(!g){setTimeout(install,80);return;}state.installed=true;createUi();installHooks(g);installKeyboard();installAdminCommand();monitorCharacter();installLocal(localState(),false);global.AstraeonSkillsV1={state,open,close,openMerchant:()=>open(true),syncRemote,adminAllSkills};}
if(document.readyState==='loading')global.addEventListener('DOMContentLoaded',install);else install();
})(window);
